# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: experimental/mandar/rpc/filer_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from open_util.net import protorpc_pb2 as open__util_dot_net_dot_protorpc__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+experimental/mandar/rpc/filer_service.proto\x12 cohesity.experimental.mandar.rpc\x1a\x1copen_util/net/protorpc.proto\"\x1d\n\rCreateFileArg\x12\x0c\n\x04name\x18\x01 \x01(\t\"\"\n\x10\x43reateFileResult\x12\x0e\n\x06status\x18\x01 \x01(\t\"=\n\x10ReadFileRangeArg\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06offset\x18\x02 \x01(\x03\x12\x0b\n\x03len\x18\x03 \x01(\x03\"6\n\x13ReadFileRangeResult\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\x03\">\n\x11WriteFileRangeArg\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06offset\x18\x02 \x01(\x03\x12\x0b\n\x03len\x18\x03 \x01(\x03\"7\n\x14WriteFileRangeResult\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\x03\x32\x91\x03\n\x0c\x46ilerService\x12s\n\nCreateFile\x12/.cohesity.experimental.mandar.rpc.CreateFileArg\x1a\x32.cohesity.experimental.mandar.rpc.CreateFileResult\"\x00\x12|\n\rReadFileRange\x12\x32.cohesity.experimental.mandar.rpc.ReadFileRangeArg\x1a\x35.cohesity.experimental.mandar.rpc.ReadFileRangeResult\"\x00\x12\x7f\n\x0eWriteFileRange\x12\x33.cohesity.experimental.mandar.rpc.WriteFileRangeArg\x1a\x36.cohesity.experimental.mandar.rpc.WriteFileRangeResult\"\x00\x1a\r\x80\xf1\x04\xe8\x07\x88\xf1\x04\x01\x90\xf1\x04\x02\x42\x03\x80\x01\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'experimental.mandar.rpc.filer_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\200\001\001'
  _globals['_FILERSERVICE']._loaded_options = None
  _globals['_FILERSERVICE']._serialized_options = b'\200\361\004\350\007\210\361\004\001\220\361\004\002'
  _globals['_CREATEFILEARG']._serialized_start=111
  _globals['_CREATEFILEARG']._serialized_end=140
  _globals['_CREATEFILERESULT']._serialized_start=142
  _globals['_CREATEFILERESULT']._serialized_end=176
  _globals['_READFILERANGEARG']._serialized_start=178
  _globals['_READFILERANGEARG']._serialized_end=239
  _globals['_READFILERANGERESULT']._serialized_start=241
  _globals['_READFILERANGERESULT']._serialized_end=295
  _globals['_WRITEFILERANGEARG']._serialized_start=297
  _globals['_WRITEFILERANGEARG']._serialized_end=359
  _globals['_WRITEFILERANGERESULT']._serialized_start=361
  _globals['_WRITEFILERANGERESULT']._serialized_end=416
  _globals['_FILERSERVICE']._serialized_start=419
  _globals['_FILERSERVICE']._serialized_end=820
# @@protoc_insertion_point(module_scope)
