# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: experimental/smurugesan/protobuf-3.6.0/src/google/protobuf/unittest_drop_unknown_fields.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n]experimental/smurugesan/protobuf-3.6.0/src/google/protobuf/unittest_drop_unknown_fields.proto\x12\x1cunittest_drop_unknown_fields\"\x85\x01\n\x03\x46oo\x12\x13\n\x0bint32_value\x18\x01 \x01(\x05\x12@\n\nenum_value\x18\x02 \x01(\x0e\x32,.unittest_drop_unknown_fields.Foo.NestedEnum\"\'\n\nNestedEnum\x12\x07\n\x03\x46OO\x10\x00\x12\x07\n\x03\x42\x41R\x10\x01\x12\x07\n\x03\x42\x41Z\x10\x02\"\xc7\x01\n\x12\x46ooWithExtraFields\x12\x13\n\x0bint32_value\x18\x01 \x01(\x05\x12O\n\nenum_value\x18\x02 \x01(\x0e\x32;.unittest_drop_unknown_fields.FooWithExtraFields.NestedEnum\x12\x19\n\x11\x65xtra_int32_value\x18\x03 \x01(\x05\"0\n\nNestedEnum\x12\x07\n\x03\x46OO\x10\x00\x12\x07\n\x03\x42\x41R\x10\x01\x12\x07\n\x03\x42\x41Z\x10\x02\x12\x07\n\x03QUX\x10\x03\x42,\xa2\x02\x0c\x44ropUnknowns\xaa\x02\x1aGoogle.Protobuf.TestProtosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'experimental.smurugesan.protobuf_3.6.0.src.google.protobuf.unittest_drop_unknown_fields_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\242\002\014DropUnknowns\252\002\032Google.Protobuf.TestProtos'
  _globals['_FOO']._serialized_start=128
  _globals['_FOO']._serialized_end=261
  _globals['_FOO_NESTEDENUM']._serialized_start=222
  _globals['_FOO_NESTEDENUM']._serialized_end=261
  _globals['_FOOWITHEXTRAFIELDS']._serialized_start=264
  _globals['_FOOWITHEXTRAFIELDS']._serialized_end=463
  _globals['_FOOWITHEXTRAFIELDS_NESTEDENUM']._serialized_start=415
  _globals['_FOOWITHEXTRAFIELDS_NESTEDENUM']._serialized_end=463
# @@protoc_insertion_point(module_scope)
