from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from typing import ClassVar as _ClassVar, Optional as _Optional

DESCRIPTOR: _descriptor.FileDescriptor

class NodeConfigProto(_message.Message):
    __slots__ = ("data_dirpath", "node_id_filepath", "cluster_id_filepath", "software_dirpath", "gandalf_dirpath", "gandalf_constituent_id_key", "gandalf_metadata_id_key", "cluster_config_key", "packages_dirpath", "services_gflags_key", "ssl_certificate_key", "disk_mounts_parent_relative_path", "disk_config_name", "apollo_dir_relative_path", "chunk_repository_dir_relative_path", "hydra_dir_relative_path", "scribe_dir_relative_path", "yoda_dir_relative_path", "elasticsearch_config_file", "elasticsearch_script_relative_path", "reverse_tunnel_script_relative_path", "gandalf_alerts_id_key", "scribe_table_id_key", "iris_users_key", "cluster_create_status_key", "clear_old_mount_points_script_relative_path", "elasticsearch_kill_busy_script_relative_path", "yoda_slave_dir_relative_path", "cluster_has_new_packages_key", "hardware_filepath", "mr_metadata_id_key", "rhino_script_relative_path", "nearline_adapter_ssl_validator_relative_path", "cluster_bringup_status_path", "software_config_dirpath", "software_platform_config_dirpath", "software_bin_dirpath", "disk_location_filepath", "free_node_alert_filepath", "memory_limit_filepath", "notify_disk_change_filepath", "nic_port_map_filepath", "node_software_version_history_filepath", "feature_list_key", "admin_user_name", "admin_rid", "default_domain_name", "iris_relative_path", "private_key_file_name", "scheduler_key", "logs_dir", "iris_master_key", "librarian_dir_relative_path", "groot_dir_relative_path", "scribe_view_config_key", "zero_metadata_fault_tolerance_file_path", "luceneserver_script_relative_path", "db_script_relative_path", "reporting_schema_dir_relative_path", "interface_link_state_filepath", "eagle_agent_dirpath", "tricorder_data_dirpath_deprecated", "athena_app_downloads_dirpath", "network_config_filepath", "cached_services_gflags_file_name", "helios_agent_key", "optimus_script_relative_path", "gandalf_antivirus_service_id_key", "bifrost_dir_relative_path", "selinux_avc_denials_chkpoint_file_path", "nexus_proxy_vip_epoch_filepath", "athena_ephemeral_volumes_base_path", "ssl_validator_relative_path", "elrond_dir_relative_path", "nfsshare_mounts_parent_relative_path", "notify_nfs_mount_change_filepath", "bridge_dir_relative_path", "bridge_nfs_auth_kerberos_relative_path", "elrond_tracked_io_log_dir_relative_path", "elrond_binary_logger_file_prefix", "ntp_freq_error_chkpoint_file_path", "elrond_access_model_key", "heimdall_dir_relative_path", "avc_denial_error_chkpoint_file_path", "remote_storage_config_filepath", "os_util_min_port", "patch_nodes_script_relative_path", "patch_dir_relative_path", "patch_logs_dir", "imported_patches_dir", "available_patches_dir", "applied_patches_dir", "patch_bin_dir", "active_patches_dir", "hotfix_dir", "patch_configs_dir", "teleport_script_path", "etl_server_script_relative_path", "offline_alerts_file_relative_path", "iris_http_port", "iris_https_port", "smbrpc_port", "nfs_sunrpc_port", "s3_port", "swift_port", "iscsi_port", "ovn_nb_port", "ovn_sb_port", "ovn_nb_raft_port", "ovn_sb_raft_port", "spire_server_port", "spire_federation_port", "athena_flannel_port", "athena_flannel_vxlan_port", "athena_flannel2_vxlan_port", "siren_port", "os_util_max_port", "bridge_port", "hydra_port", "bridge_insecure_grpc_server_port", "bridge_pigeon_grpc_port", "vault_proxy_port", "bridge_proxy_port", "bridge_secure_grpc_server_port", "madrox_port", "bridge_secondary_http_port", "newscribe_port", "newscribe_port_last", "rtclient_port", "scribe_port", "magneto_port", "magneto_read_replica_port", "magneto_api_server_grpc_port", "storage_proxy_port", "smb_proxy_port", "smb_proxy_http_port", "atom_grpc_port", "atom_port", "atom_protorpc_port", "smb2_proxy_port", "smb2_proxy_http_port", "throttler_port", "nfs_proxy_port", "nfs_proxy_http_port", "alerts_port", "keychain_port", "gandalf_port", "gandalf_grpc_port", "pigeon_port", "bridge_pigeon_tls_port", "pigeon_alternate_port", "nexus_pprof_port", "nexus_port", "nexus_proxy_port", "nexus_secure_port", "tricorder_port_deprecated", "re_ip_port", "eagle_agent_port", "re_ip_socket_port", "mcmetl_server_port", "licensing_port", "olympus_server_port", "iris_proxy_port", "apollo_port", "apollo_grpc_port", "compass_port", "stats_port", "pulse_grpc_port", "gaia_port", "gaia_grpc_port", "athena_kube_scheduler_secure_port", "athena_kube_controller_secure_port", "athena_kube_proxy_healthz_port", "athena_kube_proxy_metrics_port", "athena_kubelet_healthz_port", "athena_kube_scheduler_healthz_port", "nexus_envoy_admin_port", "nexus_service_identity_outbound_handler", "nexus_service_identity_inbound_handler", "statscollector_port", "athena_port", "athena_docker_registry_port", "optimus_port", "athena_proxy_docker_registry_port", "athena_proxy_api_server_port", "athena_proxy_config_port", "athena_etcd_client_port", "athena_etcd_peer_port", "athena_kubernetes_apiserver_http_port", "athena_kubelet_cadvisor_port", "athena_kubelet_https_port", "athena_coredns_port", "athena_coredns_health_port", "athena_proxy_port", "athena_proxy_internal_port", "athena_kubernetes_apiserver_https_port", "athena_watchdog_port", "etl_server_grpc_port", "athena_sys_srvc_docker_registry_port", "elasticsearch_min_port", "elasticsearch_max_port", "elasticsearch_node_discovery_port", "helios_onprem_docker_registry_port", "helios_onprem_etcd_client_port", "helios_onprem_etcd_peer_port", "helios_onprem_iris_http_port", "helios_onprem_iris_https_port", "rhino_port", "yoda_port", "librarian_port", "luceneserver_port", "elrond_port", "heimdall_port", "yoda_agent_port", "yoda_agent_http_port", "opensearch_min_port", "opensearch_max_port", "groot_port", "report_database_port", "report_server_port", "node_exporter_port", "broker_services_port", "broker_bifrost_port", "broker_http_port", "socks_server_broker_listen_port_range", "rigel_local_bridge_ports_range", "bifrost_http_port", "socks_grpc_proxy_port", "socks_grpc_agent_port", "icebox_port", "patch_exec_port", "testing_min_port", "testing_max_port", "ephemeral_min_port", "ephemeral_max_port", "athena_min_dynamic_node_port", "athena_max_dynamic_node_port", "athena_min_static_node_port", "athena_max_static_node_port", "elixir_http_port", "vulscanner_port", "bootstrapper_port", "kube_dashboard_port", "testservice_port", "dlp_port", "eventing_service_port", "prometheus_port", "kafka_port", "agentinstall_http_port", "imanis_grpc_port", "imanis_resource_manager_port", "imanis_node_manager_port", "workqueue_server_grpc_port", "workqueue_server_http_port", "metadata_service_grpc_port", "argus_app_port", "magnus_api_port", "magnus_server_grpc_server_port", "magnus_server_http_server_port", "magnus_actor_http_server_port", "ods_app_port", "sheltered_harbor_control_port", "sheltered_harbor_data_preparer_port", "sheltered_harbor_restorer_port", "sftp_app_port", "sftp_rest_app_port", "routing_ospf_port", "routing_bgp_port", "routing_rip_port", "janus_port", "pushclient_port", "aegis_port", "resource_manager_api_server_grpc_port", "elasticsearch_system_service_port", "elasticsearch_system_service_transport_port", "bifrost_keychain_client_local_port", "bifrost_stats_client_local_port", "bifrost_throttler_client_local_port", "bifrost_broker_stub_local_port", "bifrost_bridge_pigeon_local_port", "bifrost_snapfs_server_local_port", "bifrost_bridge_secure_snapfs_local_port", "cohesity_ca_port", "cohesity_ca_grpc_server_port", "cohesion_port", "cohesion_grpc_port", "linux_agent_port", "linux_agent_grpc_port", "bridge_desirable_chunk_file_size_MB", "bridge_desirable_ec_chunk_file_size_MB", "bridge_desirable_ec_stripe_size_MB", "bridge_estimated_compression_factor", "iris_tenants_key", "athena_kubernetes_config_key", "alerts_data_key", "bulletin_board_key", "pg_db_info_key", "helios_metadata_view", "helios_metadata_dirpath", "postgres_datadir_relative_path", "alert_policies_change_notify_key", "gandalf_iris_metadata_id_key", "axon_config_key", "axon_service_access_interface_prefix", "ssl_certificate_key_magneto_agent", "bifrost_rtuser_username", "healthcheck_results_filepath", "bifrost_rtuser_authorized_keys_filepath", "save_tenant_bifrost_rt_pub_key_script_relative_path", "bifrost_rtuser_sshd_force_command_script_path", "axon_mac_oui", "linux_default_commands_filepath", "linux_custom_commands_filepath", "helios_certificate_key", "cluster_reset_state_filepath", "current_network_config_filepath", "staging_network_config_filepath", "bifrost_constituent_id_filename", "bifrost_config_file_name", "bifrost_rt_config_filename", "tenant_certificate_key", "cluster_log_key", "icebox_dir_relative_path", "bifrost_latest_config_file_name", "bifrost_vlan_config_key", "bifrost_ipam_config_key", "bifrost_vm_config_key", "system_service_pkg_build_location", "system_service_pkg_athena_location", "bifrost_pkg_build_location", "bifrost_pkg_athena_location", "system_services_key", "rigel_transient_config_key", "ca_trust_store_key", "utility_app_info_key", "ocsp_cache_key", "ticket_approval_file_relative_path", "packages_config_key", "encryption_key", "sql_agent_ca_cert_path", "allow_cluster_destroy_marker_file_path", "system_service_json_build_location", "system_service_json_nexus_location", "system_service_vec_nexus_location", "etcd_config_key", "rigel_connectivity_key", "node_base_os_version_history_dirpath", "etcd_config_local_proto_filepath", "nexus_hmac_config_key", "email_otp_key", "sfdc_instance_task_ids_key", "audit_log_collection_key", "opensearch_config_file", "opensearch_script_relative_path", "opensearch_pemcert_filepath", "opensearch_pemkey_filepath", "opensearch_pemtrustedcas_filepath", "spire_service_identity_base_path", "kubelet_memory_limit_in_bytes_path", "cluster_disaggregate_state_filepath", "user_tunings_key", "upgrade_check_dir_path", "support_tool_box_pkg_path", "support_tool_box_pkg_dir", "s3_grpc_port", "customer_managed_baseos_file_path", "des_decrypt_lib_path", "tenant_migration_key", "ssh_key_pair_store_key", "cohesity_ca_key", "cohesity_ca_certificates_key", "yoda_entity_id_migration_state_key", "cohesion_dir_relative_path", "user_bootstrap_cohesity_ca_key", "customer_ca_signed_cluster_certificates", "rotated_cohesity_ca_certificates", "on_prem_rigel_config_key", "downloaded_patches_key", "patches_history_key", "patch_orchestration_state_key", "prechecks_data_key", "helios_certificate_encryption_key")
    DATA_DIRPATH_FIELD_NUMBER: _ClassVar[int]
    NODE_ID_FILEPATH_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_ID_FILEPATH_FIELD_NUMBER: _ClassVar[int]
    SOFTWARE_DIRPATH_FIELD_NUMBER: _ClassVar[int]
    GANDALF_DIRPATH_FIELD_NUMBER: _ClassVar[int]
    GANDALF_CONSTITUENT_ID_KEY_FIELD_NUMBER: _ClassVar[int]
    GANDALF_METADATA_ID_KEY_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_CONFIG_KEY_FIELD_NUMBER: _ClassVar[int]
    PACKAGES_DIRPATH_FIELD_NUMBER: _ClassVar[int]
    SERVICES_GFLAGS_KEY_FIELD_NUMBER: _ClassVar[int]
    SSL_CERTIFICATE_KEY_FIELD_NUMBER: _ClassVar[int]
    DISK_MOUNTS_PARENT_RELATIVE_PATH_FIELD_NUMBER: _ClassVar[int]
    DISK_CONFIG_NAME_FIELD_NUMBER: _ClassVar[int]
    APOLLO_DIR_RELATIVE_PATH_FIELD_NUMBER: _ClassVar[int]
    CHUNK_REPOSITORY_DIR_RELATIVE_PATH_FIELD_NUMBER: _ClassVar[int]
    HYDRA_DIR_RELATIVE_PATH_FIELD_NUMBER: _ClassVar[int]
    SCRIBE_DIR_RELATIVE_PATH_FIELD_NUMBER: _ClassVar[int]
    YODA_DIR_RELATIVE_PATH_FIELD_NUMBER: _ClassVar[int]
    ELASTICSEARCH_CONFIG_FILE_FIELD_NUMBER: _ClassVar[int]
    ELASTICSEARCH_SCRIPT_RELATIVE_PATH_FIELD_NUMBER: _ClassVar[int]
    REVERSE_TUNNEL_SCRIPT_RELATIVE_PATH_FIELD_NUMBER: _ClassVar[int]
    GANDALF_ALERTS_ID_KEY_FIELD_NUMBER: _ClassVar[int]
    SCRIBE_TABLE_ID_KEY_FIELD_NUMBER: _ClassVar[int]
    IRIS_USERS_KEY_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_CREATE_STATUS_KEY_FIELD_NUMBER: _ClassVar[int]
    CLEAR_OLD_MOUNT_POINTS_SCRIPT_RELATIVE_PATH_FIELD_NUMBER: _ClassVar[int]
    ELASTICSEARCH_KILL_BUSY_SCRIPT_RELATIVE_PATH_FIELD_NUMBER: _ClassVar[int]
    YODA_SLAVE_DIR_RELATIVE_PATH_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_HAS_NEW_PACKAGES_KEY_FIELD_NUMBER: _ClassVar[int]
    HARDWARE_FILEPATH_FIELD_NUMBER: _ClassVar[int]
    MR_METADATA_ID_KEY_FIELD_NUMBER: _ClassVar[int]
    RHINO_SCRIPT_RELATIVE_PATH_FIELD_NUMBER: _ClassVar[int]
    NEARLINE_ADAPTER_SSL_VALIDATOR_RELATIVE_PATH_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_BRINGUP_STATUS_PATH_FIELD_NUMBER: _ClassVar[int]
    SOFTWARE_CONFIG_DIRPATH_FIELD_NUMBER: _ClassVar[int]
    SOFTWARE_PLATFORM_CONFIG_DIRPATH_FIELD_NUMBER: _ClassVar[int]
    SOFTWARE_BIN_DIRPATH_FIELD_NUMBER: _ClassVar[int]
    DISK_LOCATION_FILEPATH_FIELD_NUMBER: _ClassVar[int]
    FREE_NODE_ALERT_FILEPATH_FIELD_NUMBER: _ClassVar[int]
    MEMORY_LIMIT_FILEPATH_FIELD_NUMBER: _ClassVar[int]
    NOTIFY_DISK_CHANGE_FILEPATH_FIELD_NUMBER: _ClassVar[int]
    NIC_PORT_MAP_FILEPATH_FIELD_NUMBER: _ClassVar[int]
    NODE_SOFTWARE_VERSION_HISTORY_FILEPATH_FIELD_NUMBER: _ClassVar[int]
    FEATURE_LIST_KEY_FIELD_NUMBER: _ClassVar[int]
    ADMIN_USER_NAME_FIELD_NUMBER: _ClassVar[int]
    ADMIN_RID_FIELD_NUMBER: _ClassVar[int]
    DEFAULT_DOMAIN_NAME_FIELD_NUMBER: _ClassVar[int]
    IRIS_RELATIVE_PATH_FIELD_NUMBER: _ClassVar[int]
    PRIVATE_KEY_FILE_NAME_FIELD_NUMBER: _ClassVar[int]
    SCHEDULER_KEY_FIELD_NUMBER: _ClassVar[int]
    LOGS_DIR_FIELD_NUMBER: _ClassVar[int]
    IRIS_MASTER_KEY_FIELD_NUMBER: _ClassVar[int]
    LIBRARIAN_DIR_RELATIVE_PATH_FIELD_NUMBER: _ClassVar[int]
    GROOT_DIR_RELATIVE_PATH_FIELD_NUMBER: _ClassVar[int]
    SCRIBE_VIEW_CONFIG_KEY_FIELD_NUMBER: _ClassVar[int]
    ZERO_METADATA_FAULT_TOLERANCE_FILE_PATH_FIELD_NUMBER: _ClassVar[int]
    LUCENESERVER_SCRIPT_RELATIVE_PATH_FIELD_NUMBER: _ClassVar[int]
    DB_SCRIPT_RELATIVE_PATH_FIELD_NUMBER: _ClassVar[int]
    REPORTING_SCHEMA_DIR_RELATIVE_PATH_FIELD_NUMBER: _ClassVar[int]
    INTERFACE_LINK_STATE_FILEPATH_FIELD_NUMBER: _ClassVar[int]
    EAGLE_AGENT_DIRPATH_FIELD_NUMBER: _ClassVar[int]
    TRICORDER_DATA_DIRPATH_DEPRECATED_FIELD_NUMBER: _ClassVar[int]
    ATHENA_APP_DOWNLOADS_DIRPATH_FIELD_NUMBER: _ClassVar[int]
    NETWORK_CONFIG_FILEPATH_FIELD_NUMBER: _ClassVar[int]
    CACHED_SERVICES_GFLAGS_FILE_NAME_FIELD_NUMBER: _ClassVar[int]
    HELIOS_AGENT_KEY_FIELD_NUMBER: _ClassVar[int]
    OPTIMUS_SCRIPT_RELATIVE_PATH_FIELD_NUMBER: _ClassVar[int]
    GANDALF_ANTIVIRUS_SERVICE_ID_KEY_FIELD_NUMBER: _ClassVar[int]
    BIFROST_DIR_RELATIVE_PATH_FIELD_NUMBER: _ClassVar[int]
    SELINUX_AVC_DENIALS_CHKPOINT_FILE_PATH_FIELD_NUMBER: _ClassVar[int]
    NEXUS_PROXY_VIP_EPOCH_FILEPATH_FIELD_NUMBER: _ClassVar[int]
    ATHENA_EPHEMERAL_VOLUMES_BASE_PATH_FIELD_NUMBER: _ClassVar[int]
    SSL_VALIDATOR_RELATIVE_PATH_FIELD_NUMBER: _ClassVar[int]
    ELROND_DIR_RELATIVE_PATH_FIELD_NUMBER: _ClassVar[int]
    NFSSHARE_MOUNTS_PARENT_RELATIVE_PATH_FIELD_NUMBER: _ClassVar[int]
    NOTIFY_NFS_MOUNT_CHANGE_FILEPATH_FIELD_NUMBER: _ClassVar[int]
    BRIDGE_DIR_RELATIVE_PATH_FIELD_NUMBER: _ClassVar[int]
    BRIDGE_NFS_AUTH_KERBEROS_RELATIVE_PATH_FIELD_NUMBER: _ClassVar[int]
    ELROND_TRACKED_IO_LOG_DIR_RELATIVE_PATH_FIELD_NUMBER: _ClassVar[int]
    ELROND_BINARY_LOGGER_FILE_PREFIX_FIELD_NUMBER: _ClassVar[int]
    NTP_FREQ_ERROR_CHKPOINT_FILE_PATH_FIELD_NUMBER: _ClassVar[int]
    ELROND_ACCESS_MODEL_KEY_FIELD_NUMBER: _ClassVar[int]
    HEIMDALL_DIR_RELATIVE_PATH_FIELD_NUMBER: _ClassVar[int]
    AVC_DENIAL_ERROR_CHKPOINT_FILE_PATH_FIELD_NUMBER: _ClassVar[int]
    REMOTE_STORAGE_CONFIG_FILEPATH_FIELD_NUMBER: _ClassVar[int]
    OS_UTIL_MIN_PORT_FIELD_NUMBER: _ClassVar[int]
    PATCH_NODES_SCRIPT_RELATIVE_PATH_FIELD_NUMBER: _ClassVar[int]
    PATCH_DIR_RELATIVE_PATH_FIELD_NUMBER: _ClassVar[int]
    PATCH_LOGS_DIR_FIELD_NUMBER: _ClassVar[int]
    IMPORTED_PATCHES_DIR_FIELD_NUMBER: _ClassVar[int]
    AVAILABLE_PATCHES_DIR_FIELD_NUMBER: _ClassVar[int]
    APPLIED_PATCHES_DIR_FIELD_NUMBER: _ClassVar[int]
    PATCH_BIN_DIR_FIELD_NUMBER: _ClassVar[int]
    ACTIVE_PATCHES_DIR_FIELD_NUMBER: _ClassVar[int]
    HOTFIX_DIR_FIELD_NUMBER: _ClassVar[int]
    PATCH_CONFIGS_DIR_FIELD_NUMBER: _ClassVar[int]
    TELEPORT_SCRIPT_PATH_FIELD_NUMBER: _ClassVar[int]
    ETL_SERVER_SCRIPT_RELATIVE_PATH_FIELD_NUMBER: _ClassVar[int]
    OFFLINE_ALERTS_FILE_RELATIVE_PATH_FIELD_NUMBER: _ClassVar[int]
    IRIS_HTTP_PORT_FIELD_NUMBER: _ClassVar[int]
    IRIS_HTTPS_PORT_FIELD_NUMBER: _ClassVar[int]
    SMBRPC_PORT_FIELD_NUMBER: _ClassVar[int]
    NFS_SUNRPC_PORT_FIELD_NUMBER: _ClassVar[int]
    S3_PORT_FIELD_NUMBER: _ClassVar[int]
    SWIFT_PORT_FIELD_NUMBER: _ClassVar[int]
    ISCSI_PORT_FIELD_NUMBER: _ClassVar[int]
    OVN_NB_PORT_FIELD_NUMBER: _ClassVar[int]
    OVN_SB_PORT_FIELD_NUMBER: _ClassVar[int]
    OVN_NB_RAFT_PORT_FIELD_NUMBER: _ClassVar[int]
    OVN_SB_RAFT_PORT_FIELD_NUMBER: _ClassVar[int]
    SPIRE_SERVER_PORT_FIELD_NUMBER: _ClassVar[int]
    SPIRE_FEDERATION_PORT_FIELD_NUMBER: _ClassVar[int]
    ATHENA_FLANNEL_PORT_FIELD_NUMBER: _ClassVar[int]
    ATHENA_FLANNEL_VXLAN_PORT_FIELD_NUMBER: _ClassVar[int]
    ATHENA_FLANNEL2_VXLAN_PORT_FIELD_NUMBER: _ClassVar[int]
    SIREN_PORT_FIELD_NUMBER: _ClassVar[int]
    OS_UTIL_MAX_PORT_FIELD_NUMBER: _ClassVar[int]
    BRIDGE_PORT_FIELD_NUMBER: _ClassVar[int]
    HYDRA_PORT_FIELD_NUMBER: _ClassVar[int]
    BRIDGE_INSECURE_GRPC_SERVER_PORT_FIELD_NUMBER: _ClassVar[int]
    BRIDGE_PIGEON_GRPC_PORT_FIELD_NUMBER: _ClassVar[int]
    VAULT_PROXY_PORT_FIELD_NUMBER: _ClassVar[int]
    BRIDGE_PROXY_PORT_FIELD_NUMBER: _ClassVar[int]
    BRIDGE_SECURE_GRPC_SERVER_PORT_FIELD_NUMBER: _ClassVar[int]
    MADROX_PORT_FIELD_NUMBER: _ClassVar[int]
    BRIDGE_SECONDARY_HTTP_PORT_FIELD_NUMBER: _ClassVar[int]
    NEWSCRIBE_PORT_FIELD_NUMBER: _ClassVar[int]
    NEWSCRIBE_PORT_LAST_FIELD_NUMBER: _ClassVar[int]
    RTCLIENT_PORT_FIELD_NUMBER: _ClassVar[int]
    SCRIBE_PORT_FIELD_NUMBER: _ClassVar[int]
    MAGNETO_PORT_FIELD_NUMBER: _ClassVar[int]
    MAGNETO_READ_REPLICA_PORT_FIELD_NUMBER: _ClassVar[int]
    MAGNETO_API_SERVER_GRPC_PORT_FIELD_NUMBER: _ClassVar[int]
    STORAGE_PROXY_PORT_FIELD_NUMBER: _ClassVar[int]
    SMB_PROXY_PORT_FIELD_NUMBER: _ClassVar[int]
    SMB_PROXY_HTTP_PORT_FIELD_NUMBER: _ClassVar[int]
    ATOM_GRPC_PORT_FIELD_NUMBER: _ClassVar[int]
    ATOM_PORT_FIELD_NUMBER: _ClassVar[int]
    ATOM_PROTORPC_PORT_FIELD_NUMBER: _ClassVar[int]
    SMB2_PROXY_PORT_FIELD_NUMBER: _ClassVar[int]
    SMB2_PROXY_HTTP_PORT_FIELD_NUMBER: _ClassVar[int]
    THROTTLER_PORT_FIELD_NUMBER: _ClassVar[int]
    NFS_PROXY_PORT_FIELD_NUMBER: _ClassVar[int]
    NFS_PROXY_HTTP_PORT_FIELD_NUMBER: _ClassVar[int]
    ALERTS_PORT_FIELD_NUMBER: _ClassVar[int]
    KEYCHAIN_PORT_FIELD_NUMBER: _ClassVar[int]
    GANDALF_PORT_FIELD_NUMBER: _ClassVar[int]
    GANDALF_GRPC_PORT_FIELD_NUMBER: _ClassVar[int]
    PIGEON_PORT_FIELD_NUMBER: _ClassVar[int]
    BRIDGE_PIGEON_TLS_PORT_FIELD_NUMBER: _ClassVar[int]
    PIGEON_ALTERNATE_PORT_FIELD_NUMBER: _ClassVar[int]
    NEXUS_PPROF_PORT_FIELD_NUMBER: _ClassVar[int]
    NEXUS_PORT_FIELD_NUMBER: _ClassVar[int]
    NEXUS_PROXY_PORT_FIELD_NUMBER: _ClassVar[int]
    NEXUS_SECURE_PORT_FIELD_NUMBER: _ClassVar[int]
    TRICORDER_PORT_DEPRECATED_FIELD_NUMBER: _ClassVar[int]
    RE_IP_PORT_FIELD_NUMBER: _ClassVar[int]
    EAGLE_AGENT_PORT_FIELD_NUMBER: _ClassVar[int]
    RE_IP_SOCKET_PORT_FIELD_NUMBER: _ClassVar[int]
    MCMETL_SERVER_PORT_FIELD_NUMBER: _ClassVar[int]
    LICENSING_PORT_FIELD_NUMBER: _ClassVar[int]
    OLYMPUS_SERVER_PORT_FIELD_NUMBER: _ClassVar[int]
    IRIS_PROXY_PORT_FIELD_NUMBER: _ClassVar[int]
    APOLLO_PORT_FIELD_NUMBER: _ClassVar[int]
    APOLLO_GRPC_PORT_FIELD_NUMBER: _ClassVar[int]
    COMPASS_PORT_FIELD_NUMBER: _ClassVar[int]
    STATS_PORT_FIELD_NUMBER: _ClassVar[int]
    PULSE_GRPC_PORT_FIELD_NUMBER: _ClassVar[int]
    GAIA_PORT_FIELD_NUMBER: _ClassVar[int]
    GAIA_GRPC_PORT_FIELD_NUMBER: _ClassVar[int]
    ATHENA_KUBE_SCHEDULER_SECURE_PORT_FIELD_NUMBER: _ClassVar[int]
    ATHENA_KUBE_CONTROLLER_SECURE_PORT_FIELD_NUMBER: _ClassVar[int]
    ATHENA_KUBE_PROXY_HEALTHZ_PORT_FIELD_NUMBER: _ClassVar[int]
    ATHENA_KUBE_PROXY_METRICS_PORT_FIELD_NUMBER: _ClassVar[int]
    ATHENA_KUBELET_HEALTHZ_PORT_FIELD_NUMBER: _ClassVar[int]
    ATHENA_KUBE_SCHEDULER_HEALTHZ_PORT_FIELD_NUMBER: _ClassVar[int]
    NEXUS_ENVOY_ADMIN_PORT_FIELD_NUMBER: _ClassVar[int]
    NEXUS_SERVICE_IDENTITY_OUTBOUND_HANDLER_FIELD_NUMBER: _ClassVar[int]
    NEXUS_SERVICE_IDENTITY_INBOUND_HANDLER_FIELD_NUMBER: _ClassVar[int]
    STATSCOLLECTOR_PORT_FIELD_NUMBER: _ClassVar[int]
    ATHENA_PORT_FIELD_NUMBER: _ClassVar[int]
    ATHENA_DOCKER_REGISTRY_PORT_FIELD_NUMBER: _ClassVar[int]
    OPTIMUS_PORT_FIELD_NUMBER: _ClassVar[int]
    ATHENA_PROXY_DOCKER_REGISTRY_PORT_FIELD_NUMBER: _ClassVar[int]
    ATHENA_PROXY_API_SERVER_PORT_FIELD_NUMBER: _ClassVar[int]
    ATHENA_PROXY_CONFIG_PORT_FIELD_NUMBER: _ClassVar[int]
    ATHENA_ETCD_CLIENT_PORT_FIELD_NUMBER: _ClassVar[int]
    ATHENA_ETCD_PEER_PORT_FIELD_NUMBER: _ClassVar[int]
    ATHENA_KUBERNETES_APISERVER_HTTP_PORT_FIELD_NUMBER: _ClassVar[int]
    ATHENA_KUBELET_CADVISOR_PORT_FIELD_NUMBER: _ClassVar[int]
    ATHENA_KUBELET_HTTPS_PORT_FIELD_NUMBER: _ClassVar[int]
    ATHENA_COREDNS_PORT_FIELD_NUMBER: _ClassVar[int]
    ATHENA_COREDNS_HEALTH_PORT_FIELD_NUMBER: _ClassVar[int]
    ATHENA_PROXY_PORT_FIELD_NUMBER: _ClassVar[int]
    ATHENA_PROXY_INTERNAL_PORT_FIELD_NUMBER: _ClassVar[int]
    ATHENA_KUBERNETES_APISERVER_HTTPS_PORT_FIELD_NUMBER: _ClassVar[int]
    ATHENA_WATCHDOG_PORT_FIELD_NUMBER: _ClassVar[int]
    ETL_SERVER_GRPC_PORT_FIELD_NUMBER: _ClassVar[int]
    ATHENA_SYS_SRVC_DOCKER_REGISTRY_PORT_FIELD_NUMBER: _ClassVar[int]
    ELASTICSEARCH_MIN_PORT_FIELD_NUMBER: _ClassVar[int]
    ELASTICSEARCH_MAX_PORT_FIELD_NUMBER: _ClassVar[int]
    ELASTICSEARCH_NODE_DISCOVERY_PORT_FIELD_NUMBER: _ClassVar[int]
    HELIOS_ONPREM_DOCKER_REGISTRY_PORT_FIELD_NUMBER: _ClassVar[int]
    HELIOS_ONPREM_ETCD_CLIENT_PORT_FIELD_NUMBER: _ClassVar[int]
    HELIOS_ONPREM_ETCD_PEER_PORT_FIELD_NUMBER: _ClassVar[int]
    HELIOS_ONPREM_IRIS_HTTP_PORT_FIELD_NUMBER: _ClassVar[int]
    HELIOS_ONPREM_IRIS_HTTPS_PORT_FIELD_NUMBER: _ClassVar[int]
    RHINO_PORT_FIELD_NUMBER: _ClassVar[int]
    YODA_PORT_FIELD_NUMBER: _ClassVar[int]
    LIBRARIAN_PORT_FIELD_NUMBER: _ClassVar[int]
    LUCENESERVER_PORT_FIELD_NUMBER: _ClassVar[int]
    ELROND_PORT_FIELD_NUMBER: _ClassVar[int]
    HEIMDALL_PORT_FIELD_NUMBER: _ClassVar[int]
    YODA_AGENT_PORT_FIELD_NUMBER: _ClassVar[int]
    YODA_AGENT_HTTP_PORT_FIELD_NUMBER: _ClassVar[int]
    OPENSEARCH_MIN_PORT_FIELD_NUMBER: _ClassVar[int]
    OPENSEARCH_MAX_PORT_FIELD_NUMBER: _ClassVar[int]
    GROOT_PORT_FIELD_NUMBER: _ClassVar[int]
    REPORT_DATABASE_PORT_FIELD_NUMBER: _ClassVar[int]
    REPORT_SERVER_PORT_FIELD_NUMBER: _ClassVar[int]
    NODE_EXPORTER_PORT_FIELD_NUMBER: _ClassVar[int]
    BROKER_SERVICES_PORT_FIELD_NUMBER: _ClassVar[int]
    BROKER_BIFROST_PORT_FIELD_NUMBER: _ClassVar[int]
    BROKER_HTTP_PORT_FIELD_NUMBER: _ClassVar[int]
    SOCKS_SERVER_BROKER_LISTEN_PORT_RANGE_FIELD_NUMBER: _ClassVar[int]
    RIGEL_LOCAL_BRIDGE_PORTS_RANGE_FIELD_NUMBER: _ClassVar[int]
    BIFROST_HTTP_PORT_FIELD_NUMBER: _ClassVar[int]
    SOCKS_GRPC_PROXY_PORT_FIELD_NUMBER: _ClassVar[int]
    SOCKS_GRPC_AGENT_PORT_FIELD_NUMBER: _ClassVar[int]
    ICEBOX_PORT_FIELD_NUMBER: _ClassVar[int]
    PATCH_EXEC_PORT_FIELD_NUMBER: _ClassVar[int]
    TESTING_MIN_PORT_FIELD_NUMBER: _ClassVar[int]
    TESTING_MAX_PORT_FIELD_NUMBER: _ClassVar[int]
    EPHEMERAL_MIN_PORT_FIELD_NUMBER: _ClassVar[int]
    EPHEMERAL_MAX_PORT_FIELD_NUMBER: _ClassVar[int]
    ATHENA_MIN_DYNAMIC_NODE_PORT_FIELD_NUMBER: _ClassVar[int]
    ATHENA_MAX_DYNAMIC_NODE_PORT_FIELD_NUMBER: _ClassVar[int]
    ATHENA_MIN_STATIC_NODE_PORT_FIELD_NUMBER: _ClassVar[int]
    ATHENA_MAX_STATIC_NODE_PORT_FIELD_NUMBER: _ClassVar[int]
    ELIXIR_HTTP_PORT_FIELD_NUMBER: _ClassVar[int]
    VULSCANNER_PORT_FIELD_NUMBER: _ClassVar[int]
    BOOTSTRAPPER_PORT_FIELD_NUMBER: _ClassVar[int]
    KUBE_DASHBOARD_PORT_FIELD_NUMBER: _ClassVar[int]
    TESTSERVICE_PORT_FIELD_NUMBER: _ClassVar[int]
    DLP_PORT_FIELD_NUMBER: _ClassVar[int]
    EVENTING_SERVICE_PORT_FIELD_NUMBER: _ClassVar[int]
    PROMETHEUS_PORT_FIELD_NUMBER: _ClassVar[int]
    KAFKA_PORT_FIELD_NUMBER: _ClassVar[int]
    AGENTINSTALL_HTTP_PORT_FIELD_NUMBER: _ClassVar[int]
    IMANIS_GRPC_PORT_FIELD_NUMBER: _ClassVar[int]
    IMANIS_RESOURCE_MANAGER_PORT_FIELD_NUMBER: _ClassVar[int]
    IMANIS_NODE_MANAGER_PORT_FIELD_NUMBER: _ClassVar[int]
    WORKQUEUE_SERVER_GRPC_PORT_FIELD_NUMBER: _ClassVar[int]
    WORKQUEUE_SERVER_HTTP_PORT_FIELD_NUMBER: _ClassVar[int]
    METADATA_SERVICE_GRPC_PORT_FIELD_NUMBER: _ClassVar[int]
    ARGUS_APP_PORT_FIELD_NUMBER: _ClassVar[int]
    MAGNUS_API_PORT_FIELD_NUMBER: _ClassVar[int]
    MAGNUS_SERVER_GRPC_SERVER_PORT_FIELD_NUMBER: _ClassVar[int]
    MAGNUS_SERVER_HTTP_SERVER_PORT_FIELD_NUMBER: _ClassVar[int]
    MAGNUS_ACTOR_HTTP_SERVER_PORT_FIELD_NUMBER: _ClassVar[int]
    ODS_APP_PORT_FIELD_NUMBER: _ClassVar[int]
    SHELTERED_HARBOR_CONTROL_PORT_FIELD_NUMBER: _ClassVar[int]
    SHELTERED_HARBOR_DATA_PREPARER_PORT_FIELD_NUMBER: _ClassVar[int]
    SHELTERED_HARBOR_RESTORER_PORT_FIELD_NUMBER: _ClassVar[int]
    SFTP_APP_PORT_FIELD_NUMBER: _ClassVar[int]
    SFTP_REST_APP_PORT_FIELD_NUMBER: _ClassVar[int]
    ROUTING_OSPF_PORT_FIELD_NUMBER: _ClassVar[int]
    ROUTING_BGP_PORT_FIELD_NUMBER: _ClassVar[int]
    ROUTING_RIP_PORT_FIELD_NUMBER: _ClassVar[int]
    JANUS_PORT_FIELD_NUMBER: _ClassVar[int]
    PUSHCLIENT_PORT_FIELD_NUMBER: _ClassVar[int]
    AEGIS_PORT_FIELD_NUMBER: _ClassVar[int]
    RESOURCE_MANAGER_API_SERVER_GRPC_PORT_FIELD_NUMBER: _ClassVar[int]
    ELASTICSEARCH_SYSTEM_SERVICE_PORT_FIELD_NUMBER: _ClassVar[int]
    ELASTICSEARCH_SYSTEM_SERVICE_TRANSPORT_PORT_FIELD_NUMBER: _ClassVar[int]
    BIFROST_KEYCHAIN_CLIENT_LOCAL_PORT_FIELD_NUMBER: _ClassVar[int]
    BIFROST_STATS_CLIENT_LOCAL_PORT_FIELD_NUMBER: _ClassVar[int]
    BIFROST_THROTTLER_CLIENT_LOCAL_PORT_FIELD_NUMBER: _ClassVar[int]
    BIFROST_BROKER_STUB_LOCAL_PORT_FIELD_NUMBER: _ClassVar[int]
    BIFROST_BRIDGE_PIGEON_LOCAL_PORT_FIELD_NUMBER: _ClassVar[int]
    BIFROST_SNAPFS_SERVER_LOCAL_PORT_FIELD_NUMBER: _ClassVar[int]
    BIFROST_BRIDGE_SECURE_SNAPFS_LOCAL_PORT_FIELD_NUMBER: _ClassVar[int]
    COHESITY_CA_PORT_FIELD_NUMBER: _ClassVar[int]
    COHESITY_CA_GRPC_SERVER_PORT_FIELD_NUMBER: _ClassVar[int]
    COHESION_PORT_FIELD_NUMBER: _ClassVar[int]
    COHESION_GRPC_PORT_FIELD_NUMBER: _ClassVar[int]
    LINUX_AGENT_PORT_FIELD_NUMBER: _ClassVar[int]
    LINUX_AGENT_GRPC_PORT_FIELD_NUMBER: _ClassVar[int]
    BRIDGE_DESIRABLE_CHUNK_FILE_SIZE_MB_FIELD_NUMBER: _ClassVar[int]
    BRIDGE_DESIRABLE_EC_CHUNK_FILE_SIZE_MB_FIELD_NUMBER: _ClassVar[int]
    BRIDGE_DESIRABLE_EC_STRIPE_SIZE_MB_FIELD_NUMBER: _ClassVar[int]
    BRIDGE_ESTIMATED_COMPRESSION_FACTOR_FIELD_NUMBER: _ClassVar[int]
    IRIS_TENANTS_KEY_FIELD_NUMBER: _ClassVar[int]
    ATHENA_KUBERNETES_CONFIG_KEY_FIELD_NUMBER: _ClassVar[int]
    ALERTS_DATA_KEY_FIELD_NUMBER: _ClassVar[int]
    BULLETIN_BOARD_KEY_FIELD_NUMBER: _ClassVar[int]
    PG_DB_INFO_KEY_FIELD_NUMBER: _ClassVar[int]
    HELIOS_METADATA_VIEW_FIELD_NUMBER: _ClassVar[int]
    HELIOS_METADATA_DIRPATH_FIELD_NUMBER: _ClassVar[int]
    POSTGRES_DATADIR_RELATIVE_PATH_FIELD_NUMBER: _ClassVar[int]
    ALERT_POLICIES_CHANGE_NOTIFY_KEY_FIELD_NUMBER: _ClassVar[int]
    GANDALF_IRIS_METADATA_ID_KEY_FIELD_NUMBER: _ClassVar[int]
    AXON_CONFIG_KEY_FIELD_NUMBER: _ClassVar[int]
    AXON_SERVICE_ACCESS_INTERFACE_PREFIX_FIELD_NUMBER: _ClassVar[int]
    SSL_CERTIFICATE_KEY_MAGNETO_AGENT_FIELD_NUMBER: _ClassVar[int]
    BIFROST_RTUSER_USERNAME_FIELD_NUMBER: _ClassVar[int]
    HEALTHCHECK_RESULTS_FILEPATH_FIELD_NUMBER: _ClassVar[int]
    BIFROST_RTUSER_AUTHORIZED_KEYS_FILEPATH_FIELD_NUMBER: _ClassVar[int]
    SAVE_TENANT_BIFROST_RT_PUB_KEY_SCRIPT_RELATIVE_PATH_FIELD_NUMBER: _ClassVar[int]
    BIFROST_RTUSER_SSHD_FORCE_COMMAND_SCRIPT_PATH_FIELD_NUMBER: _ClassVar[int]
    AXON_MAC_OUI_FIELD_NUMBER: _ClassVar[int]
    LINUX_DEFAULT_COMMANDS_FILEPATH_FIELD_NUMBER: _ClassVar[int]
    LINUX_CUSTOM_COMMANDS_FILEPATH_FIELD_NUMBER: _ClassVar[int]
    HELIOS_CERTIFICATE_KEY_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_RESET_STATE_FILEPATH_FIELD_NUMBER: _ClassVar[int]
    CURRENT_NETWORK_CONFIG_FILEPATH_FIELD_NUMBER: _ClassVar[int]
    STAGING_NETWORK_CONFIG_FILEPATH_FIELD_NUMBER: _ClassVar[int]
    BIFROST_CONSTITUENT_ID_FILENAME_FIELD_NUMBER: _ClassVar[int]
    BIFROST_CONFIG_FILE_NAME_FIELD_NUMBER: _ClassVar[int]
    BIFROST_RT_CONFIG_FILENAME_FIELD_NUMBER: _ClassVar[int]
    TENANT_CERTIFICATE_KEY_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_LOG_KEY_FIELD_NUMBER: _ClassVar[int]
    ICEBOX_DIR_RELATIVE_PATH_FIELD_NUMBER: _ClassVar[int]
    BIFROST_LATEST_CONFIG_FILE_NAME_FIELD_NUMBER: _ClassVar[int]
    BIFROST_VLAN_CONFIG_KEY_FIELD_NUMBER: _ClassVar[int]
    BIFROST_IPAM_CONFIG_KEY_FIELD_NUMBER: _ClassVar[int]
    BIFROST_VM_CONFIG_KEY_FIELD_NUMBER: _ClassVar[int]
    SYSTEM_SERVICE_PKG_BUILD_LOCATION_FIELD_NUMBER: _ClassVar[int]
    SYSTEM_SERVICE_PKG_ATHENA_LOCATION_FIELD_NUMBER: _ClassVar[int]
    BIFROST_PKG_BUILD_LOCATION_FIELD_NUMBER: _ClassVar[int]
    BIFROST_PKG_ATHENA_LOCATION_FIELD_NUMBER: _ClassVar[int]
    SYSTEM_SERVICES_KEY_FIELD_NUMBER: _ClassVar[int]
    RIGEL_TRANSIENT_CONFIG_KEY_FIELD_NUMBER: _ClassVar[int]
    CA_TRUST_STORE_KEY_FIELD_NUMBER: _ClassVar[int]
    UTILITY_APP_INFO_KEY_FIELD_NUMBER: _ClassVar[int]
    OCSP_CACHE_KEY_FIELD_NUMBER: _ClassVar[int]
    TICKET_APPROVAL_FILE_RELATIVE_PATH_FIELD_NUMBER: _ClassVar[int]
    PACKAGES_CONFIG_KEY_FIELD_NUMBER: _ClassVar[int]
    ENCRYPTION_KEY_FIELD_NUMBER: _ClassVar[int]
    SQL_AGENT_CA_CERT_PATH_FIELD_NUMBER: _ClassVar[int]
    ALLOW_CLUSTER_DESTROY_MARKER_FILE_PATH_FIELD_NUMBER: _ClassVar[int]
    SYSTEM_SERVICE_JSON_BUILD_LOCATION_FIELD_NUMBER: _ClassVar[int]
    SYSTEM_SERVICE_JSON_NEXUS_LOCATION_FIELD_NUMBER: _ClassVar[int]
    SYSTEM_SERVICE_VEC_NEXUS_LOCATION_FIELD_NUMBER: _ClassVar[int]
    ETCD_CONFIG_KEY_FIELD_NUMBER: _ClassVar[int]
    RIGEL_CONNECTIVITY_KEY_FIELD_NUMBER: _ClassVar[int]
    NODE_BASE_OS_VERSION_HISTORY_DIRPATH_FIELD_NUMBER: _ClassVar[int]
    ETCD_CONFIG_LOCAL_PROTO_FILEPATH_FIELD_NUMBER: _ClassVar[int]
    NEXUS_HMAC_CONFIG_KEY_FIELD_NUMBER: _ClassVar[int]
    EMAIL_OTP_KEY_FIELD_NUMBER: _ClassVar[int]
    SFDC_INSTANCE_TASK_IDS_KEY_FIELD_NUMBER: _ClassVar[int]
    AUDIT_LOG_COLLECTION_KEY_FIELD_NUMBER: _ClassVar[int]
    OPENSEARCH_CONFIG_FILE_FIELD_NUMBER: _ClassVar[int]
    OPENSEARCH_SCRIPT_RELATIVE_PATH_FIELD_NUMBER: _ClassVar[int]
    OPENSEARCH_PEMCERT_FILEPATH_FIELD_NUMBER: _ClassVar[int]
    OPENSEARCH_PEMKEY_FILEPATH_FIELD_NUMBER: _ClassVar[int]
    OPENSEARCH_PEMTRUSTEDCAS_FILEPATH_FIELD_NUMBER: _ClassVar[int]
    SPIRE_SERVICE_IDENTITY_BASE_PATH_FIELD_NUMBER: _ClassVar[int]
    KUBELET_MEMORY_LIMIT_IN_BYTES_PATH_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_DISAGGREGATE_STATE_FILEPATH_FIELD_NUMBER: _ClassVar[int]
    USER_TUNINGS_KEY_FIELD_NUMBER: _ClassVar[int]
    UPGRADE_CHECK_DIR_PATH_FIELD_NUMBER: _ClassVar[int]
    SUPPORT_TOOL_BOX_PKG_PATH_FIELD_NUMBER: _ClassVar[int]
    SUPPORT_TOOL_BOX_PKG_DIR_FIELD_NUMBER: _ClassVar[int]
    S3_GRPC_PORT_FIELD_NUMBER: _ClassVar[int]
    CUSTOMER_MANAGED_BASEOS_FILE_PATH_FIELD_NUMBER: _ClassVar[int]
    DES_DECRYPT_LIB_PATH_FIELD_NUMBER: _ClassVar[int]
    TENANT_MIGRATION_KEY_FIELD_NUMBER: _ClassVar[int]
    SSH_KEY_PAIR_STORE_KEY_FIELD_NUMBER: _ClassVar[int]
    COHESITY_CA_KEY_FIELD_NUMBER: _ClassVar[int]
    COHESITY_CA_CERTIFICATES_KEY_FIELD_NUMBER: _ClassVar[int]
    YODA_ENTITY_ID_MIGRATION_STATE_KEY_FIELD_NUMBER: _ClassVar[int]
    COHESION_DIR_RELATIVE_PATH_FIELD_NUMBER: _ClassVar[int]
    USER_BOOTSTRAP_COHESITY_CA_KEY_FIELD_NUMBER: _ClassVar[int]
    CUSTOMER_CA_SIGNED_CLUSTER_CERTIFICATES_FIELD_NUMBER: _ClassVar[int]
    ROTATED_COHESITY_CA_CERTIFICATES_FIELD_NUMBER: _ClassVar[int]
    ON_PREM_RIGEL_CONFIG_KEY_FIELD_NUMBER: _ClassVar[int]
    DOWNLOADED_PATCHES_KEY_FIELD_NUMBER: _ClassVar[int]
    PATCHES_HISTORY_KEY_FIELD_NUMBER: _ClassVar[int]
    PATCH_ORCHESTRATION_STATE_KEY_FIELD_NUMBER: _ClassVar[int]
    PRECHECKS_DATA_KEY_FIELD_NUMBER: _ClassVar[int]
    HELIOS_CERTIFICATE_ENCRYPTION_KEY_FIELD_NUMBER: _ClassVar[int]
    data_dirpath: str
    node_id_filepath: str
    cluster_id_filepath: str
    software_dirpath: str
    gandalf_dirpath: str
    gandalf_constituent_id_key: str
    gandalf_metadata_id_key: str
    cluster_config_key: str
    packages_dirpath: str
    services_gflags_key: str
    ssl_certificate_key: str
    disk_mounts_parent_relative_path: str
    disk_config_name: str
    apollo_dir_relative_path: str
    chunk_repository_dir_relative_path: str
    hydra_dir_relative_path: str
    scribe_dir_relative_path: str
    yoda_dir_relative_path: str
    elasticsearch_config_file: str
    elasticsearch_script_relative_path: str
    reverse_tunnel_script_relative_path: str
    gandalf_alerts_id_key: str
    scribe_table_id_key: str
    iris_users_key: str
    cluster_create_status_key: str
    clear_old_mount_points_script_relative_path: str
    elasticsearch_kill_busy_script_relative_path: str
    yoda_slave_dir_relative_path: str
    cluster_has_new_packages_key: str
    hardware_filepath: str
    mr_metadata_id_key: str
    rhino_script_relative_path: str
    nearline_adapter_ssl_validator_relative_path: str
    cluster_bringup_status_path: str
    software_config_dirpath: str
    software_platform_config_dirpath: str
    software_bin_dirpath: str
    disk_location_filepath: str
    free_node_alert_filepath: str
    memory_limit_filepath: str
    notify_disk_change_filepath: str
    nic_port_map_filepath: str
    node_software_version_history_filepath: str
    feature_list_key: str
    admin_user_name: str
    admin_rid: int
    default_domain_name: str
    iris_relative_path: str
    private_key_file_name: str
    scheduler_key: str
    logs_dir: str
    iris_master_key: str
    librarian_dir_relative_path: str
    groot_dir_relative_path: str
    scribe_view_config_key: str
    zero_metadata_fault_tolerance_file_path: str
    luceneserver_script_relative_path: str
    db_script_relative_path: str
    reporting_schema_dir_relative_path: str
    interface_link_state_filepath: str
    eagle_agent_dirpath: str
    tricorder_data_dirpath_deprecated: str
    athena_app_downloads_dirpath: str
    network_config_filepath: str
    cached_services_gflags_file_name: str
    helios_agent_key: str
    optimus_script_relative_path: str
    gandalf_antivirus_service_id_key: str
    bifrost_dir_relative_path: str
    selinux_avc_denials_chkpoint_file_path: str
    nexus_proxy_vip_epoch_filepath: str
    athena_ephemeral_volumes_base_path: str
    ssl_validator_relative_path: str
    elrond_dir_relative_path: str
    nfsshare_mounts_parent_relative_path: str
    notify_nfs_mount_change_filepath: str
    bridge_dir_relative_path: str
    bridge_nfs_auth_kerberos_relative_path: str
    elrond_tracked_io_log_dir_relative_path: str
    elrond_binary_logger_file_prefix: str
    ntp_freq_error_chkpoint_file_path: str
    elrond_access_model_key: str
    heimdall_dir_relative_path: str
    avc_denial_error_chkpoint_file_path: str
    remote_storage_config_filepath: str
    os_util_min_port: int
    patch_nodes_script_relative_path: str
    patch_dir_relative_path: str
    patch_logs_dir: str
    imported_patches_dir: str
    available_patches_dir: str
    applied_patches_dir: str
    patch_bin_dir: str
    active_patches_dir: str
    hotfix_dir: str
    patch_configs_dir: str
    teleport_script_path: str
    etl_server_script_relative_path: str
    offline_alerts_file_relative_path: str
    iris_http_port: int
    iris_https_port: int
    smbrpc_port: int
    nfs_sunrpc_port: int
    s3_port: int
    swift_port: int
    iscsi_port: int
    ovn_nb_port: int
    ovn_sb_port: int
    ovn_nb_raft_port: int
    ovn_sb_raft_port: int
    spire_server_port: int
    spire_federation_port: int
    athena_flannel_port: int
    athena_flannel_vxlan_port: int
    athena_flannel2_vxlan_port: int
    siren_port: int
    os_util_max_port: int
    bridge_port: int
    hydra_port: int
    bridge_insecure_grpc_server_port: int
    bridge_pigeon_grpc_port: int
    vault_proxy_port: int
    bridge_proxy_port: int
    bridge_secure_grpc_server_port: int
    madrox_port: int
    bridge_secondary_http_port: int
    newscribe_port: int
    newscribe_port_last: int
    rtclient_port: int
    scribe_port: int
    magneto_port: int
    magneto_read_replica_port: int
    magneto_api_server_grpc_port: int
    storage_proxy_port: int
    smb_proxy_port: int
    smb_proxy_http_port: int
    atom_grpc_port: int
    atom_port: int
    atom_protorpc_port: int
    smb2_proxy_port: int
    smb2_proxy_http_port: int
    throttler_port: int
    nfs_proxy_port: int
    nfs_proxy_http_port: int
    alerts_port: int
    keychain_port: int
    gandalf_port: int
    gandalf_grpc_port: int
    pigeon_port: int
    bridge_pigeon_tls_port: int
    pigeon_alternate_port: int
    nexus_pprof_port: int
    nexus_port: int
    nexus_proxy_port: int
    nexus_secure_port: int
    tricorder_port_deprecated: int
    re_ip_port: int
    eagle_agent_port: int
    re_ip_socket_port: int
    mcmetl_server_port: int
    licensing_port: int
    olympus_server_port: int
    iris_proxy_port: int
    apollo_port: int
    apollo_grpc_port: int
    compass_port: int
    stats_port: int
    pulse_grpc_port: int
    gaia_port: int
    gaia_grpc_port: int
    athena_kube_scheduler_secure_port: int
    athena_kube_controller_secure_port: int
    athena_kube_proxy_healthz_port: int
    athena_kube_proxy_metrics_port: int
    athena_kubelet_healthz_port: int
    athena_kube_scheduler_healthz_port: int
    nexus_envoy_admin_port: int
    nexus_service_identity_outbound_handler: int
    nexus_service_identity_inbound_handler: int
    statscollector_port: int
    athena_port: int
    athena_docker_registry_port: int
    optimus_port: int
    athena_proxy_docker_registry_port: int
    athena_proxy_api_server_port: int
    athena_proxy_config_port: int
    athena_etcd_client_port: int
    athena_etcd_peer_port: int
    athena_kubernetes_apiserver_http_port: int
    athena_kubelet_cadvisor_port: int
    athena_kubelet_https_port: int
    athena_coredns_port: int
    athena_coredns_health_port: int
    athena_proxy_port: int
    athena_proxy_internal_port: int
    athena_kubernetes_apiserver_https_port: int
    athena_watchdog_port: int
    etl_server_grpc_port: int
    athena_sys_srvc_docker_registry_port: int
    elasticsearch_min_port: int
    elasticsearch_max_port: int
    elasticsearch_node_discovery_port: int
    helios_onprem_docker_registry_port: int
    helios_onprem_etcd_client_port: int
    helios_onprem_etcd_peer_port: int
    helios_onprem_iris_http_port: int
    helios_onprem_iris_https_port: int
    rhino_port: int
    yoda_port: int
    librarian_port: int
    luceneserver_port: int
    elrond_port: int
    heimdall_port: int
    yoda_agent_port: int
    yoda_agent_http_port: int
    opensearch_min_port: int
    opensearch_max_port: int
    groot_port: int
    report_database_port: int
    report_server_port: int
    node_exporter_port: int
    broker_services_port: int
    broker_bifrost_port: int
    broker_http_port: int
    socks_server_broker_listen_port_range: str
    rigel_local_bridge_ports_range: str
    bifrost_http_port: int
    socks_grpc_proxy_port: int
    socks_grpc_agent_port: int
    icebox_port: int
    patch_exec_port: int
    testing_min_port: int
    testing_max_port: int
    ephemeral_min_port: int
    ephemeral_max_port: int
    athena_min_dynamic_node_port: int
    athena_max_dynamic_node_port: int
    athena_min_static_node_port: int
    athena_max_static_node_port: int
    elixir_http_port: int
    vulscanner_port: int
    bootstrapper_port: int
    kube_dashboard_port: int
    testservice_port: int
    dlp_port: int
    eventing_service_port: int
    prometheus_port: int
    kafka_port: int
    agentinstall_http_port: int
    imanis_grpc_port: int
    imanis_resource_manager_port: int
    imanis_node_manager_port: int
    workqueue_server_grpc_port: int
    workqueue_server_http_port: int
    metadata_service_grpc_port: int
    argus_app_port: int
    magnus_api_port: int
    magnus_server_grpc_server_port: int
    magnus_server_http_server_port: int
    magnus_actor_http_server_port: int
    ods_app_port: int
    sheltered_harbor_control_port: int
    sheltered_harbor_data_preparer_port: int
    sheltered_harbor_restorer_port: int
    sftp_app_port: int
    sftp_rest_app_port: int
    routing_ospf_port: int
    routing_bgp_port: int
    routing_rip_port: int
    janus_port: int
    pushclient_port: int
    aegis_port: int
    resource_manager_api_server_grpc_port: int
    elasticsearch_system_service_port: int
    elasticsearch_system_service_transport_port: int
    bifrost_keychain_client_local_port: int
    bifrost_stats_client_local_port: int
    bifrost_throttler_client_local_port: int
    bifrost_broker_stub_local_port: int
    bifrost_bridge_pigeon_local_port: int
    bifrost_snapfs_server_local_port: int
    bifrost_bridge_secure_snapfs_local_port: int
    cohesity_ca_port: int
    cohesity_ca_grpc_server_port: int
    cohesion_port: int
    cohesion_grpc_port: int
    linux_agent_port: int
    linux_agent_grpc_port: int
    bridge_desirable_chunk_file_size_MB: int
    bridge_desirable_ec_chunk_file_size_MB: int
    bridge_desirable_ec_stripe_size_MB: int
    bridge_estimated_compression_factor: int
    iris_tenants_key: str
    athena_kubernetes_config_key: str
    alerts_data_key: str
    bulletin_board_key: str
    pg_db_info_key: str
    helios_metadata_view: str
    helios_metadata_dirpath: str
    postgres_datadir_relative_path: str
    alert_policies_change_notify_key: str
    gandalf_iris_metadata_id_key: str
    axon_config_key: str
    axon_service_access_interface_prefix: str
    ssl_certificate_key_magneto_agent: str
    bifrost_rtuser_username: str
    healthcheck_results_filepath: str
    bifrost_rtuser_authorized_keys_filepath: str
    save_tenant_bifrost_rt_pub_key_script_relative_path: str
    bifrost_rtuser_sshd_force_command_script_path: str
    axon_mac_oui: str
    linux_default_commands_filepath: str
    linux_custom_commands_filepath: str
    helios_certificate_key: str
    cluster_reset_state_filepath: str
    current_network_config_filepath: str
    staging_network_config_filepath: str
    bifrost_constituent_id_filename: str
    bifrost_config_file_name: str
    bifrost_rt_config_filename: str
    tenant_certificate_key: str
    cluster_log_key: str
    icebox_dir_relative_path: str
    bifrost_latest_config_file_name: str
    bifrost_vlan_config_key: str
    bifrost_ipam_config_key: str
    bifrost_vm_config_key: str
    system_service_pkg_build_location: str
    system_service_pkg_athena_location: str
    bifrost_pkg_build_location: str
    bifrost_pkg_athena_location: str
    system_services_key: str
    rigel_transient_config_key: str
    ca_trust_store_key: str
    utility_app_info_key: str
    ocsp_cache_key: str
    ticket_approval_file_relative_path: str
    packages_config_key: str
    encryption_key: str
    sql_agent_ca_cert_path: str
    allow_cluster_destroy_marker_file_path: str
    system_service_json_build_location: str
    system_service_json_nexus_location: str
    system_service_vec_nexus_location: str
    etcd_config_key: str
    rigel_connectivity_key: str
    node_base_os_version_history_dirpath: str
    etcd_config_local_proto_filepath: str
    nexus_hmac_config_key: str
    email_otp_key: str
    sfdc_instance_task_ids_key: str
    audit_log_collection_key: str
    opensearch_config_file: str
    opensearch_script_relative_path: str
    opensearch_pemcert_filepath: str
    opensearch_pemkey_filepath: str
    opensearch_pemtrustedcas_filepath: str
    spire_service_identity_base_path: str
    kubelet_memory_limit_in_bytes_path: str
    cluster_disaggregate_state_filepath: str
    user_tunings_key: str
    upgrade_check_dir_path: str
    support_tool_box_pkg_path: str
    support_tool_box_pkg_dir: str
    s3_grpc_port: int
    customer_managed_baseos_file_path: str
    des_decrypt_lib_path: str
    tenant_migration_key: str
    ssh_key_pair_store_key: str
    cohesity_ca_key: str
    cohesity_ca_certificates_key: str
    yoda_entity_id_migration_state_key: str
    cohesion_dir_relative_path: str
    user_bootstrap_cohesity_ca_key: str
    customer_ca_signed_cluster_certificates: str
    rotated_cohesity_ca_certificates: str
    on_prem_rigel_config_key: str
    downloaded_patches_key: str
    patches_history_key: str
    patch_orchestration_state_key: str
    prechecks_data_key: str
    helios_certificate_encryption_key: str
    def __init__(self, data_dirpath: _Optional[str] = ..., node_id_filepath: _Optional[str] = ..., cluster_id_filepath: _Optional[str] = ..., software_dirpath: _Optional[str] = ..., gandalf_dirpath: _Optional[str] = ..., gandalf_constituent_id_key: _Optional[str] = ..., gandalf_metadata_id_key: _Optional[str] = ..., cluster_config_key: _Optional[str] = ..., packages_dirpath: _Optional[str] = ..., services_gflags_key: _Optional[str] = ..., ssl_certificate_key: _Optional[str] = ..., disk_mounts_parent_relative_path: _Optional[str] = ..., disk_config_name: _Optional[str] = ..., apollo_dir_relative_path: _Optional[str] = ..., chunk_repository_dir_relative_path: _Optional[str] = ..., hydra_dir_relative_path: _Optional[str] = ..., scribe_dir_relative_path: _Optional[str] = ..., yoda_dir_relative_path: _Optional[str] = ..., elasticsearch_config_file: _Optional[str] = ..., elasticsearch_script_relative_path: _Optional[str] = ..., reverse_tunnel_script_relative_path: _Optional[str] = ..., gandalf_alerts_id_key: _Optional[str] = ..., scribe_table_id_key: _Optional[str] = ..., iris_users_key: _Optional[str] = ..., cluster_create_status_key: _Optional[str] = ..., clear_old_mount_points_script_relative_path: _Optional[str] = ..., elasticsearch_kill_busy_script_relative_path: _Optional[str] = ..., yoda_slave_dir_relative_path: _Optional[str] = ..., cluster_has_new_packages_key: _Optional[str] = ..., hardware_filepath: _Optional[str] = ..., mr_metadata_id_key: _Optional[str] = ..., rhino_script_relative_path: _Optional[str] = ..., nearline_adapter_ssl_validator_relative_path: _Optional[str] = ..., cluster_bringup_status_path: _Optional[str] = ..., software_config_dirpath: _Optional[str] = ..., software_platform_config_dirpath: _Optional[str] = ..., software_bin_dirpath: _Optional[str] = ..., disk_location_filepath: _Optional[str] = ..., free_node_alert_filepath: _Optional[str] = ..., memory_limit_filepath: _Optional[str] = ..., notify_disk_change_filepath: _Optional[str] = ..., nic_port_map_filepath: _Optional[str] = ..., node_software_version_history_filepath: _Optional[str] = ..., feature_list_key: _Optional[str] = ..., admin_user_name: _Optional[str] = ..., admin_rid: _Optional[int] = ..., default_domain_name: _Optional[str] = ..., iris_relative_path: _Optional[str] = ..., private_key_file_name: _Optional[str] = ..., scheduler_key: _Optional[str] = ..., logs_dir: _Optional[str] = ..., iris_master_key: _Optional[str] = ..., librarian_dir_relative_path: _Optional[str] = ..., groot_dir_relative_path: _Optional[str] = ..., scribe_view_config_key: _Optional[str] = ..., zero_metadata_fault_tolerance_file_path: _Optional[str] = ..., luceneserver_script_relative_path: _Optional[str] = ..., db_script_relative_path: _Optional[str] = ..., reporting_schema_dir_relative_path: _Optional[str] = ..., interface_link_state_filepath: _Optional[str] = ..., eagle_agent_dirpath: _Optional[str] = ..., tricorder_data_dirpath_deprecated: _Optional[str] = ..., athena_app_downloads_dirpath: _Optional[str] = ..., network_config_filepath: _Optional[str] = ..., cached_services_gflags_file_name: _Optional[str] = ..., helios_agent_key: _Optional[str] = ..., optimus_script_relative_path: _Optional[str] = ..., gandalf_antivirus_service_id_key: _Optional[str] = ..., bifrost_dir_relative_path: _Optional[str] = ..., selinux_avc_denials_chkpoint_file_path: _Optional[str] = ..., nexus_proxy_vip_epoch_filepath: _Optional[str] = ..., athena_ephemeral_volumes_base_path: _Optional[str] = ..., ssl_validator_relative_path: _Optional[str] = ..., elrond_dir_relative_path: _Optional[str] = ..., nfsshare_mounts_parent_relative_path: _Optional[str] = ..., notify_nfs_mount_change_filepath: _Optional[str] = ..., bridge_dir_relative_path: _Optional[str] = ..., bridge_nfs_auth_kerberos_relative_path: _Optional[str] = ..., elrond_tracked_io_log_dir_relative_path: _Optional[str] = ..., elrond_binary_logger_file_prefix: _Optional[str] = ..., ntp_freq_error_chkpoint_file_path: _Optional[str] = ..., elrond_access_model_key: _Optional[str] = ..., heimdall_dir_relative_path: _Optional[str] = ..., avc_denial_error_chkpoint_file_path: _Optional[str] = ..., remote_storage_config_filepath: _Optional[str] = ..., os_util_min_port: _Optional[int] = ..., patch_nodes_script_relative_path: _Optional[str] = ..., patch_dir_relative_path: _Optional[str] = ..., patch_logs_dir: _Optional[str] = ..., imported_patches_dir: _Optional[str] = ..., available_patches_dir: _Optional[str] = ..., applied_patches_dir: _Optional[str] = ..., patch_bin_dir: _Optional[str] = ..., active_patches_dir: _Optional[str] = ..., hotfix_dir: _Optional[str] = ..., patch_configs_dir: _Optional[str] = ..., teleport_script_path: _Optional[str] = ..., etl_server_script_relative_path: _Optional[str] = ..., offline_alerts_file_relative_path: _Optional[str] = ..., iris_http_port: _Optional[int] = ..., iris_https_port: _Optional[int] = ..., smbrpc_port: _Optional[int] = ..., nfs_sunrpc_port: _Optional[int] = ..., s3_port: _Optional[int] = ..., swift_port: _Optional[int] = ..., iscsi_port: _Optional[int] = ..., ovn_nb_port: _Optional[int] = ..., ovn_sb_port: _Optional[int] = ..., ovn_nb_raft_port: _Optional[int] = ..., ovn_sb_raft_port: _Optional[int] = ..., spire_server_port: _Optional[int] = ..., spire_federation_port: _Optional[int] = ..., athena_flannel_port: _Optional[int] = ..., athena_flannel_vxlan_port: _Optional[int] = ..., athena_flannel2_vxlan_port: _Optional[int] = ..., siren_port: _Optional[int] = ..., os_util_max_port: _Optional[int] = ..., bridge_port: _Optional[int] = ..., hydra_port: _Optional[int] = ..., bridge_insecure_grpc_server_port: _Optional[int] = ..., bridge_pigeon_grpc_port: _Optional[int] = ..., vault_proxy_port: _Optional[int] = ..., bridge_proxy_port: _Optional[int] = ..., bridge_secure_grpc_server_port: _Optional[int] = ..., madrox_port: _Optional[int] = ..., bridge_secondary_http_port: _Optional[int] = ..., newscribe_port: _Optional[int] = ..., newscribe_port_last: _Optional[int] = ..., rtclient_port: _Optional[int] = ..., scribe_port: _Optional[int] = ..., magneto_port: _Optional[int] = ..., magneto_read_replica_port: _Optional[int] = ..., magneto_api_server_grpc_port: _Optional[int] = ..., storage_proxy_port: _Optional[int] = ..., smb_proxy_port: _Optional[int] = ..., smb_proxy_http_port: _Optional[int] = ..., atom_grpc_port: _Optional[int] = ..., atom_port: _Optional[int] = ..., atom_protorpc_port: _Optional[int] = ..., smb2_proxy_port: _Optional[int] = ..., smb2_proxy_http_port: _Optional[int] = ..., throttler_port: _Optional[int] = ..., nfs_proxy_port: _Optional[int] = ..., nfs_proxy_http_port: _Optional[int] = ..., alerts_port: _Optional[int] = ..., keychain_port: _Optional[int] = ..., gandalf_port: _Optional[int] = ..., gandalf_grpc_port: _Optional[int] = ..., pigeon_port: _Optional[int] = ..., bridge_pigeon_tls_port: _Optional[int] = ..., pigeon_alternate_port: _Optional[int] = ..., nexus_pprof_port: _Optional[int] = ..., nexus_port: _Optional[int] = ..., nexus_proxy_port: _Optional[int] = ..., nexus_secure_port: _Optional[int] = ..., tricorder_port_deprecated: _Optional[int] = ..., re_ip_port: _Optional[int] = ..., eagle_agent_port: _Optional[int] = ..., re_ip_socket_port: _Optional[int] = ..., mcmetl_server_port: _Optional[int] = ..., licensing_port: _Optional[int] = ..., olympus_server_port: _Optional[int] = ..., iris_proxy_port: _Optional[int] = ..., apollo_port: _Optional[int] = ..., apollo_grpc_port: _Optional[int] = ..., compass_port: _Optional[int] = ..., stats_port: _Optional[int] = ..., pulse_grpc_port: _Optional[int] = ..., gaia_port: _Optional[int] = ..., gaia_grpc_port: _Optional[int] = ..., athena_kube_scheduler_secure_port: _Optional[int] = ..., athena_kube_controller_secure_port: _Optional[int] = ..., athena_kube_proxy_healthz_port: _Optional[int] = ..., athena_kube_proxy_metrics_port: _Optional[int] = ..., athena_kubelet_healthz_port: _Optional[int] = ..., athena_kube_scheduler_healthz_port: _Optional[int] = ..., nexus_envoy_admin_port: _Optional[int] = ..., nexus_service_identity_outbound_handler: _Optional[int] = ..., nexus_service_identity_inbound_handler: _Optional[int] = ..., statscollector_port: _Optional[int] = ..., athena_port: _Optional[int] = ..., athena_docker_registry_port: _Optional[int] = ..., optimus_port: _Optional[int] = ..., athena_proxy_docker_registry_port: _Optional[int] = ..., athena_proxy_api_server_port: _Optional[int] = ..., athena_proxy_config_port: _Optional[int] = ..., athena_etcd_client_port: _Optional[int] = ..., athena_etcd_peer_port: _Optional[int] = ..., athena_kubernetes_apiserver_http_port: _Optional[int] = ..., athena_kubelet_cadvisor_port: _Optional[int] = ..., athena_kubelet_https_port: _Optional[int] = ..., athena_coredns_port: _Optional[int] = ..., athena_coredns_health_port: _Optional[int] = ..., athena_proxy_port: _Optional[int] = ..., athena_proxy_internal_port: _Optional[int] = ..., athena_kubernetes_apiserver_https_port: _Optional[int] = ..., athena_watchdog_port: _Optional[int] = ..., etl_server_grpc_port: _Optional[int] = ..., athena_sys_srvc_docker_registry_port: _Optional[int] = ..., elasticsearch_min_port: _Optional[int] = ..., elasticsearch_max_port: _Optional[int] = ..., elasticsearch_node_discovery_port: _Optional[int] = ..., helios_onprem_docker_registry_port: _Optional[int] = ..., helios_onprem_etcd_client_port: _Optional[int] = ..., helios_onprem_etcd_peer_port: _Optional[int] = ..., helios_onprem_iris_http_port: _Optional[int] = ..., helios_onprem_iris_https_port: _Optional[int] = ..., rhino_port: _Optional[int] = ..., yoda_port: _Optional[int] = ..., librarian_port: _Optional[int] = ..., luceneserver_port: _Optional[int] = ..., elrond_port: _Optional[int] = ..., heimdall_port: _Optional[int] = ..., yoda_agent_port: _Optional[int] = ..., yoda_agent_http_port: _Optional[int] = ..., opensearch_min_port: _Optional[int] = ..., opensearch_max_port: _Optional[int] = ..., groot_port: _Optional[int] = ..., report_database_port: _Optional[int] = ..., report_server_port: _Optional[int] = ..., node_exporter_port: _Optional[int] = ..., broker_services_port: _Optional[int] = ..., broker_bifrost_port: _Optional[int] = ..., broker_http_port: _Optional[int] = ..., socks_server_broker_listen_port_range: _Optional[str] = ..., rigel_local_bridge_ports_range: _Optional[str] = ..., bifrost_http_port: _Optional[int] = ..., socks_grpc_proxy_port: _Optional[int] = ..., socks_grpc_agent_port: _Optional[int] = ..., icebox_port: _Optional[int] = ..., patch_exec_port: _Optional[int] = ..., testing_min_port: _Optional[int] = ..., testing_max_port: _Optional[int] = ..., ephemeral_min_port: _Optional[int] = ..., ephemeral_max_port: _Optional[int] = ..., athena_min_dynamic_node_port: _Optional[int] = ..., athena_max_dynamic_node_port: _Optional[int] = ..., athena_min_static_node_port: _Optional[int] = ..., athena_max_static_node_port: _Optional[int] = ..., elixir_http_port: _Optional[int] = ..., vulscanner_port: _Optional[int] = ..., bootstrapper_port: _Optional[int] = ..., kube_dashboard_port: _Optional[int] = ..., testservice_port: _Optional[int] = ..., dlp_port: _Optional[int] = ..., eventing_service_port: _Optional[int] = ..., prometheus_port: _Optional[int] = ..., kafka_port: _Optional[int] = ..., agentinstall_http_port: _Optional[int] = ..., imanis_grpc_port: _Optional[int] = ..., imanis_resource_manager_port: _Optional[int] = ..., imanis_node_manager_port: _Optional[int] = ..., workqueue_server_grpc_port: _Optional[int] = ..., workqueue_server_http_port: _Optional[int] = ..., metadata_service_grpc_port: _Optional[int] = ..., argus_app_port: _Optional[int] = ..., magnus_api_port: _Optional[int] = ..., magnus_server_grpc_server_port: _Optional[int] = ..., magnus_server_http_server_port: _Optional[int] = ..., magnus_actor_http_server_port: _Optional[int] = ..., ods_app_port: _Optional[int] = ..., sheltered_harbor_control_port: _Optional[int] = ..., sheltered_harbor_data_preparer_port: _Optional[int] = ..., sheltered_harbor_restorer_port: _Optional[int] = ..., sftp_app_port: _Optional[int] = ..., sftp_rest_app_port: _Optional[int] = ..., routing_ospf_port: _Optional[int] = ..., routing_bgp_port: _Optional[int] = ..., routing_rip_port: _Optional[int] = ..., janus_port: _Optional[int] = ..., pushclient_port: _Optional[int] = ..., aegis_port: _Optional[int] = ..., resource_manager_api_server_grpc_port: _Optional[int] = ..., elasticsearch_system_service_port: _Optional[int] = ..., elasticsearch_system_service_transport_port: _Optional[int] = ..., bifrost_keychain_client_local_port: _Optional[int] = ..., bifrost_stats_client_local_port: _Optional[int] = ..., bifrost_throttler_client_local_port: _Optional[int] = ..., bifrost_broker_stub_local_port: _Optional[int] = ..., bifrost_bridge_pigeon_local_port: _Optional[int] = ..., bifrost_snapfs_server_local_port: _Optional[int] = ..., bifrost_bridge_secure_snapfs_local_port: _Optional[int] = ..., cohesity_ca_port: _Optional[int] = ..., cohesity_ca_grpc_server_port: _Optional[int] = ..., cohesion_port: _Optional[int] = ..., cohesion_grpc_port: _Optional[int] = ..., linux_agent_port: _Optional[int] = ..., linux_agent_grpc_port: _Optional[int] = ..., bridge_desirable_chunk_file_size_MB: _Optional[int] = ..., bridge_desirable_ec_chunk_file_size_MB: _Optional[int] = ..., bridge_desirable_ec_stripe_size_MB: _Optional[int] = ..., bridge_estimated_compression_factor: _Optional[int] = ..., iris_tenants_key: _Optional[str] = ..., athena_kubernetes_config_key: _Optional[str] = ..., alerts_data_key: _Optional[str] = ..., bulletin_board_key: _Optional[str] = ..., pg_db_info_key: _Optional[str] = ..., helios_metadata_view: _Optional[str] = ..., helios_metadata_dirpath: _Optional[str] = ..., postgres_datadir_relative_path: _Optional[str] = ..., alert_policies_change_notify_key: _Optional[str] = ..., gandalf_iris_metadata_id_key: _Optional[str] = ..., axon_config_key: _Optional[str] = ..., axon_service_access_interface_prefix: _Optional[str] = ..., ssl_certificate_key_magneto_agent: _Optional[str] = ..., bifrost_rtuser_username: _Optional[str] = ..., healthcheck_results_filepath: _Optional[str] = ..., bifrost_rtuser_authorized_keys_filepath: _Optional[str] = ..., save_tenant_bifrost_rt_pub_key_script_relative_path: _Optional[str] = ..., bifrost_rtuser_sshd_force_command_script_path: _Optional[str] = ..., axon_mac_oui: _Optional[str] = ..., linux_default_commands_filepath: _Optional[str] = ..., linux_custom_commands_filepath: _Optional[str] = ..., helios_certificate_key: _Optional[str] = ..., cluster_reset_state_filepath: _Optional[str] = ..., current_network_config_filepath: _Optional[str] = ..., staging_network_config_filepath: _Optional[str] = ..., bifrost_constituent_id_filename: _Optional[str] = ..., bifrost_config_file_name: _Optional[str] = ..., bifrost_rt_config_filename: _Optional[str] = ..., tenant_certificate_key: _Optional[str] = ..., cluster_log_key: _Optional[str] = ..., icebox_dir_relative_path: _Optional[str] = ..., bifrost_latest_config_file_name: _Optional[str] = ..., bifrost_vlan_config_key: _Optional[str] = ..., bifrost_ipam_config_key: _Optional[str] = ..., bifrost_vm_config_key: _Optional[str] = ..., system_service_pkg_build_location: _Optional[str] = ..., system_service_pkg_athena_location: _Optional[str] = ..., bifrost_pkg_build_location: _Optional[str] = ..., bifrost_pkg_athena_location: _Optional[str] = ..., system_services_key: _Optional[str] = ..., rigel_transient_config_key: _Optional[str] = ..., ca_trust_store_key: _Optional[str] = ..., utility_app_info_key: _Optional[str] = ..., ocsp_cache_key: _Optional[str] = ..., ticket_approval_file_relative_path: _Optional[str] = ..., packages_config_key: _Optional[str] = ..., encryption_key: _Optional[str] = ..., sql_agent_ca_cert_path: _Optional[str] = ..., allow_cluster_destroy_marker_file_path: _Optional[str] = ..., system_service_json_build_location: _Optional[str] = ..., system_service_json_nexus_location: _Optional[str] = ..., system_service_vec_nexus_location: _Optional[str] = ..., etcd_config_key: _Optional[str] = ..., rigel_connectivity_key: _Optional[str] = ..., node_base_os_version_history_dirpath: _Optional[str] = ..., etcd_config_local_proto_filepath: _Optional[str] = ..., nexus_hmac_config_key: _Optional[str] = ..., email_otp_key: _Optional[str] = ..., sfdc_instance_task_ids_key: _Optional[str] = ..., audit_log_collection_key: _Optional[str] = ..., opensearch_config_file: _Optional[str] = ..., opensearch_script_relative_path: _Optional[str] = ..., opensearch_pemcert_filepath: _Optional[str] = ..., opensearch_pemkey_filepath: _Optional[str] = ..., opensearch_pemtrustedcas_filepath: _Optional[str] = ..., spire_service_identity_base_path: _Optional[str] = ..., kubelet_memory_limit_in_bytes_path: _Optional[str] = ..., cluster_disaggregate_state_filepath: _Optional[str] = ..., user_tunings_key: _Optional[str] = ..., upgrade_check_dir_path: _Optional[str] = ..., support_tool_box_pkg_path: _Optional[str] = ..., support_tool_box_pkg_dir: _Optional[str] = ..., s3_grpc_port: _Optional[int] = ..., customer_managed_baseos_file_path: _Optional[str] = ..., des_decrypt_lib_path: _Optional[str] = ..., tenant_migration_key: _Optional[str] = ..., ssh_key_pair_store_key: _Optional[str] = ..., cohesity_ca_key: _Optional[str] = ..., cohesity_ca_certificates_key: _Optional[str] = ..., yoda_entity_id_migration_state_key: _Optional[str] = ..., cohesion_dir_relative_path: _Optional[str] = ..., user_bootstrap_cohesity_ca_key: _Optional[str] = ..., customer_ca_signed_cluster_certificates: _Optional[str] = ..., rotated_cohesity_ca_certificates: _Optional[str] = ..., on_prem_rigel_config_key: _Optional[str] = ..., downloaded_patches_key: _Optional[str] = ..., patches_history_key: _Optional[str] = ..., patch_orchestration_state_key: _Optional[str] = ..., prechecks_data_key: _Optional[str] = ..., helios_certificate_encryption_key: _Optional[str] = ...) -> None: ...
