# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: experimental/smurugesan/protobuf-3.6.0/java/core/src/test/proto/com/google/protobuf/map_initialization_order_test.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nwexperimental/smurugesan/protobuf-3.6.0/java/core/src/test/proto/com/google/protobuf/map_initialization_order_test.proto\x12\x08map_test\"{\n\x08Message1\x12\x33\n\tmap_field\x18\x01 \x03(\x0b\x32 .map_test.Message1.MapFieldEntry\x1a/\n\rMapFieldEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x08:\x02\x38\x01*\t\x08\xe8\x07\x10\x80\x80\x80\x80\x02\"\x10\n\x0eRedactAllTypes:D\n\x13recursive_extension\x12\x12.map_test.Message1\x18\xe9\x07 \x01(\x0b\x32\x12.map_test.Message1B(\n\x08map_testB\x1aMapInitializationOrderTestP\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'experimental.smurugesan.protobuf_3.6.0.java.core.src.test.proto.com.google.protobuf.map_initialization_order_test_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\010map_testB\032MapInitializationOrderTestP\001'
  _globals['_MESSAGE1_MAPFIELDENTRY']._loaded_options = None
  _globals['_MESSAGE1_MAPFIELDENTRY']._serialized_options = b'8\001'
  _globals['_MESSAGE1']._serialized_start=133
  _globals['_MESSAGE1']._serialized_end=256
  _globals['_MESSAGE1_MAPFIELDENTRY']._serialized_start=198
  _globals['_MESSAGE1_MAPFIELDENTRY']._serialized_end=245
  _globals['_REDACTALLTYPES']._serialized_start=258
  _globals['_REDACTALLTYPES']._serialized_end=274
# @@protoc_insertion_point(module_scope)
