# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: experimental/smurugesan/protobuf-3.6.0/java/core/src/test/proto/com/google/protobuf/test_check_utf8_size.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nnexperimental/smurugesan/protobuf-3.6.0/java/core/src/test/proto/com/google/protobuf/test_check_utf8_size.proto\x12\x1bproto2_test_check_utf8_size\":\n\x11StringWrapperSize\x12\x0b\n\x03req\x18\x01 \x02(\t\x12\x0b\n\x03opt\x18\x02 \x01(\t\x12\x0b\n\x03rep\x18\x03 \x03(\t\"9\n\x10\x42ytesWrapperSize\x12\x0b\n\x03req\x18\x01 \x02(\x0c\x12\x0b\n\x03opt\x18\x02 \x01(\x0c\x12\x0b\n\x03rep\x18\x03 \x03(\x0c\x42\x18\x42\x11TestCheckUtf8SizeH\x02\xd8\x01\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'experimental.smurugesan.protobuf_3.6.0.java.core.src.test.proto.com.google.protobuf.test_check_utf8_size_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\021TestCheckUtf8SizeH\002\330\001\001'
  _globals['_STRINGWRAPPERSIZE']._serialized_start=143
  _globals['_STRINGWRAPPERSIZE']._serialized_end=201
  _globals['_BYTESWRAPPERSIZE']._serialized_start=203
  _globals['_BYTESWRAPPERSIZE']._serialized_end=260
# @@protoc_insertion_point(module_scope)
