# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: athena/apps/autoscaler/base/credentials.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-athena/apps/autoscaler/base/credentials.proto\x12\x04\x62\x61se\"\x89\x02\n\x0eGcpCredentials\x12\x12\n\nproject_id\x18\x01 \x01(\t\x12\x1c\n\x14\x63lient_email_address\x18\x02 \x01(\t\x12$\n\x1c\x65ncrypted_client_private_key\x18\x03 \x01(\x0c\x12\x0c\n\x04type\x18\x04 \x01(\t\x12\x16\n\x0eprivate_key_id\x18\x05 \x01(\t\x12\x11\n\tclient_id\x18\x06 \x01(\t\x12\x10\n\x08\x61uth_uri\x18\x07 \x01(\t\x12\x11\n\ttoken_uri\x18\x08 \x01(\t\x12#\n\x1b\x61uth_provider_x509_cert_url\x18\t \x01(\t\x12\x1c\n\x14\x63lient_x509_cert_url\x18\n \x01(\t\"<\n\x0b\x43redentials\x12-\n\x0fgcp_credentials\x18\x01 \x01(\x0b\x32\x14.base.GcpCredentialsB\x1eZ\x1c\x63ohesity/autoscaler_app/base')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'athena.apps.autoscaler.base.credentials_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\034cohesity/autoscaler_app/base'
  _globals['_GCPCREDENTIALS']._serialized_start=56
  _globals['_GCPCREDENTIALS']._serialized_end=321
  _globals['_CREDENTIALS']._serialized_start=323
  _globals['_CREDENTIALS']._serialized_end=383
# @@protoc_insertion_point(module_scope)
