# => restore vms from VMware Backup based on timestamp provided or recent
# => job run is used for the operation.
---
- hosts: localhost
  gather_facts: no
  become: false
  collections:
    - cohesity.dataprotect
  tasks:
    - name: Finalise migration of VMs
      cohesity_migration_status:
        cluster: "{{ cohesity_server }}"
        username: "{{ cohesity_username }}"
        password: "{{ cohesity_password }}"
        validate_certs: "{{ cohesity_validate_certs }}"
        #task_name: "Migrate_VM_Jan_11_2023_06_31_PM"
        task_id: 1755745655068243:1672666992780:6198
