# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scribe/newscribe/metrics/scribe_stats_config.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2scribe/newscribe/metrics/scribe_stats_config.proto\x12\x17\x63ohesity.scribe.metrics\"\x8b\x08\n\x16ScribeStatsConfigProto\x12#\n\x11time_to_live_secs\x18\x01 \x01(\x03:\x08\x31\x35\x37\x36\x38\x30\x30\x30\x12J\n\'scribe_table_instance_stats_schema_name\x18\x02 \x01(\t:\x19kScribeTableInstanceStats\x12\x35\n*scribe_table_instance_stats_schema_version\x18\x03 \x01(\x03:\x01\x31\x12/\n\x16table_instance_id_attr\x18\x04 \x01(\t:\x0fTableInstanceId\x12H\n&scribe_table_cluster_stats_schema_name\x18\x05 \x01(\t:\x18kScribeTableClusterStats\x12\x34\n)scribe_table_cluster_stats_schema_version\x18\x06 \x01(\x03:\x01\x31\x12\x1e\n\rtable_id_attr\x18\x07 \x01(\t:\x07TableId\x12Y\n/scribe_server_instance_client_stats_schema_name\x18\x08 \x01(\t: kScribeServerInstanceClientStats\x12=\n2scribe_server_instance_client_stats_schema_version\x18\t \x01(\x03:\x01\x31\x12Y\n3scribe_server_instance_scribe_server_client_id_attr\x18\n \x01(\t:\x1cScribeServerInstanceClientId\x12H\n&scribe_server_client_stats_schema_name\x18\x0b \x01(\t:\x18kScribeServerClientStats\x12\x34\n)scribe_server_client_stats_schema_version\x18\x0c \x01(\x03:\x01\x31\x12:\n\x1cscribe_server_client_id_attr\x18\r \x01(\t:\x14ScribeServerClientId\x12H\n)scribe_server_qos_queue_stats_schema_name\x18\x0e \x01(\t:\x15kScribeServerQoSStats\x12\x37\n,scribe_server_qos_queue_stats_schema_version\x18\x0f \x01(\x03:\x01\x31\x12\x44\n\x1fscribe_server_qos_queue_id_attr\x18\x10 \x01(\t:\x1bScribeServerPrincipalNodeId')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scribe.newscribe.metrics.scribe_stats_config_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCRIBESTATSCONFIGPROTO']._serialized_start=80
  _globals['_SCRIBESTATSCONFIGPROTO']._serialized_end=1115
# @@protoc_insertion_point(module_scope)
