from util.message_catalog import message_catalog_pb2 as _message_catalog_pb2
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from typing import ClassVar as _ClassVar, Mapping as _Mapping, Optional as _Optional, Union as _Union

DESCRIPTOR: _descriptor.FileDescriptor

class ErrorProto(_message.Message):
    __slots__ = ("type", "error_detail", "detailed_error_msg")
    class Type(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
        __slots__ = ()
        kNoError: _ClassVar[ErrorProto.Type]
        kTransportError: _ClassVar[ErrorProto.Type]
        kTimeout: _ClassVar[ErrorProto.Type]
        kStale: _ClassVar[ErrorProto.Type]
        kNonExistent: _ClassVar[ErrorProto.Type]
        kRetry: _ClassVar[ErrorProto.Type]
        kNotLeader: _ClassVar[ErrorProto.Type]
        kBusy: _ClassVar[ErrorProto.Type]
        kCASError: _ClassVar[ErrorProto.Type]
        kAlreadyExists: _ClassVar[ErrorProto.Type]
        kInvalid: _ClassVar[ErrorProto.Type]
        kPermissionDenied: _ClassVar[ErrorProto.Type]
        kNeedFixing: _ClassVar[ErrorProto.Type]
        kQuotaExceeded: _ClassVar[ErrorProto.Type]
        kOutOfSpace: _ClassVar[ErrorProto.Type]
        kNotDirectory: _ClassVar[ErrorProto.Type]
        kIsDirectory: _ClassVar[ErrorProto.Type]
        kNameTooLong: _ClassVar[ErrorProto.Type]
        kNotEmpty: _ClassVar[ErrorProto.Type]
        kTooManyHardLinks: _ClassVar[ErrorProto.Type]
        kNotSynchronized: _ClassVar[ErrorProto.Type]
        kBadCookie: _ClassVar[ErrorProto.Type]
        kCrossDeviceLink: _ClassVar[ErrorProto.Type]
        kNeedExclusivePin: _ClassVar[ErrorProto.Type]
        kNotActionOwner: _ClassVar[ErrorProto.Type]
        kCorrupt: _ClassVar[ErrorProto.Type]
        kSkipped: _ClassVar[ErrorProto.Type]
        kVixError: _ClassVar[ErrorProto.Type]
        kFsError: _ClassVar[ErrorProto.Type]
        kRejected: _ClassVar[ErrorProto.Type]
        kDuplicate: _ClassVar[ErrorProto.Type]
        kNotSupported: _ClassVar[ErrorProto.Type]
        kMoreProcessingRequired: _ClassVar[ErrorProto.Type]
        kLogonFailure: _ClassVar[ErrorProto.Type]
        kInvalidInfoClass: _ClassVar[ErrorProto.Type]
        kNtError: _ClassVar[ErrorProto.Type]
        kCanceled: _ClassVar[ErrorProto.Type]
        kNotConnected: _ClassVar[ErrorProto.Type]
        kResumeIncomplete: _ClassVar[ErrorProto.Type]
        kNotOwner: _ClassVar[ErrorProto.Type]
        kAgentError: _ClassVar[ErrorProto.Type]
        kLdapError: _ClassVar[ErrorProto.Type]
        kNoAdServices: _ClassVar[ErrorProto.Type]
        kNoneMapped: _ClassVar[ErrorProto.Type]
        kSomeNotMapped: _ClassVar[ErrorProto.Type]
        kKerberosInternal: _ClassVar[ErrorProto.Type]
        kIncorrectPassword: _ClassVar[ErrorProto.Type]
        kUnknownUser: _ClassVar[ErrorProto.Type]
        kAdNotReachable: _ClassVar[ErrorProto.Type]
        kInternalError: _ClassVar[ErrorProto.Type]
        kResourceTemporarilyUnavailable: _ClassVar[ErrorProto.Type]
        kSSLError: _ClassVar[ErrorProto.Type]
        kDiskLibError: _ClassVar[ErrorProto.Type]
        kCloneDataJournalFailed: _ClassVar[ErrorProto.Type]
        kRangeNotSatisfiable: _ClassVar[ErrorProto.Type]
        kNotEnoughNodes: _ClassVar[ErrorProto.Type]
        kNotMinionLeader: _ClassVar[ErrorProto.Type]
        kIsStubNode: _ClassVar[ErrorProto.Type]
        kVixTimeoutError: _ClassVar[ErrorProto.Type]
        kFileForcedClosed: _ClassVar[ErrorProto.Type]
        kDeletePending: _ClassVar[ErrorProto.Type]
        kInterrupted: _ClassVar[ErrorProto.Type]
        kFileDataLocked: _ClassVar[ErrorProto.Type]
        kWinbindError: _ClassVar[ErrorProto.Type]
        kDiskReadOnly: _ClassVar[ErrorProto.Type]
        kNeedExclusiveLock: _ClassVar[ErrorProto.Type]
        kNeedSharedLock: _ClassVar[ErrorProto.Type]
        kDiskNotFound: _ClassVar[ErrorProto.Type]
        kEncryptionKeyNotFound: _ClassVar[ErrorProto.Type]
        kBadRpcVersion: _ClassVar[ErrorProto.Type]
        kViewNotEmpty: _ClassVar[ErrorProto.Type]
        kEntityHandleAffinityChanged: _ClassVar[ErrorProto.Type]
        kActiveAntivirusProviderNotFound: _ClassVar[ErrorProto.Type]
        kIceboxJobFailed: _ClassVar[ErrorProto.Type]
        kWaitFailed: _ClassVar[ErrorProto.Type]
        kUnsupportedContext: _ClassVar[ErrorProto.Type]
        kDataMismatch: _ClassVar[ErrorProto.Type]
        kNeedForwarding: _ClassVar[ErrorProto.Type]
        kLicense: _ClassVar[ErrorProto.Type]
        kMSGraphError: _ClassVar[ErrorProto.Type]
        kOutlookEwsError: _ClassVar[ErrorProto.Type]
        kIsMegaFile: _ClassVar[ErrorProto.Type]
        kInodeMissing: _ClassVar[ErrorProto.Type]
        kIceboxFileNotSupported: _ClassVar[ErrorProto.Type]
        kNisError: _ClassVar[ErrorProto.Type]
        kCloudError: _ClassVar[ErrorProto.Type]
        kKeystoneCommunicationError: _ClassVar[ErrorProto.Type]
        kKeystoneError: _ClassVar[ErrorProto.Type]
        kBifrostError: _ClassVar[ErrorProto.Type]
        kStoppedOnSymlink: _ClassVar[ErrorProto.Type]
        kCloudResourceNotAvailable: _ClassVar[ErrorProto.Type]
        kEOF: _ClassVar[ErrorProto.Type]
        kKMSError: _ClassVar[ErrorProto.Type]
        kProtoParseError: _ClassVar[ErrorProto.Type]
        kDnsError: _ClassVar[ErrorProto.Type]
        kPathNonExistent: _ClassVar[ErrorProto.Type]
        kIceboxNodeNotSerialized: _ClassVar[ErrorProto.Type]
        kSequencerError: _ClassVar[ErrorProto.Type]
        kEncryptionFailure: _ClassVar[ErrorProto.Type]
        kBlurFlushRequired: _ClassVar[ErrorProto.Type]
        kTrackingViewAlreadyLive: _ClassVar[ErrorProto.Type]
        kInsufficientResources: _ClassVar[ErrorProto.Type]
        kPasswordExpired: _ClassVar[ErrorProto.Type]
        kLongRunningOperation: _ClassVar[ErrorProto.Type]
        kAtomError: _ClassVar[ErrorProto.Type]
        kPaused: _ClassVar[ErrorProto.Type]
        kAlreadyEncoded: _ClassVar[ErrorProto.Type]
        kApiVersionMismatchError: _ClassVar[ErrorProto.Type]
        kOrphanInode: _ClassVar[ErrorProto.Type]
        kNexusError: _ClassVar[ErrorProto.Type]
        kMachineAccountNeedFixing: _ClassVar[ErrorProto.Type]
        kIntentNotFound: _ClassVar[ErrorProto.Type]
        kVosEOF: _ClassVar[ErrorProto.Type]
        kVosFailure: _ClassVar[ErrorProto.Type]
        kVosIgnoreOffset: _ClassVar[ErrorProto.Type]
        kDomainController: _ClassVar[ErrorProto.Type]
        kTooManyRequests: _ClassVar[ErrorProto.Type]
    kNoError: ErrorProto.Type
    kTransportError: ErrorProto.Type
    kTimeout: ErrorProto.Type
    kStale: ErrorProto.Type
    kNonExistent: ErrorProto.Type
    kRetry: ErrorProto.Type
    kNotLeader: ErrorProto.Type
    kBusy: ErrorProto.Type
    kCASError: ErrorProto.Type
    kAlreadyExists: ErrorProto.Type
    kInvalid: ErrorProto.Type
    kPermissionDenied: ErrorProto.Type
    kNeedFixing: ErrorProto.Type
    kQuotaExceeded: ErrorProto.Type
    kOutOfSpace: ErrorProto.Type
    kNotDirectory: ErrorProto.Type
    kIsDirectory: ErrorProto.Type
    kNameTooLong: ErrorProto.Type
    kNotEmpty: ErrorProto.Type
    kTooManyHardLinks: ErrorProto.Type
    kNotSynchronized: ErrorProto.Type
    kBadCookie: ErrorProto.Type
    kCrossDeviceLink: ErrorProto.Type
    kNeedExclusivePin: ErrorProto.Type
    kNotActionOwner: ErrorProto.Type
    kCorrupt: ErrorProto.Type
    kSkipped: ErrorProto.Type
    kVixError: ErrorProto.Type
    kFsError: ErrorProto.Type
    kRejected: ErrorProto.Type
    kDuplicate: ErrorProto.Type
    kNotSupported: ErrorProto.Type
    kMoreProcessingRequired: ErrorProto.Type
    kLogonFailure: ErrorProto.Type
    kInvalidInfoClass: ErrorProto.Type
    kNtError: ErrorProto.Type
    kCanceled: ErrorProto.Type
    kNotConnected: ErrorProto.Type
    kResumeIncomplete: ErrorProto.Type
    kNotOwner: ErrorProto.Type
    kAgentError: ErrorProto.Type
    kLdapError: ErrorProto.Type
    kNoAdServices: ErrorProto.Type
    kNoneMapped: ErrorProto.Type
    kSomeNotMapped: ErrorProto.Type
    kKerberosInternal: ErrorProto.Type
    kIncorrectPassword: ErrorProto.Type
    kUnknownUser: ErrorProto.Type
    kAdNotReachable: ErrorProto.Type
    kInternalError: ErrorProto.Type
    kResourceTemporarilyUnavailable: ErrorProto.Type
    kSSLError: ErrorProto.Type
    kDiskLibError: ErrorProto.Type
    kCloneDataJournalFailed: ErrorProto.Type
    kRangeNotSatisfiable: ErrorProto.Type
    kNotEnoughNodes: ErrorProto.Type
    kNotMinionLeader: ErrorProto.Type
    kIsStubNode: ErrorProto.Type
    kVixTimeoutError: ErrorProto.Type
    kFileForcedClosed: ErrorProto.Type
    kDeletePending: ErrorProto.Type
    kInterrupted: ErrorProto.Type
    kFileDataLocked: ErrorProto.Type
    kWinbindError: ErrorProto.Type
    kDiskReadOnly: ErrorProto.Type
    kNeedExclusiveLock: ErrorProto.Type
    kNeedSharedLock: ErrorProto.Type
    kDiskNotFound: ErrorProto.Type
    kEncryptionKeyNotFound: ErrorProto.Type
    kBadRpcVersion: ErrorProto.Type
    kViewNotEmpty: ErrorProto.Type
    kEntityHandleAffinityChanged: ErrorProto.Type
    kActiveAntivirusProviderNotFound: ErrorProto.Type
    kIceboxJobFailed: ErrorProto.Type
    kWaitFailed: ErrorProto.Type
    kUnsupportedContext: ErrorProto.Type
    kDataMismatch: ErrorProto.Type
    kNeedForwarding: ErrorProto.Type
    kLicense: ErrorProto.Type
    kMSGraphError: ErrorProto.Type
    kOutlookEwsError: ErrorProto.Type
    kIsMegaFile: ErrorProto.Type
    kInodeMissing: ErrorProto.Type
    kIceboxFileNotSupported: ErrorProto.Type
    kNisError: ErrorProto.Type
    kCloudError: ErrorProto.Type
    kKeystoneCommunicationError: ErrorProto.Type
    kKeystoneError: ErrorProto.Type
    kBifrostError: ErrorProto.Type
    kStoppedOnSymlink: ErrorProto.Type
    kCloudResourceNotAvailable: ErrorProto.Type
    kEOF: ErrorProto.Type
    kKMSError: ErrorProto.Type
    kProtoParseError: ErrorProto.Type
    kDnsError: ErrorProto.Type
    kPathNonExistent: ErrorProto.Type
    kIceboxNodeNotSerialized: ErrorProto.Type
    kSequencerError: ErrorProto.Type
    kEncryptionFailure: ErrorProto.Type
    kBlurFlushRequired: ErrorProto.Type
    kTrackingViewAlreadyLive: ErrorProto.Type
    kInsufficientResources: ErrorProto.Type
    kPasswordExpired: ErrorProto.Type
    kLongRunningOperation: ErrorProto.Type
    kAtomError: ErrorProto.Type
    kPaused: ErrorProto.Type
    kAlreadyEncoded: ErrorProto.Type
    kApiVersionMismatchError: ErrorProto.Type
    kOrphanInode: ErrorProto.Type
    kNexusError: ErrorProto.Type
    kMachineAccountNeedFixing: ErrorProto.Type
    kIntentNotFound: ErrorProto.Type
    kVosEOF: ErrorProto.Type
    kVosFailure: ErrorProto.Type
    kVosIgnoreOffset: ErrorProto.Type
    kDomainController: ErrorProto.Type
    kTooManyRequests: ErrorProto.Type
    TYPE_FIELD_NUMBER: _ClassVar[int]
    ERROR_DETAIL_FIELD_NUMBER: _ClassVar[int]
    DETAILED_ERROR_MSG_FIELD_NUMBER: _ClassVar[int]
    type: ErrorProto.Type
    error_detail: str
    detailed_error_msg: _message_catalog_pb2.MessageProto
    def __init__(self, type: _Optional[_Union[ErrorProto.Type, str]] = ..., error_detail: _Optional[str] = ..., detailed_error_msg: _Optional[_Union[_message_catalog_pb2.MessageProto, _Mapping]] = ...) -> None: ...
