# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scribe/newscribe/stub/server_error.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(scribe/newscribe/stub/server_error.proto\x12\x16\x63ohesity.scribe.server\"\xfe\x06\n\x10ServerErrorProto\x12\x45\n\x04type\x18\x01 \x01(\x0e\x32-.cohesity.scribe.server.ServerErrorProto.Type:\x08kNoError\x12\x11\n\terror_msg\x18\x02 \x01(\t\"\x8f\x06\n\x04Type\x12\x0c\n\x08kNoError\x10\x00\x12\x0c\n\x08kTimeout\x10\x01\x12\x15\n\x11kTableNonExistent\x10\x02\x12\x15\n\x11kInvalidSequencer\x10\x03\x12\x0f\n\x0bkCASFailure\x10\x04\x12\n\n\x06kRetry\x10\x05\x12\x13\n\x0fkTransportError\x10\x06\x12\x0e\n\nkNotLeader\x10\x07\x12\x10\n\x0ckNotCaughtup\x10\x08\x12\x14\n\x10kSenderNotLeader\x10\t\x12\x10\n\x0ckCrashClient\x10\n\x12\x12\n\x0ekInvalidBucket\x10\x0b\x12\x17\n\x13kReplicaNotCaughtup\x10\x0c\x12\x18\n\x14kLeaderInstanceStale\x10\r\x12\x13\n\x0fkBucketDbLocked\x10\x0e\x12\x1f\n\x1bkTxLeaderLockSequencerStale\x10\x0f\x12\x1f\n\x1bkRxLeaderLockSequencerStale\x10\x10\x12\x18\n\x14kViewVersionMismatch\x10\x11\x12\x1b\n\x17kTableMdVersionMismatch\x10\x12\x12\x10\n\x0ckUnavailable\x10\x13\x12\x14\n\x10kBucketNotHosted\x10\x14\x12\x11\n\rkStaleRequest\x10\x15\x12\x14\n\x10kInjectedFailure\x10\x16\x12\x11\n\rkOpIncomplete\x10\x17\x12\x16\n\x12kInsufficientSpace\x10\x18\x12\x1f\n\x1bkBucketLockTryAcquireFailed\x10\x19\x12\x1a\n\x16kExceedsMaxMessageSize\x10\x1a\x12\x1f\n\x1bkUnrecoverableDataFileError\x10\x1b\x12\x1a\n\x16kTabletStateNotCurrent\x10\x1c\x12\x1d\n\x19kParanoidConsistencyError\x10\x1d\x12#\n\x1fkBucketsOnDifferentConstituents\x10\x1e\x12\x14\n\x10kFeatureNotReady\x10\x1f\x12\x0b\n\x07kLeader\x10 \x12\x0f\n\x0bkErrorCount\x10!')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scribe.newscribe.stub.server_error_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SERVERERRORPROTO']._serialized_start=69
  _globals['_SERVERERRORPROTO']._serialized_end=963
  _globals['_SERVERERRORPROTO_TYPE']._serialized_start=180
  _globals['_SERVERERRORPROTO_TYPE']._serialized_end=963
# @@protoc_insertion_point(module_scope)
