# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: magneto/agents/linux/stub/rds_rpc.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from magneto.agents.linux.stub import rds_param_pb2 as magneto_dot_agents_dot_linux_dot_stub_dot_rds__param__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'magneto/agents/linux/stub/rds_rpc.proto\x12&cohesity.magneto.agents.linux.rds.stub\x1a)magneto/agents/linux/stub/rds_param.proto2\x91\x02\n\rRdsRpcService\x12\x8c\x01\n\x0fPrepareInstance\x12:.cohesity.magneto.agents.linux.rds.stub.PrepareInstanceArg\x1a=.cohesity.magneto.agents.linux.rds.stub.PrepareInstanceResult\x12q\n\x06\x42\x61\x63kup\x12\x31.cohesity.magneto.agents.linux.rds.stub.BackupArg\x1a\x34.cohesity.magneto.agents.linux.rds.stub.BackupResult')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'magneto.agents.linux.stub.rds_rpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RDSRPCSERVICE']._serialized_start=127
  _globals['_RDSRPCSERVICE']._serialized_end=400
# @@protoc_insertion_point(module_scope)
