# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apollo/mr/pipeline/test/sales_analytics.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-apollo/mr/pipeline/test/sales_analytics.proto\x12 cohesity.apollo.mr.pipeline.test\"-\n\x04Sale\x12\x13\n\x0bsale_amount\x18\x01 \x01(\x05\x12\x10\n\x08\x63urrency\x18\x02 \x01(\t\"\xcb\x01\n\x1aSalesAnalyticsPipelineData\x12k\n\x13\x63urrency_converters\x18\x01 \x03(\x0b\x32N.cohesity.apollo.mr.pipeline.test.SalesAnalyticsPipelineData.CurrencyConverter\x1a@\n\x11\x43urrencyConverter\x12\x10\n\x08\x63urrency\x18\x01 \x01(\t\x12\x19\n\x11\x63onversion_factor\x18\x02 \x01(\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'apollo.mr.pipeline.test.sales_analytics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SALE']._serialized_start=83
  _globals['_SALE']._serialized_end=128
  _globals['_SALESANALYTICSPIPELINEDATA']._serialized_start=131
  _globals['_SALESANALYTICSPIPELINEDATA']._serialized_end=334
  _globals['_SALESANALYTICSPIPELINEDATA_CURRENCYCONVERTER']._serialized_start=270
  _globals['_SALESANALYTICSPIPELINEDATA_CURRENCYCONVERTER']._serialized_end=334
# @@protoc_insertion_point(module_scope)
