# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: experimental/milind/new_hire_exercise/app_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from open_util.net import protorpc_pb2 as open__util_dot_net_dot_protorpc__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7experimental/milind/new_hire_exercise/app_service.proto\x12%experimental.milind.new_hire_exercise\x1a\x1copen_util/net/protorpc.proto\"#\n\x0ePingRequestArg\x12\x11\n\tsay_hello\x18\x01 \x02(\x08\"\x1d\n\x0cPingResponse\x12\r\n\x05hello\x18\x01 \x02(\x08\x32\x92\x01\n\x0bPingService\x12t\n\x04Ping\x12\x35.experimental.milind.new_hire_exercise.PingRequestArg\x1a\x33.experimental.milind.new_hire_exercise.PingResponse\"\x00\x1a\r\x80\xf1\x04\xe8\x07\x88\xf1\x04\x01\x90\xf1\x04\x02\x42\x03\x80\x01\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'experimental.milind.new_hire_exercise.app_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\200\001\001'
  _globals['_PINGSERVICE']._loaded_options = None
  _globals['_PINGSERVICE']._serialized_options = b'\200\361\004\350\007\210\361\004\001\220\361\004\002'
  _globals['_PINGREQUESTARG']._serialized_start=128
  _globals['_PINGREQUESTARG']._serialized_end=163
  _globals['_PINGRESPONSE']._serialized_start=165
  _globals['_PINGRESPONSE']._serialized_end=194
  _globals['_PINGSERVICE']._serialized_start=197
  _globals['_PINGSERVICE']._serialized_end=343
# @@protoc_insertion_point(module_scope)
