# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: experimental/smurugesan/protobuf-3.6.0/php/tests/proto/test_reserved_message_upper.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nXexperimental/smurugesan/protobuf-3.6.0/php/tests/proto/test_reserved_message_upper.proto\x12\x05upper\"\n\n\x08\x41\x42STRACT\"\x05\n\x03\x41ND\"\x07\n\x05\x41RRAY\"\x04\n\x02\x41S\"\x07\n\x05\x42REAK\"\n\n\x08\x43\x41LLABLE\"\x06\n\x04\x43\x41SE\"\x07\n\x05\x43\x41TCH\"\x07\n\x05\x43LASS\"\x07\n\x05\x43LONE\"\x07\n\x05\x43ONST\"\n\n\x08\x43ONTINUE\"\t\n\x07\x44\x45\x43LARE\"\t\n\x07\x44\x45\x46\x41ULT\"\x05\n\x03\x44IE\"\x04\n\x02\x44O\"\x06\n\x04\x45\x43HO\"\x06\n\x04\x45LSE\"\x08\n\x06\x45LSEIF\"\x07\n\x05\x45MPTY\"\x0c\n\nENDDECLARE\"\x08\n\x06\x45NDFOR\"\x0c\n\nENDFOREACH\"\x07\n\x05\x45NDIF\"\x0b\n\tENDSWITCH\"\n\n\x08\x45NDWHILE\"\x06\n\x04\x45VAL\"\x06\n\x04\x45XIT\"\t\n\x07\x45XTENDS\"\x07\n\x05\x46INAL\"\x05\n\x03\x46OR\"\t\n\x07\x46OREACH\"\n\n\x08\x46UNCTION\"\x08\n\x06GLOBAL\"\x06\n\x04GOTO\"\x04\n\x02IF\"\x0c\n\nIMPLEMENTS\"\t\n\x07INCLUDE\"\x0e\n\x0cINCLUDE_ONCE\"\x0c\n\nINSTANCEOF\"\x0b\n\tINSTEADOF\"\x0b\n\tINTERFACE\"\x07\n\x05ISSET\"\x06\n\x04LIST\"\x0b\n\tNAMESPACE\"\x05\n\x03NEW\"\x04\n\x02OR\"\x07\n\x05PRINT\"\t\n\x07PRIVATE\"\x0b\n\tPROTECTED\"\x08\n\x06PUBLIC\"\t\n\x07REQUIRE\"\x0e\n\x0cREQUIRE_ONCE\"\x08\n\x06RETURN\"\x08\n\x06STATIC\"\x08\n\x06SWITCH\"\x07\n\x05THROW\"\x07\n\x05TRAIT\"\x05\n\x03TRY\"\x07\n\x05UNSET\"\x05\n\x03USE\"\x05\n\x03VAR\"\x07\n\x05WHILE\"\x05\n\x03XOR\"\x05\n\x03INT\"\x07\n\x05\x46LOAT\"\x06\n\x04\x42OOL\"\x08\n\x06STRING\"\x06\n\x04TRUE\"\x07\n\x05\x46\x41LSE\"\x06\n\x04NULL\"\x06\n\x04VOID\"\n\n\x08ITERABLEb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'experimental.smurugesan.protobuf_3.6.0.php.tests.proto.test_reserved_message_upper_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ABSTRACT']._serialized_start=99
  _globals['_ABSTRACT']._serialized_end=109
  _globals['_AND']._serialized_start=111
  _globals['_AND']._serialized_end=116
  _globals['_ARRAY']._serialized_start=118
  _globals['_ARRAY']._serialized_end=125
  _globals['_AS']._serialized_start=127
  _globals['_AS']._serialized_end=131
  _globals['_BREAK']._serialized_start=133
  _globals['_BREAK']._serialized_end=140
  _globals['_CALLABLE']._serialized_start=142
  _globals['_CALLABLE']._serialized_end=152
  _globals['_CASE']._serialized_start=154
  _globals['_CASE']._serialized_end=160
  _globals['_CATCH']._serialized_start=162
  _globals['_CATCH']._serialized_end=169
  _globals['_CLASS']._serialized_start=171
  _globals['_CLASS']._serialized_end=178
  _globals['_CLONE']._serialized_start=180
  _globals['_CLONE']._serialized_end=187
  _globals['_CONST']._serialized_start=189
  _globals['_CONST']._serialized_end=196
  _globals['_CONTINUE']._serialized_start=198
  _globals['_CONTINUE']._serialized_end=208
  _globals['_DECLARE']._serialized_start=210
  _globals['_DECLARE']._serialized_end=219
  _globals['_DEFAULT']._serialized_start=221
  _globals['_DEFAULT']._serialized_end=230
  _globals['_DIE']._serialized_start=232
  _globals['_DIE']._serialized_end=237
  _globals['_DO']._serialized_start=239
  _globals['_DO']._serialized_end=243
  _globals['_ECHO']._serialized_start=245
  _globals['_ECHO']._serialized_end=251
  _globals['_ELSE']._serialized_start=253
  _globals['_ELSE']._serialized_end=259
  _globals['_ELSEIF']._serialized_start=261
  _globals['_ELSEIF']._serialized_end=269
  _globals['_EMPTY']._serialized_start=271
  _globals['_EMPTY']._serialized_end=278
  _globals['_ENDDECLARE']._serialized_start=280
  _globals['_ENDDECLARE']._serialized_end=292
  _globals['_ENDFOR']._serialized_start=294
  _globals['_ENDFOR']._serialized_end=302
  _globals['_ENDFOREACH']._serialized_start=304
  _globals['_ENDFOREACH']._serialized_end=316
  _globals['_ENDIF']._serialized_start=318
  _globals['_ENDIF']._serialized_end=325
  _globals['_ENDSWITCH']._serialized_start=327
  _globals['_ENDSWITCH']._serialized_end=338
  _globals['_ENDWHILE']._serialized_start=340
  _globals['_ENDWHILE']._serialized_end=350
  _globals['_EVAL']._serialized_start=352
  _globals['_EVAL']._serialized_end=358
  _globals['_EXIT']._serialized_start=360
  _globals['_EXIT']._serialized_end=366
  _globals['_EXTENDS']._serialized_start=368
  _globals['_EXTENDS']._serialized_end=377
  _globals['_FINAL']._serialized_start=379
  _globals['_FINAL']._serialized_end=386
  _globals['_FOR']._serialized_start=388
  _globals['_FOR']._serialized_end=393
  _globals['_FOREACH']._serialized_start=395
  _globals['_FOREACH']._serialized_end=404
  _globals['_FUNCTION']._serialized_start=406
  _globals['_FUNCTION']._serialized_end=416
  _globals['_GLOBAL']._serialized_start=418
  _globals['_GLOBAL']._serialized_end=426
  _globals['_GOTO']._serialized_start=428
  _globals['_GOTO']._serialized_end=434
  _globals['_IF']._serialized_start=436
  _globals['_IF']._serialized_end=440
  _globals['_IMPLEMENTS']._serialized_start=442
  _globals['_IMPLEMENTS']._serialized_end=454
  _globals['_INCLUDE']._serialized_start=456
  _globals['_INCLUDE']._serialized_end=465
  _globals['_INCLUDE_ONCE']._serialized_start=467
  _globals['_INCLUDE_ONCE']._serialized_end=481
  _globals['_INSTANCEOF']._serialized_start=483
  _globals['_INSTANCEOF']._serialized_end=495
  _globals['_INSTEADOF']._serialized_start=497
  _globals['_INSTEADOF']._serialized_end=508
  _globals['_INTERFACE']._serialized_start=510
  _globals['_INTERFACE']._serialized_end=521
  _globals['_ISSET']._serialized_start=523
  _globals['_ISSET']._serialized_end=530
  _globals['_LIST']._serialized_start=532
  _globals['_LIST']._serialized_end=538
  _globals['_NAMESPACE']._serialized_start=540
  _globals['_NAMESPACE']._serialized_end=551
  _globals['_NEW']._serialized_start=553
  _globals['_NEW']._serialized_end=558
  _globals['_OR']._serialized_start=560
  _globals['_OR']._serialized_end=564
  _globals['_PRINT']._serialized_start=566
  _globals['_PRINT']._serialized_end=573
  _globals['_PRIVATE']._serialized_start=575
  _globals['_PRIVATE']._serialized_end=584
  _globals['_PROTECTED']._serialized_start=586
  _globals['_PROTECTED']._serialized_end=597
  _globals['_PUBLIC']._serialized_start=599
  _globals['_PUBLIC']._serialized_end=607
  _globals['_REQUIRE']._serialized_start=609
  _globals['_REQUIRE']._serialized_end=618
  _globals['_REQUIRE_ONCE']._serialized_start=620
  _globals['_REQUIRE_ONCE']._serialized_end=634
  _globals['_RETURN']._serialized_start=636
  _globals['_RETURN']._serialized_end=644
  _globals['_STATIC']._serialized_start=646
  _globals['_STATIC']._serialized_end=654
  _globals['_SWITCH']._serialized_start=656
  _globals['_SWITCH']._serialized_end=664
  _globals['_THROW']._serialized_start=666
  _globals['_THROW']._serialized_end=673
  _globals['_TRAIT']._serialized_start=675
  _globals['_TRAIT']._serialized_end=682
  _globals['_TRY']._serialized_start=684
  _globals['_TRY']._serialized_end=689
  _globals['_UNSET']._serialized_start=691
  _globals['_UNSET']._serialized_end=698
  _globals['_USE']._serialized_start=700
  _globals['_USE']._serialized_end=705
  _globals['_VAR']._serialized_start=707
  _globals['_VAR']._serialized_end=712
  _globals['_WHILE']._serialized_start=714
  _globals['_WHILE']._serialized_end=721
  _globals['_XOR']._serialized_start=723
  _globals['_XOR']._serialized_end=728
  _globals['_INT']._serialized_start=730
  _globals['_INT']._serialized_end=735
  _globals['_FLOAT']._serialized_start=737
  _globals['_FLOAT']._serialized_end=744
  _globals['_BOOL']._serialized_start=746
  _globals['_BOOL']._serialized_end=752
  _globals['_STRING']._serialized_start=754
  _globals['_STRING']._serialized_end=762
  _globals['_TRUE']._serialized_start=764
  _globals['_TRUE']._serialized_end=770
  _globals['_FALSE']._serialized_start=772
  _globals['_FALSE']._serialized_end=779
  _globals['_NULL']._serialized_start=781
  _globals['_NULL']._serialized_end=787
  _globals['_VOID']._serialized_start=789
  _globals['_VOID']._serialized_end=795
  _globals['_ITERABLE']._serialized_start=797
  _globals['_ITERABLE']._serialized_end=807
# @@protoc_insertion_point(module_scope)
