# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: experimental/deba/rpc/file_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from open_util.net import protorpc_pb2 as open__util_dot_net_dot_protorpc__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(experimental/deba/rpc/file_service.proto\x12\x1e\x63ohesity.experimental.deba.rpc\x1a\x1copen_util/net/protorpc.proto\"&\n\x11\x43reateFileRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\"\x81\x01\n\x10\x43reateFileResult\x12?\n\x0breturn_code\x18\x01 \x01(\x0e\x32*.cohesity.experimental.deba.rpc.ReturnCode\x12,\n\nreturn_msg\x18\x02 \x01(\t:\x18\x46ile created successfull\"H\n\x0fReadFileRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x12\n\x06offset\x18\x02 \x01(\x03:\x02-1\x12\x0e\n\x06length\x18\x03 \x01(\x03\"Q\n\x0eReadFileResult\x12?\n\x0breturn_code\x18\x01 \x01(\x0e\x32*.cohesity.experimental.deba.rpc.ReturnCode\"I\n\x10WriteFileRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x12\n\x06offset\x18\x02 \x01(\x03:\x02-1\x12\x0e\n\x06length\x18\x03 \x01(\x03\"R\n\x0fWriteFileResult\x12?\n\x0breturn_code\x18\x01 \x01(\x0e\x32*.cohesity.experimental.deba.rpc.ReturnCode*g\n\nReturnCode\x12\x0c\n\x08kSuccess\x10\x01\x12\x12\n\x0ekAlreadyExists\x10\x02\x12\x11\n\rkDoesNotExist\x10\x03\x12\x11\n\rkAccessDenied\x10\x04\x12\x11\n\rkUnknownError\x10\x05\x32\xfd\x02\n\x0b\x46ileService\x12s\n\nCreateFile\x12\x31.cohesity.experimental.deba.rpc.CreateFileRequest\x1a\x30.cohesity.experimental.deba.rpc.CreateFileResult\"\x00\x12r\n\rReadFileRange\x12/.cohesity.experimental.deba.rpc.ReadFileRequest\x1a..cohesity.experimental.deba.rpc.ReadFileResult\"\x00\x12u\n\x0eWriteFileRange\x12\x30.cohesity.experimental.deba.rpc.WriteFileRequest\x1a/.cohesity.experimental.deba.rpc.WriteFileResult\"\x00\x1a\x0e\x80\xf1\x04\xe0\xd4\x03\x88\xf1\x04\x01\x90\xf1\x04\x02\x42\x03\x80\x01\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'experimental.deba.rpc.file_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\200\001\001'
  _globals['_FILESERVICE']._loaded_options = None
  _globals['_FILESERVICE']._serialized_options = b'\200\361\004\340\324\003\210\361\004\001\220\361\004\002'
  _globals['_RETURNCODE']._serialized_start=594
  _globals['_RETURNCODE']._serialized_end=697
  _globals['_CREATEFILEREQUEST']._serialized_start=106
  _globals['_CREATEFILEREQUEST']._serialized_end=144
  _globals['_CREATEFILERESULT']._serialized_start=147
  _globals['_CREATEFILERESULT']._serialized_end=276
  _globals['_READFILEREQUEST']._serialized_start=278
  _globals['_READFILEREQUEST']._serialized_end=350
  _globals['_READFILERESULT']._serialized_start=352
  _globals['_READFILERESULT']._serialized_end=433
  _globals['_WRITEFILEREQUEST']._serialized_start=435
  _globals['_WRITEFILEREQUEST']._serialized_end=508
  _globals['_WRITEFILERESULT']._serialized_start=510
  _globals['_WRITEFILERESULT']._serialized_end=592
  _globals['_FILESERVICE']._serialized_start=700
  _globals['_FILESERVICE']._serialized_end=1081
# @@protoc_insertion_point(module_scope)
