# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: magneto/api/common/filters.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n magneto/api/common/filters.proto\x12\x1b\x63ohesity.magneto.api.common\"\xc3\x01\n\rSourceFilters\x12Z\n\x19\x65xclude_source_filter_vec\x18\x01 \x03(\x0b\x32\x37.cohesity.magneto.api.common.SourceFilters.SourceFilter\x1aV\n\x0cSourceFilter\x12\x15\n\rsource_filter\x18\x01 \x01(\t\x12\x10\n\x08is_regex\x18\x02 \x01(\x08\x12\x1d\n\x0e\x63\x61se_sensitive\x18\x03 \x01(\x08:\x05\x66\x61lse\"C\n\x14\x46ilteringPolicyProto\x12\x15\n\rallow_filters\x18\x01 \x03(\t\x12\x14\n\x0c\x64\x65ny_filters\x18\x02 \x03(\tB\x1dZ\x1b\x63ohesity/magneto/api/common')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'magneto.api.common.filters_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\033cohesity/magneto/api/common'
  _globals['_SOURCEFILTERS']._serialized_start=66
  _globals['_SOURCEFILTERS']._serialized_end=261
  _globals['_SOURCEFILTERS_SOURCEFILTER']._serialized_start=175
  _globals['_SOURCEFILTERS_SOURCEFILTER']._serialized_end=261
  _globals['_FILTERINGPOLICYPROTO']._serialized_start=263
  _globals['_FILTERINGPOLICYPROTO']._serialized_end=330
# @@protoc_insertion_point(module_scope)
