from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from typing import ClassVar as _ClassVar, Optional as _Optional

DESCRIPTOR: _descriptor.FileDescriptor

class NexusUrisProto(_message.Message):
    __slots__ = ("base_uri", "api_version", "cloud_cluster_create_uri", "cloud_cluster_add_nodes_uri", "cluster_destroy_uri", "cluster_start_uri", "cluster_stop_uri", "cluster_status_uri", "cluster_upgrade_uri", "cluster_list_packages_uri", "cluster_delete_packages_uri", "cluster_download_packages_uri", "cloud_node_join_cluster_uri", "node_disjoin_cluster_uri", "node_upgrade_uri", "node_package_uri", "node_upload_package_uri", "node_status_uri", "node_list_packages_uri", "node_delete_packages_uri", "node_stop_uri", "avahi_discover_nodes_uri", "cluster_update_gflags_uri", "cluster_list_gflags_uri", "cluster_config_update_uri", "cluster_remove_node_uri_deprecated", "cluster_has_new_packages_uri", "cluster_ack_new_packages_uri", "disk_mark_offline_uri", "disk_forget_uri", "disk_assimilate_uri", "cluster_bringup_uri", "cluster_expand_uri", "node_bringup_uri", "cluster_bringup_status_uri", "avahi_discover_all_nodes_uri", "node_check_upgradability_uri", "node_check_compatibility_uri", "node_hardware_info_uri", "cluster_list_network_interfaces_uri", "node_list_network_interfaces_uri", "cluster_update_network_interfaces_uri", "node_sync_upload_package_uri", "node_info_uri", "node_update_network_interfaces_uri", "node_update_routes_uri_deprecated", "cluster_restart_uri", "virtual_robo_cluster_create_uri", "cluster_tricorder_uri_deprecated", "fetch_node_level_tricorder_results_uri_deprecated", "cluster_ssh_key_upgrade_uri", "disk_extend_uri", "disk_discover_uri", "cluster_update_network_uri", "node_save_nexus_gflags_uri", "cluster_get_hosts_file_uri", "cluster_upload_hosts_file_uri", "cluster_list_platform_gflags_uri", "node_bringup_network_uri", "disk_identify_uri", "node_identify_uri", "node_raise_monitoring_alerts_uri", "firewall_list_uri", "firewall_update_uri", "route_add_uri", "route_show_uri", "route_delete_uri", "node_add_route_uri", "node_delete_route_uri", "ipmi_list_users_uri", "ipmi_get_lan_info_uri", "ipmi_get_fru_info_uri", "ipmi_get_sel_uri", "ipmi_get_sel_info_uri", "ipmi_get_sdr_info_uri", "ipmi_reset_bmc_uri", "ipmi_set_node_power_uri", "ntp_server_sync_uri", "bond_create_uri", "bond_delete_uri", "bond_update_uri", "ip_config_uri", "ip_unconfig_uri", "license_audit_uri", "license_upload_uri", "license_key_upload_uri", "account_usage_uri", "create_vm_uri", "list_vm_uri", "vm_status_uri", "vm_lcm_uri", "vm_delete_uri", "vm_list_internal_uri", "vm_launch_internal_uri", "vnc_access_uri", "vm_inventory_uri", "vm_status_internal_uri", "vm_lcm_internal_uri", "vm_delete_internal_uri", "vm_sched_uri", "vm_offline_migration_uri", "vmx_parse_uri", "interface_groups_list_uri", "interface_group_list_uri", "interface_group_create_uri", "interface_group_delete_uri", "interface_group_update_uri", "fetch_disk_space_details_uri", "is_account_classified_uri", "update_ipmi_user_uri", "update_ipmi_lan_info_uri", "license_expiry_date_uri", "vm_config_cleanup_uri", "cluster_services_state_uri", "node_services_state_uri", "reboot_proxy_vm_uri", "send_snmp_test_trap_uri", "license_cluster_claimed_uri", "axon_api_base_uri", "account_overusage_uri", "node_disk_discover_uri", "is_cluster_ready_uri", "update_linux_credentials_uri", "show_system_led_info_uri", "node_disk_assimilate_uri", "node_re_ip_uri", "interface_update_uri", "nodes_hostname_uri", "ipmi_cluster_list_users_uri", "ipmi_cluster_update_users_uri", "ipmi_cluster_get_lan_info_uri", "ipmi_cluster_update_lan_info_uri", "api_version2", "nodes_re_ip_uri", "node_ip_config_uri", "node_ip_unconfig_uri", "get_fru_data_uri", "set_fru_data_uri", "syslogs_uri", "syslogs_status_uri", "syslogs_audit_tags_uri", "syslogs_programnames_uri", "locate_fru_uri", "list_locate_fru_uri", "breakfix_api_base_uri", "list_fru_uri", "node_firewall_update_uri", "fru_qrp_uri", "chassis_uri", "racks_uri", "nfs_share_mount_uri", "security_support_user_token_uri", "security_support_user_sudo_access_uri", "node_nfs_share_mount_uri", "linux_command_execute_uri", "node_save_service_gflags_uri", "ssh_keys_md5sum_uri", "rigel_cluster_create_uri", "nfs_share_migrate_uri", "avahi_cluster_nodes_uri", "nodes_networking_reset_uri", "nodes_reset_state_uri", "cluster_reset_state_uri", "security_support_user_access_info_uri", "banner_uri", "update_banner_uri", "cluster_staging_info_uri", "nodes_staging_info_uri", "node_apply_service_gflags_uri", "node_disk_inventory_uri", "node_groups_list_uri", "node_group_list_uri", "node_group_create_uri", "node_group_delete_uri", "node_group_update_uri", "market_place_enable_uri", "rigel_update_node_network_uri", "remote_storage_purefb_register_uri", "remote_storage_purefb_fetch_details_uri", "nfs_share_configure_uri", "nodes_power_uri", "bifrost_ipam_allocate_networking_uri", "bifrost_ipam_release_networking_uri", "nfs_share_list_uri", "nfs_share_rebalance_uri", "remote_storage_purefb_monitor_uri", "sysctl_conf_uri", "cluster_install_package_uri", "cluster_remove_package_uri", "cluster_list_package_uri", "node_create_csr_uri", "system_app_status_uri", "node_import_signed_csr_uri", "cluster_update_package_enable_uri", "cluster_update_package_disable_uri", "cluster_update_package_list_uri", "yum_repo_add_uri", "yum_repo_enable_uri", "yum_repo_remove_uri", "yum_repos_list_uri", "custom_baseos_enable_uri", "custom_baseos_disable_uri", "custom_baseos_status_uri", "yum_repo_set_option_uri", "rigel_connectivity_check_uri", "linux_command_list_uri", "qos_list_uri", "qos_update_uri", "node_qos_update_uri", "support_user_put_2FA_uri", "support_user_get_2FA_uri", "he_onprem_update_network_uri", "node_get_csr_and_public_key_uri", "node_post_server_and_ca_cert_uri", "cluster_toggle_protorpc_encryption_uri", "send_alerts_uri", "nfs_share_create_snapshot_uri", "node_validate_sed_uri", "cluster_update_hardware_encryption_uri", "customer_managed_baseos_status_uri", "customer_managed_baseos_enable_uri", "customer_managed_baseos_disable_uri", "cluster_list_snapshot_uri", "cluster_create_snapshot_uri", "cluster_restore_snapshot_uri", "node_create_snapshot_uri", "node_restore_snapshot_uri", "create_snapshot_status_uri", "restore_snapshot_status_uri", "secure_shell_uri", "node_secure_shell_uri", "node_aggregate_uri", "node_disaggregate_uri", "cloud_cluster_add_nodes_async_uri", "cluster_bringup_async_uri", "virtual_robo_cluster_create_async_uri", "cloud_cluster_create_async_uri", "cluster_operation_status_uri", "cluster_expand_async_uri", "cluster_upgrade_uri_v2", "split_key_host_access_uri", "cluster_upgrade_check_run_tests_uri", "cluster_upgrade_check_show_results_uri", "cluster_fetch_latest_etcd_snapshot_node_ip_uri", "node_etcd_serve_latest_snapshot_uri", "generate_split_key_token_uri", "node_dns_update_uri", "cluster_update_airgap_config", "node_nfs_share_unmount_uri", "nfs_share_update_data_vip_uri", "firewall_profile_update_uri", "service_identity_global_enable_uri", "service_identity_disabled_ports_uri", "service_identity_status_uri", "firewall_profile_remove_uri", "node_firmware_inventory_uri", "node_firmware_upgrade_uri", "node_sync_import_crl_file_uri", "nfs_share_handle_change_uri", "node_upload_packages_by_url_uri", "upgrade_and_patch_uri", "upload_package_and_upgrade_patch_uri", "upgrade_space_check_uri", "node_power_operation_uri")
    BASE_URI_FIELD_NUMBER: _ClassVar[int]
    API_VERSION_FIELD_NUMBER: _ClassVar[int]
    CLOUD_CLUSTER_CREATE_URI_FIELD_NUMBER: _ClassVar[int]
    CLOUD_CLUSTER_ADD_NODES_URI_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_DESTROY_URI_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_START_URI_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_STOP_URI_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_STATUS_URI_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_UPGRADE_URI_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_LIST_PACKAGES_URI_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_DELETE_PACKAGES_URI_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_DOWNLOAD_PACKAGES_URI_FIELD_NUMBER: _ClassVar[int]
    CLOUD_NODE_JOIN_CLUSTER_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_DISJOIN_CLUSTER_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_UPGRADE_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_PACKAGE_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_UPLOAD_PACKAGE_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_STATUS_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_LIST_PACKAGES_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_DELETE_PACKAGES_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_STOP_URI_FIELD_NUMBER: _ClassVar[int]
    AVAHI_DISCOVER_NODES_URI_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_UPDATE_GFLAGS_URI_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_LIST_GFLAGS_URI_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_CONFIG_UPDATE_URI_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_REMOVE_NODE_URI_DEPRECATED_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_HAS_NEW_PACKAGES_URI_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_ACK_NEW_PACKAGES_URI_FIELD_NUMBER: _ClassVar[int]
    DISK_MARK_OFFLINE_URI_FIELD_NUMBER: _ClassVar[int]
    DISK_FORGET_URI_FIELD_NUMBER: _ClassVar[int]
    DISK_ASSIMILATE_URI_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_BRINGUP_URI_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_EXPAND_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_BRINGUP_URI_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_BRINGUP_STATUS_URI_FIELD_NUMBER: _ClassVar[int]
    AVAHI_DISCOVER_ALL_NODES_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_CHECK_UPGRADABILITY_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_CHECK_COMPATIBILITY_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_HARDWARE_INFO_URI_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_LIST_NETWORK_INTERFACES_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_LIST_NETWORK_INTERFACES_URI_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_UPDATE_NETWORK_INTERFACES_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_SYNC_UPLOAD_PACKAGE_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_INFO_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_UPDATE_NETWORK_INTERFACES_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_UPDATE_ROUTES_URI_DEPRECATED_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_RESTART_URI_FIELD_NUMBER: _ClassVar[int]
    VIRTUAL_ROBO_CLUSTER_CREATE_URI_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_TRICORDER_URI_DEPRECATED_FIELD_NUMBER: _ClassVar[int]
    FETCH_NODE_LEVEL_TRICORDER_RESULTS_URI_DEPRECATED_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_SSH_KEY_UPGRADE_URI_FIELD_NUMBER: _ClassVar[int]
    DISK_EXTEND_URI_FIELD_NUMBER: _ClassVar[int]
    DISK_DISCOVER_URI_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_UPDATE_NETWORK_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_SAVE_NEXUS_GFLAGS_URI_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_GET_HOSTS_FILE_URI_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_UPLOAD_HOSTS_FILE_URI_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_LIST_PLATFORM_GFLAGS_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_BRINGUP_NETWORK_URI_FIELD_NUMBER: _ClassVar[int]
    DISK_IDENTIFY_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_IDENTIFY_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_RAISE_MONITORING_ALERTS_URI_FIELD_NUMBER: _ClassVar[int]
    FIREWALL_LIST_URI_FIELD_NUMBER: _ClassVar[int]
    FIREWALL_UPDATE_URI_FIELD_NUMBER: _ClassVar[int]
    ROUTE_ADD_URI_FIELD_NUMBER: _ClassVar[int]
    ROUTE_SHOW_URI_FIELD_NUMBER: _ClassVar[int]
    ROUTE_DELETE_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_ADD_ROUTE_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_DELETE_ROUTE_URI_FIELD_NUMBER: _ClassVar[int]
    IPMI_LIST_USERS_URI_FIELD_NUMBER: _ClassVar[int]
    IPMI_GET_LAN_INFO_URI_FIELD_NUMBER: _ClassVar[int]
    IPMI_GET_FRU_INFO_URI_FIELD_NUMBER: _ClassVar[int]
    IPMI_GET_SEL_URI_FIELD_NUMBER: _ClassVar[int]
    IPMI_GET_SEL_INFO_URI_FIELD_NUMBER: _ClassVar[int]
    IPMI_GET_SDR_INFO_URI_FIELD_NUMBER: _ClassVar[int]
    IPMI_RESET_BMC_URI_FIELD_NUMBER: _ClassVar[int]
    IPMI_SET_NODE_POWER_URI_FIELD_NUMBER: _ClassVar[int]
    NTP_SERVER_SYNC_URI_FIELD_NUMBER: _ClassVar[int]
    BOND_CREATE_URI_FIELD_NUMBER: _ClassVar[int]
    BOND_DELETE_URI_FIELD_NUMBER: _ClassVar[int]
    BOND_UPDATE_URI_FIELD_NUMBER: _ClassVar[int]
    IP_CONFIG_URI_FIELD_NUMBER: _ClassVar[int]
    IP_UNCONFIG_URI_FIELD_NUMBER: _ClassVar[int]
    LICENSE_AUDIT_URI_FIELD_NUMBER: _ClassVar[int]
    LICENSE_UPLOAD_URI_FIELD_NUMBER: _ClassVar[int]
    LICENSE_KEY_UPLOAD_URI_FIELD_NUMBER: _ClassVar[int]
    ACCOUNT_USAGE_URI_FIELD_NUMBER: _ClassVar[int]
    CREATE_VM_URI_FIELD_NUMBER: _ClassVar[int]
    LIST_VM_URI_FIELD_NUMBER: _ClassVar[int]
    VM_STATUS_URI_FIELD_NUMBER: _ClassVar[int]
    VM_LCM_URI_FIELD_NUMBER: _ClassVar[int]
    VM_DELETE_URI_FIELD_NUMBER: _ClassVar[int]
    VM_LIST_INTERNAL_URI_FIELD_NUMBER: _ClassVar[int]
    VM_LAUNCH_INTERNAL_URI_FIELD_NUMBER: _ClassVar[int]
    VNC_ACCESS_URI_FIELD_NUMBER: _ClassVar[int]
    VM_INVENTORY_URI_FIELD_NUMBER: _ClassVar[int]
    VM_STATUS_INTERNAL_URI_FIELD_NUMBER: _ClassVar[int]
    VM_LCM_INTERNAL_URI_FIELD_NUMBER: _ClassVar[int]
    VM_DELETE_INTERNAL_URI_FIELD_NUMBER: _ClassVar[int]
    VM_SCHED_URI_FIELD_NUMBER: _ClassVar[int]
    VM_OFFLINE_MIGRATION_URI_FIELD_NUMBER: _ClassVar[int]
    VMX_PARSE_URI_FIELD_NUMBER: _ClassVar[int]
    INTERFACE_GROUPS_LIST_URI_FIELD_NUMBER: _ClassVar[int]
    INTERFACE_GROUP_LIST_URI_FIELD_NUMBER: _ClassVar[int]
    INTERFACE_GROUP_CREATE_URI_FIELD_NUMBER: _ClassVar[int]
    INTERFACE_GROUP_DELETE_URI_FIELD_NUMBER: _ClassVar[int]
    INTERFACE_GROUP_UPDATE_URI_FIELD_NUMBER: _ClassVar[int]
    FETCH_DISK_SPACE_DETAILS_URI_FIELD_NUMBER: _ClassVar[int]
    IS_ACCOUNT_CLASSIFIED_URI_FIELD_NUMBER: _ClassVar[int]
    UPDATE_IPMI_USER_URI_FIELD_NUMBER: _ClassVar[int]
    UPDATE_IPMI_LAN_INFO_URI_FIELD_NUMBER: _ClassVar[int]
    LICENSE_EXPIRY_DATE_URI_FIELD_NUMBER: _ClassVar[int]
    VM_CONFIG_CLEANUP_URI_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_SERVICES_STATE_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_SERVICES_STATE_URI_FIELD_NUMBER: _ClassVar[int]
    REBOOT_PROXY_VM_URI_FIELD_NUMBER: _ClassVar[int]
    SEND_SNMP_TEST_TRAP_URI_FIELD_NUMBER: _ClassVar[int]
    LICENSE_CLUSTER_CLAIMED_URI_FIELD_NUMBER: _ClassVar[int]
    AXON_API_BASE_URI_FIELD_NUMBER: _ClassVar[int]
    ACCOUNT_OVERUSAGE_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_DISK_DISCOVER_URI_FIELD_NUMBER: _ClassVar[int]
    IS_CLUSTER_READY_URI_FIELD_NUMBER: _ClassVar[int]
    UPDATE_LINUX_CREDENTIALS_URI_FIELD_NUMBER: _ClassVar[int]
    SHOW_SYSTEM_LED_INFO_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_DISK_ASSIMILATE_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_RE_IP_URI_FIELD_NUMBER: _ClassVar[int]
    INTERFACE_UPDATE_URI_FIELD_NUMBER: _ClassVar[int]
    NODES_HOSTNAME_URI_FIELD_NUMBER: _ClassVar[int]
    IPMI_CLUSTER_LIST_USERS_URI_FIELD_NUMBER: _ClassVar[int]
    IPMI_CLUSTER_UPDATE_USERS_URI_FIELD_NUMBER: _ClassVar[int]
    IPMI_CLUSTER_GET_LAN_INFO_URI_FIELD_NUMBER: _ClassVar[int]
    IPMI_CLUSTER_UPDATE_LAN_INFO_URI_FIELD_NUMBER: _ClassVar[int]
    API_VERSION2_FIELD_NUMBER: _ClassVar[int]
    NODES_RE_IP_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_IP_CONFIG_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_IP_UNCONFIG_URI_FIELD_NUMBER: _ClassVar[int]
    GET_FRU_DATA_URI_FIELD_NUMBER: _ClassVar[int]
    SET_FRU_DATA_URI_FIELD_NUMBER: _ClassVar[int]
    SYSLOGS_URI_FIELD_NUMBER: _ClassVar[int]
    SYSLOGS_STATUS_URI_FIELD_NUMBER: _ClassVar[int]
    SYSLOGS_AUDIT_TAGS_URI_FIELD_NUMBER: _ClassVar[int]
    SYSLOGS_PROGRAMNAMES_URI_FIELD_NUMBER: _ClassVar[int]
    LOCATE_FRU_URI_FIELD_NUMBER: _ClassVar[int]
    LIST_LOCATE_FRU_URI_FIELD_NUMBER: _ClassVar[int]
    BREAKFIX_API_BASE_URI_FIELD_NUMBER: _ClassVar[int]
    LIST_FRU_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_FIREWALL_UPDATE_URI_FIELD_NUMBER: _ClassVar[int]
    FRU_QRP_URI_FIELD_NUMBER: _ClassVar[int]
    CHASSIS_URI_FIELD_NUMBER: _ClassVar[int]
    RACKS_URI_FIELD_NUMBER: _ClassVar[int]
    NFS_SHARE_MOUNT_URI_FIELD_NUMBER: _ClassVar[int]
    SECURITY_SUPPORT_USER_TOKEN_URI_FIELD_NUMBER: _ClassVar[int]
    SECURITY_SUPPORT_USER_SUDO_ACCESS_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_NFS_SHARE_MOUNT_URI_FIELD_NUMBER: _ClassVar[int]
    LINUX_COMMAND_EXECUTE_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_SAVE_SERVICE_GFLAGS_URI_FIELD_NUMBER: _ClassVar[int]
    SSH_KEYS_MD5SUM_URI_FIELD_NUMBER: _ClassVar[int]
    RIGEL_CLUSTER_CREATE_URI_FIELD_NUMBER: _ClassVar[int]
    NFS_SHARE_MIGRATE_URI_FIELD_NUMBER: _ClassVar[int]
    AVAHI_CLUSTER_NODES_URI_FIELD_NUMBER: _ClassVar[int]
    NODES_NETWORKING_RESET_URI_FIELD_NUMBER: _ClassVar[int]
    NODES_RESET_STATE_URI_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_RESET_STATE_URI_FIELD_NUMBER: _ClassVar[int]
    SECURITY_SUPPORT_USER_ACCESS_INFO_URI_FIELD_NUMBER: _ClassVar[int]
    BANNER_URI_FIELD_NUMBER: _ClassVar[int]
    UPDATE_BANNER_URI_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_STAGING_INFO_URI_FIELD_NUMBER: _ClassVar[int]
    NODES_STAGING_INFO_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_APPLY_SERVICE_GFLAGS_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_DISK_INVENTORY_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_GROUPS_LIST_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_GROUP_LIST_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_GROUP_CREATE_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_GROUP_DELETE_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_GROUP_UPDATE_URI_FIELD_NUMBER: _ClassVar[int]
    MARKET_PLACE_ENABLE_URI_FIELD_NUMBER: _ClassVar[int]
    RIGEL_UPDATE_NODE_NETWORK_URI_FIELD_NUMBER: _ClassVar[int]
    REMOTE_STORAGE_PUREFB_REGISTER_URI_FIELD_NUMBER: _ClassVar[int]
    REMOTE_STORAGE_PUREFB_FETCH_DETAILS_URI_FIELD_NUMBER: _ClassVar[int]
    NFS_SHARE_CONFIGURE_URI_FIELD_NUMBER: _ClassVar[int]
    NODES_POWER_URI_FIELD_NUMBER: _ClassVar[int]
    BIFROST_IPAM_ALLOCATE_NETWORKING_URI_FIELD_NUMBER: _ClassVar[int]
    BIFROST_IPAM_RELEASE_NETWORKING_URI_FIELD_NUMBER: _ClassVar[int]
    NFS_SHARE_LIST_URI_FIELD_NUMBER: _ClassVar[int]
    NFS_SHARE_REBALANCE_URI_FIELD_NUMBER: _ClassVar[int]
    REMOTE_STORAGE_PUREFB_MONITOR_URI_FIELD_NUMBER: _ClassVar[int]
    SYSCTL_CONF_URI_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_INSTALL_PACKAGE_URI_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_REMOVE_PACKAGE_URI_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_LIST_PACKAGE_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_CREATE_CSR_URI_FIELD_NUMBER: _ClassVar[int]
    SYSTEM_APP_STATUS_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_IMPORT_SIGNED_CSR_URI_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_UPDATE_PACKAGE_ENABLE_URI_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_UPDATE_PACKAGE_DISABLE_URI_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_UPDATE_PACKAGE_LIST_URI_FIELD_NUMBER: _ClassVar[int]
    YUM_REPO_ADD_URI_FIELD_NUMBER: _ClassVar[int]
    YUM_REPO_ENABLE_URI_FIELD_NUMBER: _ClassVar[int]
    YUM_REPO_REMOVE_URI_FIELD_NUMBER: _ClassVar[int]
    YUM_REPOS_LIST_URI_FIELD_NUMBER: _ClassVar[int]
    CUSTOM_BASEOS_ENABLE_URI_FIELD_NUMBER: _ClassVar[int]
    CUSTOM_BASEOS_DISABLE_URI_FIELD_NUMBER: _ClassVar[int]
    CUSTOM_BASEOS_STATUS_URI_FIELD_NUMBER: _ClassVar[int]
    YUM_REPO_SET_OPTION_URI_FIELD_NUMBER: _ClassVar[int]
    RIGEL_CONNECTIVITY_CHECK_URI_FIELD_NUMBER: _ClassVar[int]
    LINUX_COMMAND_LIST_URI_FIELD_NUMBER: _ClassVar[int]
    QOS_LIST_URI_FIELD_NUMBER: _ClassVar[int]
    QOS_UPDATE_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_QOS_UPDATE_URI_FIELD_NUMBER: _ClassVar[int]
    SUPPORT_USER_PUT_2FA_URI_FIELD_NUMBER: _ClassVar[int]
    SUPPORT_USER_GET_2FA_URI_FIELD_NUMBER: _ClassVar[int]
    HE_ONPREM_UPDATE_NETWORK_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_GET_CSR_AND_PUBLIC_KEY_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_POST_SERVER_AND_CA_CERT_URI_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_TOGGLE_PROTORPC_ENCRYPTION_URI_FIELD_NUMBER: _ClassVar[int]
    SEND_ALERTS_URI_FIELD_NUMBER: _ClassVar[int]
    NFS_SHARE_CREATE_SNAPSHOT_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_VALIDATE_SED_URI_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_UPDATE_HARDWARE_ENCRYPTION_URI_FIELD_NUMBER: _ClassVar[int]
    CUSTOMER_MANAGED_BASEOS_STATUS_URI_FIELD_NUMBER: _ClassVar[int]
    CUSTOMER_MANAGED_BASEOS_ENABLE_URI_FIELD_NUMBER: _ClassVar[int]
    CUSTOMER_MANAGED_BASEOS_DISABLE_URI_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_LIST_SNAPSHOT_URI_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_CREATE_SNAPSHOT_URI_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_RESTORE_SNAPSHOT_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_CREATE_SNAPSHOT_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_RESTORE_SNAPSHOT_URI_FIELD_NUMBER: _ClassVar[int]
    CREATE_SNAPSHOT_STATUS_URI_FIELD_NUMBER: _ClassVar[int]
    RESTORE_SNAPSHOT_STATUS_URI_FIELD_NUMBER: _ClassVar[int]
    SECURE_SHELL_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_SECURE_SHELL_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_AGGREGATE_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_DISAGGREGATE_URI_FIELD_NUMBER: _ClassVar[int]
    CLOUD_CLUSTER_ADD_NODES_ASYNC_URI_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_BRINGUP_ASYNC_URI_FIELD_NUMBER: _ClassVar[int]
    VIRTUAL_ROBO_CLUSTER_CREATE_ASYNC_URI_FIELD_NUMBER: _ClassVar[int]
    CLOUD_CLUSTER_CREATE_ASYNC_URI_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_OPERATION_STATUS_URI_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_EXPAND_ASYNC_URI_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_UPGRADE_URI_V2_FIELD_NUMBER: _ClassVar[int]
    SPLIT_KEY_HOST_ACCESS_URI_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_UPGRADE_CHECK_RUN_TESTS_URI_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_UPGRADE_CHECK_SHOW_RESULTS_URI_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_FETCH_LATEST_ETCD_SNAPSHOT_NODE_IP_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_ETCD_SERVE_LATEST_SNAPSHOT_URI_FIELD_NUMBER: _ClassVar[int]
    GENERATE_SPLIT_KEY_TOKEN_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_DNS_UPDATE_URI_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_UPDATE_AIRGAP_CONFIG_FIELD_NUMBER: _ClassVar[int]
    NODE_NFS_SHARE_UNMOUNT_URI_FIELD_NUMBER: _ClassVar[int]
    NFS_SHARE_UPDATE_DATA_VIP_URI_FIELD_NUMBER: _ClassVar[int]
    FIREWALL_PROFILE_UPDATE_URI_FIELD_NUMBER: _ClassVar[int]
    SERVICE_IDENTITY_GLOBAL_ENABLE_URI_FIELD_NUMBER: _ClassVar[int]
    SERVICE_IDENTITY_DISABLED_PORTS_URI_FIELD_NUMBER: _ClassVar[int]
    SERVICE_IDENTITY_STATUS_URI_FIELD_NUMBER: _ClassVar[int]
    FIREWALL_PROFILE_REMOVE_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_FIRMWARE_INVENTORY_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_FIRMWARE_UPGRADE_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_SYNC_IMPORT_CRL_FILE_URI_FIELD_NUMBER: _ClassVar[int]
    NFS_SHARE_HANDLE_CHANGE_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_UPLOAD_PACKAGES_BY_URL_URI_FIELD_NUMBER: _ClassVar[int]
    UPGRADE_AND_PATCH_URI_FIELD_NUMBER: _ClassVar[int]
    UPLOAD_PACKAGE_AND_UPGRADE_PATCH_URI_FIELD_NUMBER: _ClassVar[int]
    UPGRADE_SPACE_CHECK_URI_FIELD_NUMBER: _ClassVar[int]
    NODE_POWER_OPERATION_URI_FIELD_NUMBER: _ClassVar[int]
    base_uri: str
    api_version: str
    cloud_cluster_create_uri: str
    cloud_cluster_add_nodes_uri: str
    cluster_destroy_uri: str
    cluster_start_uri: str
    cluster_stop_uri: str
    cluster_status_uri: str
    cluster_upgrade_uri: str
    cluster_list_packages_uri: str
    cluster_delete_packages_uri: str
    cluster_download_packages_uri: str
    cloud_node_join_cluster_uri: str
    node_disjoin_cluster_uri: str
    node_upgrade_uri: str
    node_package_uri: str
    node_upload_package_uri: str
    node_status_uri: str
    node_list_packages_uri: str
    node_delete_packages_uri: str
    node_stop_uri: str
    avahi_discover_nodes_uri: str
    cluster_update_gflags_uri: str
    cluster_list_gflags_uri: str
    cluster_config_update_uri: str
    cluster_remove_node_uri_deprecated: str
    cluster_has_new_packages_uri: str
    cluster_ack_new_packages_uri: str
    disk_mark_offline_uri: str
    disk_forget_uri: str
    disk_assimilate_uri: str
    cluster_bringup_uri: str
    cluster_expand_uri: str
    node_bringup_uri: str
    cluster_bringup_status_uri: str
    avahi_discover_all_nodes_uri: str
    node_check_upgradability_uri: str
    node_check_compatibility_uri: str
    node_hardware_info_uri: str
    cluster_list_network_interfaces_uri: str
    node_list_network_interfaces_uri: str
    cluster_update_network_interfaces_uri: str
    node_sync_upload_package_uri: str
    node_info_uri: str
    node_update_network_interfaces_uri: str
    node_update_routes_uri_deprecated: str
    cluster_restart_uri: str
    virtual_robo_cluster_create_uri: str
    cluster_tricorder_uri_deprecated: str
    fetch_node_level_tricorder_results_uri_deprecated: str
    cluster_ssh_key_upgrade_uri: str
    disk_extend_uri: str
    disk_discover_uri: str
    cluster_update_network_uri: str
    node_save_nexus_gflags_uri: str
    cluster_get_hosts_file_uri: str
    cluster_upload_hosts_file_uri: str
    cluster_list_platform_gflags_uri: str
    node_bringup_network_uri: str
    disk_identify_uri: str
    node_identify_uri: str
    node_raise_monitoring_alerts_uri: str
    firewall_list_uri: str
    firewall_update_uri: str
    route_add_uri: str
    route_show_uri: str
    route_delete_uri: str
    node_add_route_uri: str
    node_delete_route_uri: str
    ipmi_list_users_uri: str
    ipmi_get_lan_info_uri: str
    ipmi_get_fru_info_uri: str
    ipmi_get_sel_uri: str
    ipmi_get_sel_info_uri: str
    ipmi_get_sdr_info_uri: str
    ipmi_reset_bmc_uri: str
    ipmi_set_node_power_uri: str
    ntp_server_sync_uri: str
    bond_create_uri: str
    bond_delete_uri: str
    bond_update_uri: str
    ip_config_uri: str
    ip_unconfig_uri: str
    license_audit_uri: str
    license_upload_uri: str
    license_key_upload_uri: str
    account_usage_uri: str
    create_vm_uri: str
    list_vm_uri: str
    vm_status_uri: str
    vm_lcm_uri: str
    vm_delete_uri: str
    vm_list_internal_uri: str
    vm_launch_internal_uri: str
    vnc_access_uri: str
    vm_inventory_uri: str
    vm_status_internal_uri: str
    vm_lcm_internal_uri: str
    vm_delete_internal_uri: str
    vm_sched_uri: str
    vm_offline_migration_uri: str
    vmx_parse_uri: str
    interface_groups_list_uri: str
    interface_group_list_uri: str
    interface_group_create_uri: str
    interface_group_delete_uri: str
    interface_group_update_uri: str
    fetch_disk_space_details_uri: str
    is_account_classified_uri: str
    update_ipmi_user_uri: str
    update_ipmi_lan_info_uri: str
    license_expiry_date_uri: str
    vm_config_cleanup_uri: str
    cluster_services_state_uri: str
    node_services_state_uri: str
    reboot_proxy_vm_uri: str
    send_snmp_test_trap_uri: str
    license_cluster_claimed_uri: str
    axon_api_base_uri: str
    account_overusage_uri: str
    node_disk_discover_uri: str
    is_cluster_ready_uri: str
    update_linux_credentials_uri: str
    show_system_led_info_uri: str
    node_disk_assimilate_uri: str
    node_re_ip_uri: str
    interface_update_uri: str
    nodes_hostname_uri: str
    ipmi_cluster_list_users_uri: str
    ipmi_cluster_update_users_uri: str
    ipmi_cluster_get_lan_info_uri: str
    ipmi_cluster_update_lan_info_uri: str
    api_version2: str
    nodes_re_ip_uri: str
    node_ip_config_uri: str
    node_ip_unconfig_uri: str
    get_fru_data_uri: str
    set_fru_data_uri: str
    syslogs_uri: str
    syslogs_status_uri: str
    syslogs_audit_tags_uri: str
    syslogs_programnames_uri: str
    locate_fru_uri: str
    list_locate_fru_uri: str
    breakfix_api_base_uri: str
    list_fru_uri: str
    node_firewall_update_uri: str
    fru_qrp_uri: str
    chassis_uri: str
    racks_uri: str
    nfs_share_mount_uri: str
    security_support_user_token_uri: str
    security_support_user_sudo_access_uri: str
    node_nfs_share_mount_uri: str
    linux_command_execute_uri: str
    node_save_service_gflags_uri: str
    ssh_keys_md5sum_uri: str
    rigel_cluster_create_uri: str
    nfs_share_migrate_uri: str
    avahi_cluster_nodes_uri: str
    nodes_networking_reset_uri: str
    nodes_reset_state_uri: str
    cluster_reset_state_uri: str
    security_support_user_access_info_uri: str
    banner_uri: str
    update_banner_uri: str
    cluster_staging_info_uri: str
    nodes_staging_info_uri: str
    node_apply_service_gflags_uri: str
    node_disk_inventory_uri: str
    node_groups_list_uri: str
    node_group_list_uri: str
    node_group_create_uri: str
    node_group_delete_uri: str
    node_group_update_uri: str
    market_place_enable_uri: str
    rigel_update_node_network_uri: str
    remote_storage_purefb_register_uri: str
    remote_storage_purefb_fetch_details_uri: str
    nfs_share_configure_uri: str
    nodes_power_uri: str
    bifrost_ipam_allocate_networking_uri: str
    bifrost_ipam_release_networking_uri: str
    nfs_share_list_uri: str
    nfs_share_rebalance_uri: str
    remote_storage_purefb_monitor_uri: str
    sysctl_conf_uri: str
    cluster_install_package_uri: str
    cluster_remove_package_uri: str
    cluster_list_package_uri: str
    node_create_csr_uri: str
    system_app_status_uri: str
    node_import_signed_csr_uri: str
    cluster_update_package_enable_uri: str
    cluster_update_package_disable_uri: str
    cluster_update_package_list_uri: str
    yum_repo_add_uri: str
    yum_repo_enable_uri: str
    yum_repo_remove_uri: str
    yum_repos_list_uri: str
    custom_baseos_enable_uri: str
    custom_baseos_disable_uri: str
    custom_baseos_status_uri: str
    yum_repo_set_option_uri: str
    rigel_connectivity_check_uri: str
    linux_command_list_uri: str
    qos_list_uri: str
    qos_update_uri: str
    node_qos_update_uri: str
    support_user_put_2FA_uri: str
    support_user_get_2FA_uri: str
    he_onprem_update_network_uri: str
    node_get_csr_and_public_key_uri: str
    node_post_server_and_ca_cert_uri: str
    cluster_toggle_protorpc_encryption_uri: str
    send_alerts_uri: str
    nfs_share_create_snapshot_uri: str
    node_validate_sed_uri: str
    cluster_update_hardware_encryption_uri: str
    customer_managed_baseos_status_uri: str
    customer_managed_baseos_enable_uri: str
    customer_managed_baseos_disable_uri: str
    cluster_list_snapshot_uri: str
    cluster_create_snapshot_uri: str
    cluster_restore_snapshot_uri: str
    node_create_snapshot_uri: str
    node_restore_snapshot_uri: str
    create_snapshot_status_uri: str
    restore_snapshot_status_uri: str
    secure_shell_uri: str
    node_secure_shell_uri: str
    node_aggregate_uri: str
    node_disaggregate_uri: str
    cloud_cluster_add_nodes_async_uri: str
    cluster_bringup_async_uri: str
    virtual_robo_cluster_create_async_uri: str
    cloud_cluster_create_async_uri: str
    cluster_operation_status_uri: str
    cluster_expand_async_uri: str
    cluster_upgrade_uri_v2: str
    split_key_host_access_uri: str
    cluster_upgrade_check_run_tests_uri: str
    cluster_upgrade_check_show_results_uri: str
    cluster_fetch_latest_etcd_snapshot_node_ip_uri: str
    node_etcd_serve_latest_snapshot_uri: str
    generate_split_key_token_uri: str
    node_dns_update_uri: str
    cluster_update_airgap_config: str
    node_nfs_share_unmount_uri: str
    nfs_share_update_data_vip_uri: str
    firewall_profile_update_uri: str
    service_identity_global_enable_uri: str
    service_identity_disabled_ports_uri: str
    service_identity_status_uri: str
    firewall_profile_remove_uri: str
    node_firmware_inventory_uri: str
    node_firmware_upgrade_uri: str
    node_sync_import_crl_file_uri: str
    nfs_share_handle_change_uri: str
    node_upload_packages_by_url_uri: str
    upgrade_and_patch_uri: str
    upload_package_and_upgrade_patch_uri: str
    upgrade_space_check_uri: str
    node_power_operation_uri: str
    def __init__(self, base_uri: _Optional[str] = ..., api_version: _Optional[str] = ..., cloud_cluster_create_uri: _Optional[str] = ..., cloud_cluster_add_nodes_uri: _Optional[str] = ..., cluster_destroy_uri: _Optional[str] = ..., cluster_start_uri: _Optional[str] = ..., cluster_stop_uri: _Optional[str] = ..., cluster_status_uri: _Optional[str] = ..., cluster_upgrade_uri: _Optional[str] = ..., cluster_list_packages_uri: _Optional[str] = ..., cluster_delete_packages_uri: _Optional[str] = ..., cluster_download_packages_uri: _Optional[str] = ..., cloud_node_join_cluster_uri: _Optional[str] = ..., node_disjoin_cluster_uri: _Optional[str] = ..., node_upgrade_uri: _Optional[str] = ..., node_package_uri: _Optional[str] = ..., node_upload_package_uri: _Optional[str] = ..., node_status_uri: _Optional[str] = ..., node_list_packages_uri: _Optional[str] = ..., node_delete_packages_uri: _Optional[str] = ..., node_stop_uri: _Optional[str] = ..., avahi_discover_nodes_uri: _Optional[str] = ..., cluster_update_gflags_uri: _Optional[str] = ..., cluster_list_gflags_uri: _Optional[str] = ..., cluster_config_update_uri: _Optional[str] = ..., cluster_remove_node_uri_deprecated: _Optional[str] = ..., cluster_has_new_packages_uri: _Optional[str] = ..., cluster_ack_new_packages_uri: _Optional[str] = ..., disk_mark_offline_uri: _Optional[str] = ..., disk_forget_uri: _Optional[str] = ..., disk_assimilate_uri: _Optional[str] = ..., cluster_bringup_uri: _Optional[str] = ..., cluster_expand_uri: _Optional[str] = ..., node_bringup_uri: _Optional[str] = ..., cluster_bringup_status_uri: _Optional[str] = ..., avahi_discover_all_nodes_uri: _Optional[str] = ..., node_check_upgradability_uri: _Optional[str] = ..., node_check_compatibility_uri: _Optional[str] = ..., node_hardware_info_uri: _Optional[str] = ..., cluster_list_network_interfaces_uri: _Optional[str] = ..., node_list_network_interfaces_uri: _Optional[str] = ..., cluster_update_network_interfaces_uri: _Optional[str] = ..., node_sync_upload_package_uri: _Optional[str] = ..., node_info_uri: _Optional[str] = ..., node_update_network_interfaces_uri: _Optional[str] = ..., node_update_routes_uri_deprecated: _Optional[str] = ..., cluster_restart_uri: _Optional[str] = ..., virtual_robo_cluster_create_uri: _Optional[str] = ..., cluster_tricorder_uri_deprecated: _Optional[str] = ..., fetch_node_level_tricorder_results_uri_deprecated: _Optional[str] = ..., cluster_ssh_key_upgrade_uri: _Optional[str] = ..., disk_extend_uri: _Optional[str] = ..., disk_discover_uri: _Optional[str] = ..., cluster_update_network_uri: _Optional[str] = ..., node_save_nexus_gflags_uri: _Optional[str] = ..., cluster_get_hosts_file_uri: _Optional[str] = ..., cluster_upload_hosts_file_uri: _Optional[str] = ..., cluster_list_platform_gflags_uri: _Optional[str] = ..., node_bringup_network_uri: _Optional[str] = ..., disk_identify_uri: _Optional[str] = ..., node_identify_uri: _Optional[str] = ..., node_raise_monitoring_alerts_uri: _Optional[str] = ..., firewall_list_uri: _Optional[str] = ..., firewall_update_uri: _Optional[str] = ..., route_add_uri: _Optional[str] = ..., route_show_uri: _Optional[str] = ..., route_delete_uri: _Optional[str] = ..., node_add_route_uri: _Optional[str] = ..., node_delete_route_uri: _Optional[str] = ..., ipmi_list_users_uri: _Optional[str] = ..., ipmi_get_lan_info_uri: _Optional[str] = ..., ipmi_get_fru_info_uri: _Optional[str] = ..., ipmi_get_sel_uri: _Optional[str] = ..., ipmi_get_sel_info_uri: _Optional[str] = ..., ipmi_get_sdr_info_uri: _Optional[str] = ..., ipmi_reset_bmc_uri: _Optional[str] = ..., ipmi_set_node_power_uri: _Optional[str] = ..., ntp_server_sync_uri: _Optional[str] = ..., bond_create_uri: _Optional[str] = ..., bond_delete_uri: _Optional[str] = ..., bond_update_uri: _Optional[str] = ..., ip_config_uri: _Optional[str] = ..., ip_unconfig_uri: _Optional[str] = ..., license_audit_uri: _Optional[str] = ..., license_upload_uri: _Optional[str] = ..., license_key_upload_uri: _Optional[str] = ..., account_usage_uri: _Optional[str] = ..., create_vm_uri: _Optional[str] = ..., list_vm_uri: _Optional[str] = ..., vm_status_uri: _Optional[str] = ..., vm_lcm_uri: _Optional[str] = ..., vm_delete_uri: _Optional[str] = ..., vm_list_internal_uri: _Optional[str] = ..., vm_launch_internal_uri: _Optional[str] = ..., vnc_access_uri: _Optional[str] = ..., vm_inventory_uri: _Optional[str] = ..., vm_status_internal_uri: _Optional[str] = ..., vm_lcm_internal_uri: _Optional[str] = ..., vm_delete_internal_uri: _Optional[str] = ..., vm_sched_uri: _Optional[str] = ..., vm_offline_migration_uri: _Optional[str] = ..., vmx_parse_uri: _Optional[str] = ..., interface_groups_list_uri: _Optional[str] = ..., interface_group_list_uri: _Optional[str] = ..., interface_group_create_uri: _Optional[str] = ..., interface_group_delete_uri: _Optional[str] = ..., interface_group_update_uri: _Optional[str] = ..., fetch_disk_space_details_uri: _Optional[str] = ..., is_account_classified_uri: _Optional[str] = ..., update_ipmi_user_uri: _Optional[str] = ..., update_ipmi_lan_info_uri: _Optional[str] = ..., license_expiry_date_uri: _Optional[str] = ..., vm_config_cleanup_uri: _Optional[str] = ..., cluster_services_state_uri: _Optional[str] = ..., node_services_state_uri: _Optional[str] = ..., reboot_proxy_vm_uri: _Optional[str] = ..., send_snmp_test_trap_uri: _Optional[str] = ..., license_cluster_claimed_uri: _Optional[str] = ..., axon_api_base_uri: _Optional[str] = ..., account_overusage_uri: _Optional[str] = ..., node_disk_discover_uri: _Optional[str] = ..., is_cluster_ready_uri: _Optional[str] = ..., update_linux_credentials_uri: _Optional[str] = ..., show_system_led_info_uri: _Optional[str] = ..., node_disk_assimilate_uri: _Optional[str] = ..., node_re_ip_uri: _Optional[str] = ..., interface_update_uri: _Optional[str] = ..., nodes_hostname_uri: _Optional[str] = ..., ipmi_cluster_list_users_uri: _Optional[str] = ..., ipmi_cluster_update_users_uri: _Optional[str] = ..., ipmi_cluster_get_lan_info_uri: _Optional[str] = ..., ipmi_cluster_update_lan_info_uri: _Optional[str] = ..., api_version2: _Optional[str] = ..., nodes_re_ip_uri: _Optional[str] = ..., node_ip_config_uri: _Optional[str] = ..., node_ip_unconfig_uri: _Optional[str] = ..., get_fru_data_uri: _Optional[str] = ..., set_fru_data_uri: _Optional[str] = ..., syslogs_uri: _Optional[str] = ..., syslogs_status_uri: _Optional[str] = ..., syslogs_audit_tags_uri: _Optional[str] = ..., syslogs_programnames_uri: _Optional[str] = ..., locate_fru_uri: _Optional[str] = ..., list_locate_fru_uri: _Optional[str] = ..., breakfix_api_base_uri: _Optional[str] = ..., list_fru_uri: _Optional[str] = ..., node_firewall_update_uri: _Optional[str] = ..., fru_qrp_uri: _Optional[str] = ..., chassis_uri: _Optional[str] = ..., racks_uri: _Optional[str] = ..., nfs_share_mount_uri: _Optional[str] = ..., security_support_user_token_uri: _Optional[str] = ..., security_support_user_sudo_access_uri: _Optional[str] = ..., node_nfs_share_mount_uri: _Optional[str] = ..., linux_command_execute_uri: _Optional[str] = ..., node_save_service_gflags_uri: _Optional[str] = ..., ssh_keys_md5sum_uri: _Optional[str] = ..., rigel_cluster_create_uri: _Optional[str] = ..., nfs_share_migrate_uri: _Optional[str] = ..., avahi_cluster_nodes_uri: _Optional[str] = ..., nodes_networking_reset_uri: _Optional[str] = ..., nodes_reset_state_uri: _Optional[str] = ..., cluster_reset_state_uri: _Optional[str] = ..., security_support_user_access_info_uri: _Optional[str] = ..., banner_uri: _Optional[str] = ..., update_banner_uri: _Optional[str] = ..., cluster_staging_info_uri: _Optional[str] = ..., nodes_staging_info_uri: _Optional[str] = ..., node_apply_service_gflags_uri: _Optional[str] = ..., node_disk_inventory_uri: _Optional[str] = ..., node_groups_list_uri: _Optional[str] = ..., node_group_list_uri: _Optional[str] = ..., node_group_create_uri: _Optional[str] = ..., node_group_delete_uri: _Optional[str] = ..., node_group_update_uri: _Optional[str] = ..., market_place_enable_uri: _Optional[str] = ..., rigel_update_node_network_uri: _Optional[str] = ..., remote_storage_purefb_register_uri: _Optional[str] = ..., remote_storage_purefb_fetch_details_uri: _Optional[str] = ..., nfs_share_configure_uri: _Optional[str] = ..., nodes_power_uri: _Optional[str] = ..., bifrost_ipam_allocate_networking_uri: _Optional[str] = ..., bifrost_ipam_release_networking_uri: _Optional[str] = ..., nfs_share_list_uri: _Optional[str] = ..., nfs_share_rebalance_uri: _Optional[str] = ..., remote_storage_purefb_monitor_uri: _Optional[str] = ..., sysctl_conf_uri: _Optional[str] = ..., cluster_install_package_uri: _Optional[str] = ..., cluster_remove_package_uri: _Optional[str] = ..., cluster_list_package_uri: _Optional[str] = ..., node_create_csr_uri: _Optional[str] = ..., system_app_status_uri: _Optional[str] = ..., node_import_signed_csr_uri: _Optional[str] = ..., cluster_update_package_enable_uri: _Optional[str] = ..., cluster_update_package_disable_uri: _Optional[str] = ..., cluster_update_package_list_uri: _Optional[str] = ..., yum_repo_add_uri: _Optional[str] = ..., yum_repo_enable_uri: _Optional[str] = ..., yum_repo_remove_uri: _Optional[str] = ..., yum_repos_list_uri: _Optional[str] = ..., custom_baseos_enable_uri: _Optional[str] = ..., custom_baseos_disable_uri: _Optional[str] = ..., custom_baseos_status_uri: _Optional[str] = ..., yum_repo_set_option_uri: _Optional[str] = ..., rigel_connectivity_check_uri: _Optional[str] = ..., linux_command_list_uri: _Optional[str] = ..., qos_list_uri: _Optional[str] = ..., qos_update_uri: _Optional[str] = ..., node_qos_update_uri: _Optional[str] = ..., support_user_put_2FA_uri: _Optional[str] = ..., support_user_get_2FA_uri: _Optional[str] = ..., he_onprem_update_network_uri: _Optional[str] = ..., node_get_csr_and_public_key_uri: _Optional[str] = ..., node_post_server_and_ca_cert_uri: _Optional[str] = ..., cluster_toggle_protorpc_encryption_uri: _Optional[str] = ..., send_alerts_uri: _Optional[str] = ..., nfs_share_create_snapshot_uri: _Optional[str] = ..., node_validate_sed_uri: _Optional[str] = ..., cluster_update_hardware_encryption_uri: _Optional[str] = ..., customer_managed_baseos_status_uri: _Optional[str] = ..., customer_managed_baseos_enable_uri: _Optional[str] = ..., customer_managed_baseos_disable_uri: _Optional[str] = ..., cluster_list_snapshot_uri: _Optional[str] = ..., cluster_create_snapshot_uri: _Optional[str] = ..., cluster_restore_snapshot_uri: _Optional[str] = ..., node_create_snapshot_uri: _Optional[str] = ..., node_restore_snapshot_uri: _Optional[str] = ..., create_snapshot_status_uri: _Optional[str] = ..., restore_snapshot_status_uri: _Optional[str] = ..., secure_shell_uri: _Optional[str] = ..., node_secure_shell_uri: _Optional[str] = ..., node_aggregate_uri: _Optional[str] = ..., node_disaggregate_uri: _Optional[str] = ..., cloud_cluster_add_nodes_async_uri: _Optional[str] = ..., cluster_bringup_async_uri: _Optional[str] = ..., virtual_robo_cluster_create_async_uri: _Optional[str] = ..., cloud_cluster_create_async_uri: _Optional[str] = ..., cluster_operation_status_uri: _Optional[str] = ..., cluster_expand_async_uri: _Optional[str] = ..., cluster_upgrade_uri_v2: _Optional[str] = ..., split_key_host_access_uri: _Optional[str] = ..., cluster_upgrade_check_run_tests_uri: _Optional[str] = ..., cluster_upgrade_check_show_results_uri: _Optional[str] = ..., cluster_fetch_latest_etcd_snapshot_node_ip_uri: _Optional[str] = ..., node_etcd_serve_latest_snapshot_uri: _Optional[str] = ..., generate_split_key_token_uri: _Optional[str] = ..., node_dns_update_uri: _Optional[str] = ..., cluster_update_airgap_config: _Optional[str] = ..., node_nfs_share_unmount_uri: _Optional[str] = ..., nfs_share_update_data_vip_uri: _Optional[str] = ..., firewall_profile_update_uri: _Optional[str] = ..., service_identity_global_enable_uri: _Optional[str] = ..., service_identity_disabled_ports_uri: _Optional[str] = ..., service_identity_status_uri: _Optional[str] = ..., firewall_profile_remove_uri: _Optional[str] = ..., node_firmware_inventory_uri: _Optional[str] = ..., node_firmware_upgrade_uri: _Optional[str] = ..., node_sync_import_crl_file_uri: _Optional[str] = ..., nfs_share_handle_change_uri: _Optional[str] = ..., node_upload_packages_by_url_uri: _Optional[str] = ..., upgrade_and_patch_uri: _Optional[str] = ..., upload_package_and_upgrade_patch_uri: _Optional[str] = ..., upgrade_space_check_uri: _Optional[str] = ..., node_power_operation_uri: _Optional[str] = ...) -> None: ...
