# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apollo/mr/algorithms/chunk_repo_metadata_gc/chunk_repo_metadata_gc.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from configs import cluster_config_pb2 as configs_dot_cluster__config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nHapollo/mr/algorithms/chunk_repo_metadata_gc/chunk_repo_metadata_gc.proto\x12\x1d\x63ohesity.apollo.mr.algorithms\x1a\x1c\x63onfigs/cluster_config.proto\"i\n#ChunkRepoMetadataGCContextDataProto\x12\x42\n\x14\x63luster_config_proto\x18\x01 \x01(\x0b\x32$.cohesity.configs.ClusterConfigProto')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'apollo.mr.algorithms.chunk_repo_metadata_gc.chunk_repo_metadata_gc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHUNKREPOMETADATAGCCONTEXTDATAPROTO']._serialized_start=137
  _globals['_CHUNKREPOMETADATAGCCONTEXTDATAPROTO']._serialized_end=242
# @@protoc_insertion_point(module_scope)
