# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yoda/es/test/json_test_protos.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from yoda.es import jsonname_pb2 as yoda_dot_es_dot_jsonname__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#yoda/es/test/json_test_protos.proto\x12\x15\x63ohesity.yoda.es.test\x1a\x16yoda/es/jsonname.proto\"i\n\tFlatProto\x12\x11\n\topt_int32\x18\x01 \x01(\x05\x12\x11\n\topt_int64\x18\x02 \x01(\x03\x12\x12\n\nopt_double\x18\x03 \x01(\x01\x12\x11\n\topt_float\x18\x04 \x01(\x02\x12\x0f\n\x07opt_str\x18\x05 \x01(\t\".\n\nArrayProto\x12\x0f\n\x07rep_int\x18\x01 \x03(\x05\x12\x0f\n\x07rep_str\x18\x02 \x03(\t\"\xa9\x01\n\x0bNestedProto\x12\x31\n\x07opt_msg\x18\x01 \x01(\x0b\x32 .cohesity.yoda.es.test.FlatProto\x12\x31\n\x07rep_msg\x18\x02 \x03(\x0b\x32 .cohesity.yoda.es.test.FlatProto\x12\x34\n\trep_array\x18\x03 \x03(\x0b\x32!.cohesity.yoda.es.test.ArrayProto\"*\n\x0cRenamedProto\x12\x1a\n\x06\x64\x65lete\x18\x01 \x01(\x05\x42\n\x92\xb5\x18\x06\x64\x65lete\"4\n\x14MapEntryStringString\x12\x0c\n\x04_key\x18\x01 \x01(\t\x12\x0e\n\x06_value\x18\x02 \x01(\t\"[\n\x0cMapTestProto\x12K\n\tterm_maps\x18\x01 \x03(\x0b\x32+.cohesity.yoda.es.test.MapEntryStringStringB\x0b\x92\xb5\x18\x03map\x98\xb5\x18\x01\"2\n\nBytesProto\x12\x11\n\topt_bytes\x18\x01 \x01(\x0c\x12\x11\n\trep_bytes\x18\x02 \x03(\x0c\"5\n\x0bStringProto\x12\x12\n\nopt_string\x18\x01 \x01(\t\x12\x12\n\nrep_string\x18\x02 \x03(\t\"[\n\x1aNumericRangeQueryTestProto\x12=\n\x05range\x18\x01 \x03(\x0b\x32(.cohesity.yoda.es.test.MapEntryStringMapB\x04\x98\xb5\x18\x01\"a\n\x11MapEntryStringMap\x12\x0c\n\x04_key\x18\x01 \x01(\t\x12>\n\x06_value\x18\x02 \x03(\x0b\x32(.cohesity.yoda.es.test.MapEntryStringIntB\x04\x98\xb5\x18\x01\"1\n\x11MapEntryStringInt\x12\x0c\n\x04_key\x18\x01 \x01(\t\x12\x0e\n\x06_value\x18\x02 \x01(\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'yoda.es.test.json_test_protos_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RENAMEDPROTO'].fields_by_name['delete']._loaded_options = None
  _globals['_RENAMEDPROTO'].fields_by_name['delete']._serialized_options = b'\222\265\030\006delete'
  _globals['_MAPTESTPROTO'].fields_by_name['term_maps']._loaded_options = None
  _globals['_MAPTESTPROTO'].fields_by_name['term_maps']._serialized_options = b'\222\265\030\003map\230\265\030\001'
  _globals['_NUMERICRANGEQUERYTESTPROTO'].fields_by_name['range']._loaded_options = None
  _globals['_NUMERICRANGEQUERYTESTPROTO'].fields_by_name['range']._serialized_options = b'\230\265\030\001'
  _globals['_MAPENTRYSTRINGMAP'].fields_by_name['_value']._loaded_options = None
  _globals['_MAPENTRYSTRINGMAP'].fields_by_name['_value']._serialized_options = b'\230\265\030\001'
  _globals['_FLATPROTO']._serialized_start=86
  _globals['_FLATPROTO']._serialized_end=191
  _globals['_ARRAYPROTO']._serialized_start=193
  _globals['_ARRAYPROTO']._serialized_end=239
  _globals['_NESTEDPROTO']._serialized_start=242
  _globals['_NESTEDPROTO']._serialized_end=411
  _globals['_RENAMEDPROTO']._serialized_start=413
  _globals['_RENAMEDPROTO']._serialized_end=455
  _globals['_MAPENTRYSTRINGSTRING']._serialized_start=457
  _globals['_MAPENTRYSTRINGSTRING']._serialized_end=509
  _globals['_MAPTESTPROTO']._serialized_start=511
  _globals['_MAPTESTPROTO']._serialized_end=602
  _globals['_BYTESPROTO']._serialized_start=604
  _globals['_BYTESPROTO']._serialized_end=654
  _globals['_STRINGPROTO']._serialized_start=656
  _globals['_STRINGPROTO']._serialized_end=709
  _globals['_NUMERICRANGEQUERYTESTPROTO']._serialized_start=711
  _globals['_NUMERICRANGEQUERYTESTPROTO']._serialized_end=802
  _globals['_MAPENTRYSTRINGMAP']._serialized_start=804
  _globals['_MAPENTRYSTRINGMAP']._serialized_end=901
  _globals['_MAPENTRYSTRINGINT']._serialized_start=903
  _globals['_MAPENTRYSTRINGINT']._serialized_end=952
# @@protoc_insertion_point(module_scope)
