# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: helios/bookkeeper/base/base.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!helios/bookkeeper/base/base.proto\x12\x17\x63ohesity.helios.bk.base\"\xd1\x03\n\x13\x42ookkeeperUrisProto\x12#\n\x0fkub_bk_hostname\x18\x01 \x01(\t:\nbookkeeper\x12\x18\n\x0b\x61pi_version\x18\x02 \x01(\t:\x03/v1\x12\x17\n\x08\x62\x61se_uri\x18\x03 \x01(\t:\x05/base\x12\x1b\n\nstatus_uri\x18\x04 \x01(\t:\x07/status\x12\"\n\x0e\x63opy_tasks_uri\x18\x05 \x01(\t:\n/copytasks\x12 \n\rpg_status_uri\x18\x06 \x01(\t:\t/postgres\x12\x1a\n\res_status_uri\x18\x07 \x01(\t:\x03/es\x12\x1a\n\rbk_status_uri\x18\x08 \x01(\t:\x03/bk\x12 \n\x10kafka_status_uri\x18\t \x01(\t:\x06/kafka\x12#\n\x0cgflag_config\x18\n \x01(\t:\r/config/gflag\x12\x1f\n\napp_health\x18\x0b \x01(\t:\x0b/app/health\x12\x35\n\x17\x64\x65\x62ug_info_describe_pod\x18\x0c \x01(\t:\x14/debug/pods/describe\x12(\n\x11\x64\x65\x62ug_info_gflags\x18\r \x01(\t:\r/debug/gflags*0\n\x0c\x42kClientType\x12\t\n\x05kRest\x10\x01\x12\t\n\x05kGrpc\x10\x02\x12\n\n\x06kRedis\x10\x03\x42 Z\x1ehelios/bookkeeper/base/base.pb')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'helios.bookkeeper.base.base_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\036helios/bookkeeper/base/base.pb'
  _globals['_BKCLIENTTYPE']._serialized_start=530
  _globals['_BKCLIENTTYPE']._serialized_end=578
  _globals['_BOOKKEEPERURISPROTO']._serialized_start=63
  _globals['_BOOKKEEPERURISPROTO']._serialized_end=528
# @@protoc_insertion_point(module_scope)
