# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: experimental/akarsh/rpc/remote_fs.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from open_util.net import protorpc_pb2 as open__util_dot_net_dot_protorpc__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'experimental/akarsh/rpc/remote_fs.proto\x12 cohesity.experimental.akarsh.rpc\x1a\x1copen_util/net/protorpc.proto\"\x18\n\x08\x46ileName\x12\x0c\n\x04name\x18\x01 \x02(\t\"C\n\x08IOParams\x12\x11\n\tfile_name\x18\x01 \x02(\t\x12\x14\n\x0cnum_of_bytes\x18\x02 \x02(\x05\x12\x0e\n\x06offset\x18\x03 \x02(\x05\"6\n\x08Response\x12\x10\n\x08response\x18\x01 \x02(\t\x12\x18\n\x10\x65xecution_number\x18\x02 \x02(\x05\x32\xd6\x02\n\x10RemoteFileSystem\x12\x66\n\nCreateFile\x12*.cohesity.experimental.akarsh.rpc.FileName\x1a*.cohesity.experimental.akarsh.rpc.Response\"\x00\x12\x64\n\x08ReadFile\x12*.cohesity.experimental.akarsh.rpc.IOParams\x1a*.cohesity.experimental.akarsh.rpc.Response\"\x00\x12\x65\n\tWriteFile\x12*.cohesity.experimental.akarsh.rpc.IOParams\x1a*.cohesity.experimental.akarsh.rpc.Response\"\x00\x1a\r\x80\xf1\x04\xe8\x07\x88\xf1\x04\x01\x90\xf1\x04\x02\x42\x03\x80\x01\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'experimental.akarsh.rpc.remote_fs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\200\001\001'
  _globals['_REMOTEFILESYSTEM']._loaded_options = None
  _globals['_REMOTEFILESYSTEM']._serialized_options = b'\200\361\004\350\007\210\361\004\001\220\361\004\002'
  _globals['_FILENAME']._serialized_start=107
  _globals['_FILENAME']._serialized_end=131
  _globals['_IOPARAMS']._serialized_start=133
  _globals['_IOPARAMS']._serialized_end=200
  _globals['_RESPONSE']._serialized_start=202
  _globals['_RESPONSE']._serialized_end=256
  _globals['_REMOTEFILESYSTEM']._serialized_start=259
  _globals['_REMOTEFILESYSTEM']._serialized_end=601
# @@protoc_insertion_point(module_scope)
