# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bridge/nas_dr_orchestrator/grpc_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bridge.nas_dr_orchestrator import nas_dr_pb2 as bridge_dot_nas__dr__orchestrator_dot_nas__dr__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-bridge/nas_dr_orchestrator/grpc_service.proto\x12#cohesity.bridge.nas_dr_orchestrator\x1a\'bridge/nas_dr_orchestrator/nas_dr.proto2\xf9\x05\n\x0bGRpcService\x12\x91\x01\n\x12PerformDROperation\x12:.cohesity.bridge.nas_dr_orchestrator.PerformDROperationArg\x1a=.cohesity.bridge.nas_dr_orchestrator.PerformDROperationResult\"\x00\x12\x9a\x01\n\x15GetAllowedFailoverOps\x12=.cohesity.bridge.nas_dr_orchestrator.GetAllowedFailoverOpsArg\x1a@.cohesity.bridge.nas_dr_orchestrator.GetAllowedFailoverOpsResult\"\x00\x12|\n\x0bGetDRStatus\x12\x33.cohesity.bridge.nas_dr_orchestrator.GetDRStatusArg\x1a\x36.cohesity.bridge.nas_dr_orchestrator.GetDRStatusResult\"\x00\x12\xa9\x01\n\x1aLookupOrUpdateTrackingView\x12\x42.cohesity.bridge.nas_dr_orchestrator.LookupOrUpdateTrackingViewArg\x1a\x45.cohesity.bridge.nas_dr_orchestrator.LookupOrUpdateTrackingViewResult\"\x00\x12\x8e\x01\n\x11GetTrackingViewId\x12\x39.cohesity.bridge.nas_dr_orchestrator.GetTrackingViewIdArg\x1a<.cohesity.bridge.nas_dr_orchestrator.GetTrackingViewIdResult\"\x00\x42(Z#cohesity/bridge/nas_dr_orchestrator\x80\x01\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bridge.nas_dr_orchestrator.grpc_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z#cohesity/bridge/nas_dr_orchestrator\200\001\000'
  _globals['_GRPCSERVICE']._serialized_start=128
  _globals['_GRPCSERVICE']._serialized_end=889
# @@protoc_insertion_point(module_scope)
