# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: experimental/dixit/ex/fs_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from open_util.net import protorpc_pb2 as open__util_dot_net_dot_protorpc__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&experimental/dixit/ex/fs_service.proto\x12\x1e\x63ohesity.experimental.dixit.ex\x1a\x1copen_util/net/protorpc.proto\"\x1d\n\rCreateFileReq\x12\x0c\n\x04name\x18\x01 \x02(\t\"-\n\x0e\x43reateFileResp\x12\x0e\n\x06status\x18\x01 \x02(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\t\";\n\x0bReadFileReq\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06offset\x18\x02 \x01(\x03\x12\x0e\n\x06length\x18\x03 \x01(\x03\".\n\x0cReadFileResp\x12\x0e\n\x06status\x18\x01 \x02(\x08\x12\x0e\n\x06\x62uffer\x18\x02 \x01(\t\"L\n\x0cWriteFileReq\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0e\n\x06offset\x18\x02 \x02(\x03\x12\x0e\n\x06length\x18\x03 \x02(\x03\x12\x0e\n\x06\x62uffer\x18\x04 \x02(\t\",\n\rWriteFileResp\x12\x0e\n\x06status\x18\x01 \x02(\x08\x12\x0b\n\x03msg\x18\x02 \x01(\t2\xde\x02\n\tFSService\x12m\n\nCreateFile\x12-.cohesity.experimental.dixit.ex.CreateFileReq\x1a..cohesity.experimental.dixit.ex.CreateFileResp\"\x00\x12g\n\x08ReadFile\x12+.cohesity.experimental.dixit.ex.ReadFileReq\x1a,.cohesity.experimental.dixit.ex.ReadFileResp\"\x00\x12j\n\tWriteFile\x12,.cohesity.experimental.dixit.ex.WriteFileReq\x1a-.cohesity.experimental.dixit.ex.WriteFileResp\"\x00\x1a\r\x80\xf1\x04\x88\'\x88\xf1\x04\x01\x90\xf1\x04\x03\x42\x03\x80\x01\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'experimental.dixit.ex.fs_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\200\001\001'
  _globals['_FSSERVICE']._loaded_options = None
  _globals['_FSSERVICE']._serialized_options = b'\200\361\004\210\'\210\361\004\001\220\361\004\003'
  _globals['_CREATEFILEREQ']._serialized_start=104
  _globals['_CREATEFILEREQ']._serialized_end=133
  _globals['_CREATEFILERESP']._serialized_start=135
  _globals['_CREATEFILERESP']._serialized_end=180
  _globals['_READFILEREQ']._serialized_start=182
  _globals['_READFILEREQ']._serialized_end=241
  _globals['_READFILERESP']._serialized_start=243
  _globals['_READFILERESP']._serialized_end=289
  _globals['_WRITEFILEREQ']._serialized_start=291
  _globals['_WRITEFILEREQ']._serialized_end=367
  _globals['_WRITEFILERESP']._serialized_start=369
  _globals['_WRITEFILERESP']._serialized_end=413
  _globals['_FSSERVICE']._serialized_start=416
  _globals['_FSSERVICE']._serialized_end=766
# @@protoc_insertion_point(module_scope)
