# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: magneto/slave/stub/file_stub.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from magneto.master.base import master_pb2 as magneto_dot_master_dot_base_dot_master__pb2
from magneto.slave.stub import stub_pb2 as magneto_dot_slave_dot_stub_dot_stub__pb2
from magneto.slave.stub import bridge_updates_pb2 as magneto_dot_slave_dot_stub_dot_bridge__updates__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"magneto/slave/stub/file_stub.proto\x12 cohesity.magneto.slave.stub.file\x1a magneto/master/base/master.proto\x1a\x1dmagneto/slave/stub/stub.proto\x1a\'magneto/slave/stub/bridge_updates.proto\"g\n\x18\x42\x61\x63kupWorkUnitsUpdateArg\x12K\n\x11\x62\x61\x63kup_update_vec\x18\x01 \x03(\x0b\x32\x30.cohesity.magneto.slave.stub.BackupDiskUpdateArg\"j\n\x19RestoreWorkUnitsUpdateArg\x12M\n\x12restore_update_vec\x18\x01 \x03(\x0b\x32\x31.cohesity.magneto.slave.stub.RestoreDiskUpdateArg\"\xef\x04\n\x13\x46ileActionUpdateArg\x12H\n\x04type\x18\x01 \x01(\x0e\x32:.cohesity.magneto.slave.stub.file.FileActionUpdateArg.Type\x12`\n\x1c\x62\x61\x63kup_work_units_update_arg\x18\x02 \x01(\x0b\x32:.cohesity.magneto.slave.stub.file.BackupWorkUnitsUpdateArg\x12\x62\n\x1drestore_work_units_update_arg\x18\x03 \x01(\x0b\x32;.cohesity.magneto.slave.stub.file.RestoreWorkUnitsUpdateArg\"\xc1\x01\n\x04Type\x12\x18\n\x14kPrepareBackupUpdate\x10\x01\x12\x1a\n\x16kBackupWorkUnitsUpdate\x10\x02\x12\x1b\n\x17kEndBackupSubTaskUpdate\x10\x03\x12\x14\n\x10kEndBackupUpdate\x10\x04\x12\x1b\n\x17kRestoreWorkUnitsUpdate\x10\x05\x12\x1c\n\x18kEndRestoreSubTaskUpdate\x10\x06\x12\x15\n\x11kEndRestoreUpdate\x10\x07\x32\x83\x01\n\x16\x66ile_action_update_arg\x12,.cohesity.magneto.slave.stub.ActionUpdateArg\x18j \x01(\x0b\x32\x35.cohesity.magneto.slave.stub.file.FileActionUpdateArg\"\x83\x02\n\x17\x46ileStartRestoreTaskArg\x12\x1b\n\x0cmount_volume\x18\x01 \x01(\x08:\x05\x66\x61lse\x12\x38\n\x0bview_params\x18\x02 \x01(\x0b\x32#.cohesity.magneto.master.ViewParams2\x90\x01\n\x1b\x66ile_start_restore_task_arg\x12\x30.cohesity.magneto.slave.stub.StartRestoreTaskArg\x18\x66 \x01(\x0b\x32\x39.cohesity.magneto.slave.stub.file.FileStartRestoreTaskArg')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'magneto.slave.stub.file_stub_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BACKUPWORKUNITSUPDATEARG']._serialized_start=178
  _globals['_BACKUPWORKUNITSUPDATEARG']._serialized_end=281
  _globals['_RESTOREWORKUNITSUPDATEARG']._serialized_start=283
  _globals['_RESTOREWORKUNITSUPDATEARG']._serialized_end=389
  _globals['_FILEACTIONUPDATEARG']._serialized_start=392
  _globals['_FILEACTIONUPDATEARG']._serialized_end=1015
  _globals['_FILEACTIONUPDATEARG_TYPE']._serialized_start=688
  _globals['_FILEACTIONUPDATEARG_TYPE']._serialized_end=881
  _globals['_FILESTARTRESTORETASKARG']._serialized_start=1018
  _globals['_FILESTARTRESTORETASKARG']._serialized_end=1277
# @@protoc_insertion_point(module_scope)
