# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: apollo/mr/algorithms/brick_usage_stats/brick_usage_stats.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from configs import cluster_config_pb2 as configs_dot_cluster__config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>apollo/mr/algorithms/brick_usage_stats/brick_usage_stats.proto\x12\x1d\x63ohesity.apollo.mr.algorithms\x1a\x1c\x63onfigs/cluster_config.proto\"e\n\x1f\x42rickUsageStatsContextDataProto\x12\x42\n\x14\x63luster_config_proto\x18\x01 \x01(\x0b\x32$.cohesity.configs.ClusterConfigProto')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'apollo.mr.algorithms.brick_usage_stats.brick_usage_stats_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BRICKUSAGESTATSCONTEXTDATAPROTO']._serialized_start=127
  _globals['_BRICKUSAGESTATSCONTEXTDATAPROTO']._serialized_end=228
# @@protoc_insertion_point(module_scope)
