# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: experimental/ravi/protobuf/ds.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#experimental/ravi/protobuf/ds.proto\x12\x10\x63ohesity.protods\"e\n\x08ProtoMap\x12.\n\x02id\x18\x01 \x03(\x0b\x32\".cohesity.protods.ProtoMap.IdEntry\x1a)\n\x07IdEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\x08:\x02\x38\x01\"\x16\n\x08ProtoVec\x12\n\n\x02id\x18\x01 \x03(\x03')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'experimental.ravi.protobuf.ds_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROTOMAP_IDENTRY']._loaded_options = None
  _globals['_PROTOMAP_IDENTRY']._serialized_options = b'8\001'
  _globals['_PROTOMAP']._serialized_start=57
  _globals['_PROTOMAP']._serialized_end=158
  _globals['_PROTOMAP_IDENTRY']._serialized_start=117
  _globals['_PROTOMAP_IDENTRY']._serialized_end=158
  _globals['_PROTOVEC']._serialized_start=160
  _globals['_PROTOVEC']._serialized_end=182
# @@protoc_insertion_point(module_scope)
