# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: experimental/smurugesan/protobuf-3.6.0/src/google/protobuf/util/internal/testdata/proto3.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n^experimental/smurugesan/protobuf-3.6.0/src/google/protobuf/util/internal/testdata/proto3.proto\x12\x17google.protobuf.testing\"\x7f\n\rProto3Message\x12\x45\n\nenum_value\x18\x01 \x01(\x0e\x32\x31.google.protobuf.testing.Proto3Message.NestedEnum\"\'\n\nNestedEnum\x12\x07\n\x03\x46OO\x10\x00\x12\x07\n\x03\x42\x41R\x10\x01\x12\x07\n\x03\x42\x41Z\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'experimental.smurugesan.protobuf_3.6.0.src.google.protobuf.util.internal.testdata.proto3_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROTO3MESSAGE']._serialized_start=123
  _globals['_PROTO3MESSAGE']._serialized_end=250
  _globals['_PROTO3MESSAGE_NESTEDENUM']._serialized_start=211
  _globals['_PROTO3MESSAGE_NESTEDENUM']._serialized_end=250
# @@protoc_insertion_point(module_scope)
