# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: experimental/taruny/rpc/file_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from open_util.net import protorpc_pb2 as open__util_dot_net_dot_protorpc__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*experimental/taruny/rpc/file_service.proto\x12 cohesity.experimental.taruny.rpc\x1a\x1copen_util/net/protorpc.proto\"\"\n\rFileCreateArg\x12\x11\n\tfile_name\x18\x01 \x01(\t\"\xb7\x01\n\x10\x46ileCreateResult\x12K\n\x04type\x18\x01 \x01(\x0e\x32=.cohesity.experimental.taruny.rpc.FileCreateResult.ResultType\"V\n\nResultType\x12\x0c\n\x08kSuccess\x10\x01\x12\x12\n\x0ekAlreadyExists\x10\x02\x12\x13\n\x0fkNoNameProvided\x10\x03\x12\x11\n\rkUnknownError\x10\x04\"D\n\x0b\x46ileReadArg\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x11\n\x06offset\x18\x02 \x01(\x03:\x01\x30\x12\x0f\n\x03len\x18\x03 \x01(\x03:\x02-1\"\xb6\x01\n\x0e\x46ileReadResult\x12I\n\x04type\x18\x01 \x01(\x0e\x32;.cohesity.experimental.taruny.rpc.FileReadResult.ResultType\"Y\n\nResultType\x12\x0c\n\x08kSuccess\x10\x01\x12\x13\n\x0fkNoNameProvided\x10\x02\x12\x15\n\x11kFileDoesNotExist\x10\x03\x12\x11\n\rkUnknownError\x10\x04\"E\n\x0c\x46ileWriteArg\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x11\n\x06offset\x18\x02 \x01(\x03:\x01\x30\x12\x0f\n\x03len\x18\x03 \x01(\x03:\x02-1\"\xb8\x01\n\x0f\x46ileWriteResult\x12J\n\x04type\x18\x01 \x01(\x0e\x32<.cohesity.experimental.taruny.rpc.FileWriteResult.ResultType\"Y\n\nResultType\x12\x0c\n\x08kSuccess\x10\x01\x12\x13\n\x0fkNoNameProvided\x10\x02\x12\x15\n\x11kFileDoesNotExist\x10\x03\x12\x11\n\rkUnknownError\x10\x04\x32\xfc\x02\n\x0b\x46ileService\x12s\n\nCreateFile\x12/.cohesity.experimental.taruny.rpc.FileCreateArg\x1a\x32.cohesity.experimental.taruny.rpc.FileCreateResult\"\x00\x12r\n\rReadFileRange\x12-.cohesity.experimental.taruny.rpc.FileReadArg\x1a\x30.cohesity.experimental.taruny.rpc.FileReadResult\"\x00\x12u\n\x0eWriteFileRange\x12..cohesity.experimental.taruny.rpc.FileWriteArg\x1a\x31.cohesity.experimental.taruny.rpc.FileWriteResult\"\x00\x1a\r\x80\xf1\x04\xe8\x07\x88\xf1\x04\x01\x90\xf1\x04\x02\x42\x03\x80\x01\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'experimental.taruny.rpc.file_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\200\001\001'
  _globals['_FILESERVICE']._loaded_options = None
  _globals['_FILESERVICE']._serialized_options = b'\200\361\004\350\007\210\361\004\001\220\361\004\002'
  _globals['_FILECREATEARG']._serialized_start=110
  _globals['_FILECREATEARG']._serialized_end=144
  _globals['_FILECREATERESULT']._serialized_start=147
  _globals['_FILECREATERESULT']._serialized_end=330
  _globals['_FILECREATERESULT_RESULTTYPE']._serialized_start=244
  _globals['_FILECREATERESULT_RESULTTYPE']._serialized_end=330
  _globals['_FILEREADARG']._serialized_start=332
  _globals['_FILEREADARG']._serialized_end=400
  _globals['_FILEREADRESULT']._serialized_start=403
  _globals['_FILEREADRESULT']._serialized_end=585
  _globals['_FILEREADRESULT_RESULTTYPE']._serialized_start=496
  _globals['_FILEREADRESULT_RESULTTYPE']._serialized_end=585
  _globals['_FILEWRITEARG']._serialized_start=587
  _globals['_FILEWRITEARG']._serialized_end=656
  _globals['_FILEWRITERESULT']._serialized_start=659
  _globals['_FILEWRITERESULT']._serialized_end=843
  _globals['_FILEWRITERESULT_RESULTTYPE']._serialized_start=496
  _globals['_FILEWRITERESULT_RESULTTYPE']._serialized_end=585
  _globals['_FILESERVICE']._serialized_start=846
  _globals['_FILESERVICE']._serialized_end=1226
# @@protoc_insertion_point(module_scope)
