---
- name: Download Cohesity Agent
  hosts: linux
  tasks:
    - name: Ensure Cohesity agent is downloaded
      cohesity_agent:
        cluster: "{{ cohesity_server }}"
        username: "{{ cohesity_username }}"
        password: "{{ cohesity_password }}"
        validate_certs: "{{ cohesity_validate_certs }}"
        state: "{{ state | default('present') }}"
        create_user: "{{ create_user | default(false) }}"
        native_package: "{{ native_package | default(false) }}"
        operating_system: "{{ ansible_distribution }}"
