from util.message_catalog import message_catalog_pb2 as _message_catalog_pb2
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from typing import ClassVar as _ClassVar, Mapping as _Mapping, Optional as _Optional, Union as _Union

DESCRIPTOR: _descriptor.FileDescriptor

class ErrorProto(_message.Message):
    __slots__ = ("type", "error_msg", "detailed_error_msg")
    class Type(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
        __slots__ = ()
        kNoError: _ClassVar[ErrorProto.Type]
        kTransportError: _ClassVar[ErrorProto.Type]
        kTimeout: _ClassVar[ErrorProto.Type]
        kStale: _ClassVar[ErrorProto.Type]
        kExists: _ClassVar[ErrorProto.Type]
        kNonExistent: _ClassVar[ErrorProto.Type]
        kRetry: _ClassVar[ErrorProto.Type]
        kNotMaster: _ClassVar[ErrorProto.Type]
        kInvalidLogin: _ClassVar[ErrorProto.Type]
        kInvalidRequest: _ClassVar[ErrorProto.Type]
        kUnsupported: _ClassVar[ErrorProto.Type]
        kVSphereError: _ClassVar[ErrorProto.Type]
        kVixError: _ClassVar[ErrorProto.Type]
        kBridgeError: _ClassVar[ErrorProto.Type]
        kRejected: _ClassVar[ErrorProto.Type]
        kDuplicate: _ClassVar[ErrorProto.Type]
        kVMHostMismatch: _ClassVar[ErrorProto.Type]
        kGuestOperationsError: _ClassVar[ErrorProto.Type]
        kAgentError: _ClassVar[ErrorProto.Type]
        kAgentErrorNotRetryable: _ClassVar[ErrorProto.Type]
        kDatabaseBackupMismatch: _ClassVar[ErrorProto.Type]
        kVolumeUtilError: _ClassVar[ErrorProto.Type]
        kCopyUtilError: _ClassVar[ErrorProto.Type]
        kSqlRestoreError: _ClassVar[ErrorProto.Type]
        kGrpcError: _ClassVar[ErrorProto.Type]
        kYodaError: _ClassVar[ErrorProto.Type]
        kDisabled: _ClassVar[ErrorProto.Type]
        kScriptError: _ClassVar[ErrorProto.Type]
        kMethodError: _ClassVar[ErrorProto.Type]
        kUnknownError: _ClassVar[ErrorProto.Type]
        kCancelled: _ClassVar[ErrorProto.Type]
        kIneligible: _ClassVar[ErrorProto.Type]
        kPureError: _ClassVar[ErrorProto.Type]
        kCloudError: _ClassVar[ErrorProto.Type]
        kNexusError: _ClassVar[ErrorProto.Type]
        kNetappError: _ClassVar[ErrorProto.Type]
        kDirectoryWalkerError: _ClassVar[ErrorProto.Type]
        kScribeError: _ClassVar[ErrorProto.Type]
        kAcropolisError: _ClassVar[ErrorProto.Type]
        kFsError: _ClassVar[ErrorProto.Type]
        kVixTimeoutError: _ClassVar[ErrorProto.Type]
        kIsilonError: _ClassVar[ErrorProto.Type]
        kKvmError: _ClassVar[ErrorProto.Type]
        kSchedulingError: _ClassVar[ErrorProto.Type]
        kAccessError: _ClassVar[ErrorProto.Type]
        kInvalid: _ClassVar[ErrorProto.Type]
        kNotLeader: _ClassVar[ErrorProto.Type]
        kPending: _ClassVar[ErrorProto.Type]
        kParseError: _ClassVar[ErrorProto.Type]
        kServiceUnavailable: _ClassVar[ErrorProto.Type]
        kOracleRestoreError: _ClassVar[ErrorProto.Type]
        kFlashbladeError: _ClassVar[ErrorProto.Type]
        kDbRestoreError: _ClassVar[ErrorProto.Type]
        kCloudResourceLimitExceeded: _ClassVar[ErrorProto.Type]
        kVCDError: _ClassVar[ErrorProto.Type]
        kOutlookEwsError: _ClassVar[ErrorProto.Type]
        kHyperFlexError: _ClassVar[ErrorProto.Type]
        kCloudProxyDiskError: _ClassVar[ErrorProto.Type]
        kCloudProxyLaunchError: _ClassVar[ErrorProto.Type]
        kCloudResourceUnsupported: _ClassVar[ErrorProto.Type]
        kSQLLogChainHoleFound: _ClassVar[ErrorProto.Type]
        kSQLEntityLockingConflict: _ClassVar[ErrorProto.Type]
        kIncompleteHardlinkGroup: _ClassVar[ErrorProto.Type]
        kCloudNetworkConnectionError: _ClassVar[ErrorProto.Type]
        kBifrostError: _ClassVar[ErrorProto.Type]
        kWarning: _ClassVar[ErrorProto.Type]
        kADRestoreError: _ClassVar[ErrorProto.Type]
        kMSGraphError: _ClassVar[ErrorProto.Type]
        kGPFSError: _ClassVar[ErrorProto.Type]
        kNotImplemented: _ClassVar[ErrorProto.Type]
        kCimError: _ClassVar[ErrorProto.Type]
        kKubernetesError: _ClassVar[ErrorProto.Type]
        kIoFilterError: _ClassVar[ErrorProto.Type]
        kTagsError: _ClassVar[ErrorProto.Type]
        kNotSynchronized: _ClassVar[ErrorProto.Type]
        kNimbleError: _ClassVar[ErrorProto.Type]
        kSANError: _ClassVar[ErrorProto.Type]
        kElastifileError: _ClassVar[ErrorProto.Type]
        kOutOfSpace: _ClassVar[ErrorProto.Type]
        kSQLMissingDifferentialBase: _ClassVar[ErrorProto.Type]
        kUnauthorized: _ClassVar[ErrorProto.Type]
        kAtomError: _ClassVar[ErrorProto.Type]
        kExchangeError: _ClassVar[ErrorProto.Type]
        kCustomAttributesError: _ClassVar[ErrorProto.Type]
        kMissingBackupsetRows: _ClassVar[ErrorProto.Type]
        kImanisError: _ClassVar[ErrorProto.Type]
        kInvalidEndTime: _ClassVar[ErrorProto.Type]
        kInternalError: _ClassVar[ErrorProto.Type]
        kSQLMissingFCIInstances: _ClassVar[ErrorProto.Type]
        kVolumeAttachmentFailed: _ClassVar[ErrorProto.Type]
        kCloudResourceNotAvailable: _ClassVar[ErrorProto.Type]
        kEncryptionKeyNotFound: _ClassVar[ErrorProto.Type]
        kEOF: _ClassVar[ErrorProto.Type]
        kAutodiscoverError: _ClassVar[ErrorProto.Type]
        kSourceEntityNotPresent: _ClassVar[ErrorProto.Type]
        kSQLAAGRelationshipError: _ClassVar[ErrorProto.Type]
        kNoDbsDiscovered: _ClassVar[ErrorProto.Type]
        kSharepointError: _ClassVar[ErrorProto.Type]
        kHeimdallFleetError: _ClassVar[ErrorProto.Type]
        kViewKeeperError: _ClassVar[ErrorProto.Type]
        kAlreadyTerminated: _ClassVar[ErrorProto.Type]
        kUdaRestoreError: _ClassVar[ErrorProto.Type]
        kUdaBackupError: _ClassVar[ErrorProto.Type]
        kMDSError: _ClassVar[ErrorProto.Type]
        kMissingProvider: _ClassVar[ErrorProto.Type]
        kMountFailure: _ClassVar[ErrorProto.Type]
        kSFDCBackupError: _ClassVar[ErrorProto.Type]
        kSSLCertificateError: _ClassVar[ErrorProto.Type]
        kSSLHandshakeError: _ClassVar[ErrorProto.Type]
        kHostResolutionError: _ClassVar[ErrorProto.Type]
        kSfdcError: _ClassVar[ErrorProto.Type]
        kLogFileNonExistent: _ClassVar[ErrorProto.Type]
        kVMListPaginationError: _ClassVar[ErrorProto.Type]
        kFullRecoveryInProgress: _ClassVar[ErrorProto.Type]
        kEmptyFile: _ClassVar[ErrorProto.Type]
        kSkipped: _ClassVar[ErrorProto.Type]
        kMSGraphEmptyResponseError: _ClassVar[ErrorProto.Type]
        kViewBoxNotFound: _ClassVar[ErrorProto.Type]
        kSfdcCycleDetected: _ClassVar[ErrorProto.Type]
        kGCPSubnetIPExhausted: _ClassVar[ErrorProto.Type]
        kSfdcAwsError: _ClassVar[ErrorProto.Type]
        kResponseMalformed: _ClassVar[ErrorProto.Type]
        kNoConnectionAvailable: _ClassVar[ErrorProto.Type]
        kNonProtectableEntity: _ClassVar[ErrorProto.Type]
        kInvalidApiResponse: _ClassVar[ErrorProto.Type]
        kInvalidParameter: _ClassVar[ErrorProto.Type]
        kIOError: _ClassVar[ErrorProto.Type]
        kOracleRestoreV2NotSupported: _ClassVar[ErrorProto.Type]
        kVosEOF: _ClassVar[ErrorProto.Type]
        kVosFailure: _ClassVar[ErrorProto.Type]
        kVosIgnoreOffset: _ClassVar[ErrorProto.Type]
        kIbmFlashSystemError: _ClassVar[ErrorProto.Type]
        kRequestEntityTooLarge: _ClassVar[ErrorProto.Type]
        kCorrupt: _ClassVar[ErrorProto.Type]
        kSnapshotError: _ClassVar[ErrorProto.Type]
        kQueryDiskExtentSessionExpired: _ClassVar[ErrorProto.Type]
    kNoError: ErrorProto.Type
    kTransportError: ErrorProto.Type
    kTimeout: ErrorProto.Type
    kStale: ErrorProto.Type
    kExists: ErrorProto.Type
    kNonExistent: ErrorProto.Type
    kRetry: ErrorProto.Type
    kNotMaster: ErrorProto.Type
    kInvalidLogin: ErrorProto.Type
    kInvalidRequest: ErrorProto.Type
    kUnsupported: ErrorProto.Type
    kVSphereError: ErrorProto.Type
    kVixError: ErrorProto.Type
    kBridgeError: ErrorProto.Type
    kRejected: ErrorProto.Type
    kDuplicate: ErrorProto.Type
    kVMHostMismatch: ErrorProto.Type
    kGuestOperationsError: ErrorProto.Type
    kAgentError: ErrorProto.Type
    kAgentErrorNotRetryable: ErrorProto.Type
    kDatabaseBackupMismatch: ErrorProto.Type
    kVolumeUtilError: ErrorProto.Type
    kCopyUtilError: ErrorProto.Type
    kSqlRestoreError: ErrorProto.Type
    kGrpcError: ErrorProto.Type
    kYodaError: ErrorProto.Type
    kDisabled: ErrorProto.Type
    kScriptError: ErrorProto.Type
    kMethodError: ErrorProto.Type
    kUnknownError: ErrorProto.Type
    kCancelled: ErrorProto.Type
    kIneligible: ErrorProto.Type
    kPureError: ErrorProto.Type
    kCloudError: ErrorProto.Type
    kNexusError: ErrorProto.Type
    kNetappError: ErrorProto.Type
    kDirectoryWalkerError: ErrorProto.Type
    kScribeError: ErrorProto.Type
    kAcropolisError: ErrorProto.Type
    kFsError: ErrorProto.Type
    kVixTimeoutError: ErrorProto.Type
    kIsilonError: ErrorProto.Type
    kKvmError: ErrorProto.Type
    kSchedulingError: ErrorProto.Type
    kAccessError: ErrorProto.Type
    kInvalid: ErrorProto.Type
    kNotLeader: ErrorProto.Type
    kPending: ErrorProto.Type
    kParseError: ErrorProto.Type
    kServiceUnavailable: ErrorProto.Type
    kOracleRestoreError: ErrorProto.Type
    kFlashbladeError: ErrorProto.Type
    kDbRestoreError: ErrorProto.Type
    kCloudResourceLimitExceeded: ErrorProto.Type
    kVCDError: ErrorProto.Type
    kOutlookEwsError: ErrorProto.Type
    kHyperFlexError: ErrorProto.Type
    kCloudProxyDiskError: ErrorProto.Type
    kCloudProxyLaunchError: ErrorProto.Type
    kCloudResourceUnsupported: ErrorProto.Type
    kSQLLogChainHoleFound: ErrorProto.Type
    kSQLEntityLockingConflict: ErrorProto.Type
    kIncompleteHardlinkGroup: ErrorProto.Type
    kCloudNetworkConnectionError: ErrorProto.Type
    kBifrostError: ErrorProto.Type
    kWarning: ErrorProto.Type
    kADRestoreError: ErrorProto.Type
    kMSGraphError: ErrorProto.Type
    kGPFSError: ErrorProto.Type
    kNotImplemented: ErrorProto.Type
    kCimError: ErrorProto.Type
    kKubernetesError: ErrorProto.Type
    kIoFilterError: ErrorProto.Type
    kTagsError: ErrorProto.Type
    kNotSynchronized: ErrorProto.Type
    kNimbleError: ErrorProto.Type
    kSANError: ErrorProto.Type
    kElastifileError: ErrorProto.Type
    kOutOfSpace: ErrorProto.Type
    kSQLMissingDifferentialBase: ErrorProto.Type
    kUnauthorized: ErrorProto.Type
    kAtomError: ErrorProto.Type
    kExchangeError: ErrorProto.Type
    kCustomAttributesError: ErrorProto.Type
    kMissingBackupsetRows: ErrorProto.Type
    kImanisError: ErrorProto.Type
    kInvalidEndTime: ErrorProto.Type
    kInternalError: ErrorProto.Type
    kSQLMissingFCIInstances: ErrorProto.Type
    kVolumeAttachmentFailed: ErrorProto.Type
    kCloudResourceNotAvailable: ErrorProto.Type
    kEncryptionKeyNotFound: ErrorProto.Type
    kEOF: ErrorProto.Type
    kAutodiscoverError: ErrorProto.Type
    kSourceEntityNotPresent: ErrorProto.Type
    kSQLAAGRelationshipError: ErrorProto.Type
    kNoDbsDiscovered: ErrorProto.Type
    kSharepointError: ErrorProto.Type
    kHeimdallFleetError: ErrorProto.Type
    kViewKeeperError: ErrorProto.Type
    kAlreadyTerminated: ErrorProto.Type
    kUdaRestoreError: ErrorProto.Type
    kUdaBackupError: ErrorProto.Type
    kMDSError: ErrorProto.Type
    kMissingProvider: ErrorProto.Type
    kMountFailure: ErrorProto.Type
    kSFDCBackupError: ErrorProto.Type
    kSSLCertificateError: ErrorProto.Type
    kSSLHandshakeError: ErrorProto.Type
    kHostResolutionError: ErrorProto.Type
    kSfdcError: ErrorProto.Type
    kLogFileNonExistent: ErrorProto.Type
    kVMListPaginationError: ErrorProto.Type
    kFullRecoveryInProgress: ErrorProto.Type
    kEmptyFile: ErrorProto.Type
    kSkipped: ErrorProto.Type
    kMSGraphEmptyResponseError: ErrorProto.Type
    kViewBoxNotFound: ErrorProto.Type
    kSfdcCycleDetected: ErrorProto.Type
    kGCPSubnetIPExhausted: ErrorProto.Type
    kSfdcAwsError: ErrorProto.Type
    kResponseMalformed: ErrorProto.Type
    kNoConnectionAvailable: ErrorProto.Type
    kNonProtectableEntity: ErrorProto.Type
    kInvalidApiResponse: ErrorProto.Type
    kInvalidParameter: ErrorProto.Type
    kIOError: ErrorProto.Type
    kOracleRestoreV2NotSupported: ErrorProto.Type
    kVosEOF: ErrorProto.Type
    kVosFailure: ErrorProto.Type
    kVosIgnoreOffset: ErrorProto.Type
    kIbmFlashSystemError: ErrorProto.Type
    kRequestEntityTooLarge: ErrorProto.Type
    kCorrupt: ErrorProto.Type
    kSnapshotError: ErrorProto.Type
    kQueryDiskExtentSessionExpired: ErrorProto.Type
    TYPE_FIELD_NUMBER: _ClassVar[int]
    ERROR_MSG_FIELD_NUMBER: _ClassVar[int]
    DETAILED_ERROR_MSG_FIELD_NUMBER: _ClassVar[int]
    type: ErrorProto.Type
    error_msg: str
    detailed_error_msg: _message_catalog_pb2.MessageProto
    def __init__(self, type: _Optional[_Union[ErrorProto.Type, str]] = ..., error_msg: _Optional[str] = ..., detailed_error_msg: _Optional[_Union[_message_catalog_pb2.MessageProto, _Mapping]] = ...) -> None: ...
