# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: experimental/madhusudan/rpc_server.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from open_util.net import protorpc_pb2 as open__util_dot_net_dot_protorpc__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(experimental/madhusudan/rpc_server.proto\x12 cohesity.experimental.madhusudan\x1a\x1copen_util/net/protorpc.proto\"%\n\x11\x43reateFileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x02(\t\"P\n\x12\x43reateFileResponse\x12:\n\x05\x65rror\x18\x01 \x02(\x0e\x32+.cohesity.experimental.madhusudan.ErrorType\"C\n\x0fReadFileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x02(\t\x12\x0e\n\x06offset\x18\x02 \x02(\x03\x12\x0e\n\x06length\x18\x03 \x02(\x03\"N\n\x10ReadFileResponse\x12:\n\x05\x65rror\x18\x01 \x02(\x0e\x32+.cohesity.experimental.madhusudan.ErrorType\"D\n\x10WriteFileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x02(\t\x12\x0e\n\x06offset\x18\x02 \x02(\x03\x12\x0e\n\x06length\x18\x03 \x02(\x03\"O\n\x11WriteFileResponse\x12:\n\x05\x65rror\x18\x01 \x02(\x0e\x32+.cohesity.experimental.madhusudan.ErrorType*9\n\tErrorType\x12\x0c\n\x08\x66NoError\x10\x00\x12\x12\n\x0e\x66\x46ileNotExists\x10\x01\x12\n\n\x06\x66Other\x10\x02\x32\xff\x02\n\x06Server\x12y\n\nCreateFile\x12\x33.cohesity.experimental.madhusudan.CreateFileRequest\x1a\x34.cohesity.experimental.madhusudan.CreateFileResponse\"\x00\x12s\n\x08ReadFile\x12\x31.cohesity.experimental.madhusudan.ReadFileRequest\x1a\x32.cohesity.experimental.madhusudan.ReadFileResponse\"\x00\x12v\n\tWriteFile\x12\x32.cohesity.experimental.madhusudan.WriteFileRequest\x1a\x33.cohesity.experimental.madhusudan.WriteFileResponse\"\x00\x1a\r\x80\xf1\x04\xe8\x07\x88\xf1\x04\x01\x90\xf1\x04\x02\x42\x03\x80\x01\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'experimental.madhusudan.rpc_server_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\200\001\001'
  _globals['_SERVER']._loaded_options = None
  _globals['_SERVER']._serialized_options = b'\200\361\004\350\007\210\361\004\001\220\361\004\002'
  _globals['_ERRORTYPE']._serialized_start=529
  _globals['_ERRORTYPE']._serialized_end=586
  _globals['_CREATEFILEREQUEST']._serialized_start=108
  _globals['_CREATEFILEREQUEST']._serialized_end=145
  _globals['_CREATEFILERESPONSE']._serialized_start=147
  _globals['_CREATEFILERESPONSE']._serialized_end=227
  _globals['_READFILEREQUEST']._serialized_start=229
  _globals['_READFILEREQUEST']._serialized_end=296
  _globals['_READFILERESPONSE']._serialized_start=298
  _globals['_READFILERESPONSE']._serialized_end=376
  _globals['_WRITEFILEREQUEST']._serialized_start=378
  _globals['_WRITEFILEREQUEST']._serialized_end=446
  _globals['_WRITEFILERESPONSE']._serialized_start=448
  _globals['_WRITEFILERESPONSE']._serialized_end=527
  _globals['_SERVER']._serialized_start=589
  _globals['_SERVER']._serialized_end=972
# @@protoc_insertion_point(module_scope)
