# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: magneto/connectors/isilon/isilon.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from magneto.base import magneto_pb2 as magneto_dot_base_dot_magneto__pb2
try:
  magneto_dot_base_dot_env__params__pb2 = magneto_dot_base_dot_magneto__pb2.magneto_dot_base_dot_env__params__pb2
except AttributeError:
  magneto_dot_base_dot_env__params__pb2 = magneto_dot_base_dot_magneto__pb2.magneto.base.env_params_pb2
from magneto.connectors.file import file_pb2 as magneto_dot_connectors_dot_file_dot_file__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&magneto/connectors/isilon/isilon.proto\x12\x17\x63ohesity.magneto.isilon\x1a\x1amagneto/base/magneto.proto\x1a\"magneto/connectors/file/file.proto\"\xca\x04\n\x0cSnapshotInfo\x12\n\n\x02id\x18\x01 \x01(\r\x12\x1b\n\x13\x63reation_time_usecs\x18\x02 \x01(\x03\x12\x19\n\x11\x65xpire_time_usecs\x18\x03 \x01(\x03\x12\\\n\x10\x63hangelist_state\x18\x04 \x01(\x0e\x32\x35.cohesity.magneto.isilon.SnapshotInfo.ChangelistState:\x0bkNotStarted\x12\x19\n\x11\x63hangelist_job_id\x18\x05 \x01(\x03\x12\x1f\n\x17pagination_resume_token\x18\x06 \x01(\t\x12\x1a\n\x12\x63hangelist_deleted\x18\x07 \x01(\x08\x12\"\n\x1askip_configure_nfs_exports\x18\x08 \x01(\x08\x12*\n\"changelist_creation_final_progress\x18\t \x01(\t\x12(\n\x1auses_ifs_root_for_snapshot\x18\x63 \x01(\x08:\x04true\"\\\n\x0f\x43hangelistState\x12\x0f\n\x0bkNotStarted\x10\x00\x12\x16\n\x12kCreateRequestSent\x10\x01\x12\x0c\n\x08kCreated\x10\x02\x12\x12\n\x0ekFullyIngested\x10\x03\x32h\n\x14isilon_snapshot_info\x12#.cohesity.magneto.file.SnapshotInfo\x18g \x01(\x0b\x32%.cohesity.magneto.isilon.SnapshotInfo\"\x7f\n\x0b\x43hangeEntry\x12\x0b\n\x03lin\x18\x01 \x01(\x03\x32\x63\n\x0cisilon_entry\x12\'.cohesity.magneto.file.ChangeEntryProto\x18\x64 \x01(\x0b\x32$.cohesity.magneto.isilon.ChangeEntry\"\xac\x02\n\x13SnapChangeInfoCache\x12X\n\x0f\x64\x65leted_lin_map\x18\x01 \x03(\x0b\x32?.cohesity.magneto.isilon.SnapChangeInfoCache.DeletedLinMapEntry\x1a\x34\n\x12\x44\x65letedLinMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\x84\x01\n\x1disilon_snap_change_info_cache\x12/.cohesity.magneto.file.SnapChangeInfoCacheProto\x18\x64 \x01(\x0b\x32,.cohesity.magneto.isilon.SnapChangeInfoCache')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'magneto.connectors.isilon.isilon_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SNAPCHANGEINFOCACHE_DELETEDLINMAPENTRY']._loaded_options = None
  _globals['_SNAPCHANGEINFOCACHE_DELETEDLINMAPENTRY']._serialized_options = b'8\001'
  _globals['_SNAPSHOTINFO']._serialized_start=132
  _globals['_SNAPSHOTINFO']._serialized_end=718
  _globals['_SNAPSHOTINFO_CHANGELISTSTATE']._serialized_start=520
  _globals['_SNAPSHOTINFO_CHANGELISTSTATE']._serialized_end=612
  _globals['_CHANGEENTRY']._serialized_start=720
  _globals['_CHANGEENTRY']._serialized_end=847
  _globals['_SNAPCHANGEINFOCACHE']._serialized_start=850
  _globals['_SNAPCHANGEINFOCACHE']._serialized_end=1150
  _globals['_SNAPCHANGEINFOCACHE_DELETEDLINMAPENTRY']._serialized_start=963
  _globals['_SNAPCHANGEINFOCACHE_DELETEDLINMAPENTRY']._serialized_end=1015
# @@protoc_insertion_point(module_scope)
