from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from typing import ClassVar as _ClassVar, Optional as _Optional

DESCRIPTOR: _descriptor.FileDescriptor

class BridgeStatsConfigProto(_message.Message):
    __slots__ = ("time_to_live_secs", "internal_stats_time_to_live_secs", "disk_stats_schema_name", "disk_stats_schema_version", "node_stats_schema_name", "node_stats_schema_version", "cluster_stats_schema_name", "cluster_stats_schema_version", "viewbox_disk_stats_schema_name", "viewbox_disk_stats_schema_version", "viewbox_stats_schema_name", "viewbox_stats_schema_version", "viewbox_node_logical_stats_schema_name", "viewbox_node_logical_stats_schema_version", "viewbox_logical_stats_schema_name", "viewbox_logical_stats_schema_version", "cluster_logical_stats_schema_name", "cluster_logical_stats_schema_version", "viewbox_node_workload_logical_stats_schema_name", "viewbox_node_workload_logical_stats_schema_version", "viewbox_workload_logical_stats_schema_name", "viewbox_workload_logical_stats_schema_version", "cluster_workload_logical_stats_schema_name", "cluster_workload_logical_stats_schema_version", "icebox_vault_stats_schema_name", "icebox_vault_stats_schema_version", "viewbox_node_scribe_physical_stats_schema_name", "viewbox_node_scribe_physical_stats_schema_version", "icebox_job_vault_stats_schema_name", "icebox_job_vault_stats_schema_version", "cluster_tier_physical_stats_schema_name", "cluster_tier_physical_stats_schema_version", "viewbox_tier_physical_stats_schema_name", "viewbox_tier_physical_stats_schema_version", "icebox_cluster_vault_stats_schema_name", "icebox_cluster_vault_stats_schema_version", "viewbox_node_brick_stats_schema_name", "viewbox_node_brick_stats_schema_version", "view_stats_schema_name", "view_stats_schema_version", "stats_container_stats_schema_name", "stats_container_stats_schema_version", "viewbox_node_blob_data_journal_schema_name", "viewbox_node_blob_data_journal_schema_version", "viewbox_blob_data_journal_schema_name", "viewbox_blob_data_journal_schema_version", "cluster_blob_data_journal_schema_name", "cluster_blob_data_journal_schema_version", "viewbox_node_blob_metadata_journal_schema_name", "viewbox_node_blob_metadata_journal_schema_version", "viewbox_blob_metadata_journal_schema_name", "viewbox_blob_metadata_journal_schema_version", "cluster_blob_metadata_journal_schema_name", "cluster_blob_metadata_journal_schema_version", "view_blob_metadata_journal_schema_name", "view_blob_metadata_journal_schema_version", "view_perf_stats_schema_name", "view_perf_stats_schema_version", "viewbox_node_journal_usage_stats_schema_name", "viewbox_node_journal_usage_stats_schema_version", "viewbox_journal_usage_stats_schema_name", "viewbox_journal_usage_stats_schema_version", "disk_journal_usage_stats_schema_name", "disk_journal_usage_stats_schema_version", "node_journal_usage_stats_schema_name", "node_journal_usage_stats_schema_version", "cluster_journal_usage_stats_schema_name", "cluster_journal_usage_stats_schema_version", "admctl_component_node_stats_schema_name", "admctl_component_node_stats_schema_version", "admctl_component_queue_stats_schema_name", "admctl_component_queue_stats_schema_version", "admctl_component_queue_cluster_stats_schema_name", "admctl_component_queue_cluster_stats_schema_version", "icebox_stub_view_stats_schema_name", "icebox_stub_view_stats_schema_version", "object_perf_stats_schema_name", "object_perf_stats_schema_version", "icebox_cloud_domain_stats_schema_name", "icebox_cloud_domain_stats_schema_version", "filer_perf_stats_schema_name", "filer_perf_stats_schema_version", "client_perf_stats_schema_name", "client_perf_stats_schema_version", "workload_stats_schema_name", "workload_stats_schema_version", "workload_component_level_perf_stats_schema_name", "workload_component_level_perf_stats_schema_version", "workload_granular_level_perf_stats_schema_name", "workload_granular_level_perf_stats_schema_version", "ldap_perf_stats_schema_name", "ldap_perf_stats_schema_version", "workload_physical_perf_stats_schema_name", "workload_physical_perf_stats_schema_version", "disk_id_attr", "node_id_attr", "cluster_id_attr", "viewbox_disk_id_attr", "viewbox_id_attr", "viewbox_name_attr", "viewbox_node_id_attr", "viewbox_node_workload_id_attr", "viewbox_workload_id_attr", "cluster_workload_id_attr", "icebox_vault_id_attr", "icebox_job_vault_id_attr", "icebox_job_id_attr", "cluster_tier_id_attr", "viewbox_tier_id_attr", "icebox_vault_name_attr", "icebox_vault_type_attr", "icebox_job_name_attr", "view_id_attr", "stats_container_id_attr", "icebox_job_type_attr", "icebox_num_entities_attr", "component_queue_node_id_attr", "component_queue_id_attr", "component_id_attr", "icebox_cloud_domain_id_attr", "icebox_cloud_domain_namespace_attr", "filer_perf_stats_id_attr", "client_perf_stats_id_attr", "priority_inversion_node_id_attr", "priority_inversion_component_id_attr", "priority_inversion_cluster_id_attr", "viewbox_node_metadata_journal_usage_stats_schema_name", "viewbox_node_metadata_journal_usage_stats_schema_version", "viewbox_metadata_journal_usage_stats_schema_name", "viewbox_metadata_journal_usage_stats_schema_version", "view_metadata_journal_usage_stats_schema_name", "view_metadata_journal_usage_stats_schema_version", "node_metadata_journal_usage_stats_schema_name", "node_metadata_journal_usage_stats_schema_version", "cluster_metadata_journal_usage_stats_schema_name", "cluster_metadata_journal_usage_stats_schema_version", "disk_metadata_journal_usage_stats_schema_name", "disk_metadata_journal_usage_stats_schema_version", "workload_stats_id_attr", "workload_component_level_perf_stats_id_attr", "workload_granular_level_perf_stats_id_attr", "ldap_perf_stats_id_attr", "icebox_archive_format_attr", "workload_physical_perf_stats_id_attr", "priority_inversion_node_stats_schema_name", "priority_inversion_node_stats_schema_version", "priority_inversion_component_stats_schema_name", "priority_inversion_component_stats_schema_version", "priority_inversion_cluster_stats_schema_name", "priority_inversion_cluster_stats_schema_version")
    class Metric(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
        __slots__ = ()
        kTotalIos: _ClassVar[BridgeStatsConfigProto.Metric]
        kReadIos: _ClassVar[BridgeStatsConfigProto.Metric]
        kWriteIos: _ClassVar[BridgeStatsConfigProto.Metric]
        kSequentialIos: _ClassVar[BridgeStatsConfigProto.Metric]
        kRandomIos: _ClassVar[BridgeStatsConfigProto.Metric]
        kNumBytesRead: _ClassVar[BridgeStatsConfigProto.Metric]
        kNumBytesWritten: _ClassVar[BridgeStatsConfigProto.Metric]
        kReadLatencyUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kWriteLatencyUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kNumReadErrors: _ClassVar[BridgeStatsConfigProto.Metric]
        kNumWriteErrors: _ClassVar[BridgeStatsConfigProto.Metric]
        kReadSizesP25: _ClassVar[BridgeStatsConfigProto.Metric]
        kReadSizesP50: _ClassVar[BridgeStatsConfigProto.Metric]
        kReadSizesP75: _ClassVar[BridgeStatsConfigProto.Metric]
        kReadSizesP99: _ClassVar[BridgeStatsConfigProto.Metric]
        kWriteSizesP25: _ClassVar[BridgeStatsConfigProto.Metric]
        kWriteSizesP50: _ClassVar[BridgeStatsConfigProto.Metric]
        kWriteSizesP75: _ClassVar[BridgeStatsConfigProto.Metric]
        kWriteSizesP99: _ClassVar[BridgeStatsConfigProto.Metric]
        kCapacityBytes: _ClassVar[BridgeStatsConfigProto.Metric]
        kSystemCapacityBytes: _ClassVar[BridgeStatsConfigProto.Metric]
        kMorphedUsageBytes: _ClassVar[BridgeStatsConfigProto.Metric]
        kUnmorphedUsageBytes: _ClassVar[BridgeStatsConfigProto.Metric]
        kSystemUsageBytes: _ClassVar[BridgeStatsConfigProto.Metric]
        kMorphedGarbageBytes: _ClassVar[BridgeStatsConfigProto.Metric]
        kUnmorphedGarbageBytes: _ClassVar[BridgeStatsConfigProto.Metric]
        kDedupMorphedUsageBytes: _ClassVar[BridgeStatsConfigProto.Metric]
        kDedupUnmorphedUsageBytes: _ClassVar[BridgeStatsConfigProto.Metric]
        kNonDedupMorphedUsageBytes: _ClassVar[BridgeStatsConfigProto.Metric]
        kNonDedupUnmorphedUsageBytes: _ClassVar[BridgeStatsConfigProto.Metric]
        kGarbageMorphedUsageBytes: _ClassVar[BridgeStatsConfigProto.Metric]
        kGarbageUnmorphedUsageBytes: _ClassVar[BridgeStatsConfigProto.Metric]
        kScribeUsageBytes: _ClassVar[BridgeStatsConfigProto.Metric]
        kBrickUsageBytes: _ClassVar[BridgeStatsConfigProto.Metric]
        kPreReplicationMorphedUsageBytes: _ClassVar[BridgeStatsConfigProto.Metric]
        kContainerECEncodeBytes: _ClassVar[BridgeStatsConfigProto.Metric]
        kContainerECEncodeOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kContainerECEncodeErrors: _ClassVar[BridgeStatsConfigProto.Metric]
        kContainerECEncodeLatencyUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kUnmorphedBytesArchived: _ClassVar[BridgeStatsConfigProto.Metric]
        kMorphedBytesArchived: _ClassVar[BridgeStatsConfigProto.Metric]
        kUnmorphedBytesRestored: _ClassVar[BridgeStatsConfigProto.Metric]
        kMorphedBytesRestored: _ClassVar[BridgeStatsConfigProto.Metric]
        kUnmorphedBytesGCed: _ClassVar[BridgeStatsConfigProto.Metric]
        kMorphedBytesGCed: _ClassVar[BridgeStatsConfigProto.Metric]
        kUnmorphedBytesUptiered: _ClassVar[BridgeStatsConfigProto.Metric]
        kMorphedBytesUptiered: _ClassVar[BridgeStatsConfigProto.Metric]
        kMorphedBytesDowntiered: _ClassVar[BridgeStatsConfigProto.Metric]
        kCloudGetCall: _ClassVar[BridgeStatsConfigProto.Metric]
        kCloudGetCallLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kCloudGetCallErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kCloudPutCall: _ClassVar[BridgeStatsConfigProto.Metric]
        kCloudPutCallLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kCloudPutCallErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kCloudPostCall: _ClassVar[BridgeStatsConfigProto.Metric]
        kCloudPostCallLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kCloudPostCallErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kCloudDeleteCall: _ClassVar[BridgeStatsConfigProto.Metric]
        kCloudDeleteCallLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kCloudDeleteCallErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kCloudHeadCall: _ClassVar[BridgeStatsConfigProto.Metric]
        kCloudHeadCallLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kCloudHeadCallErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kCloudUptierHeadCall: _ClassVar[BridgeStatsConfigProto.Metric]
        kCloudUptierHeadCallLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kCloudUptierHeadCallErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kCloudUptierPostCall: _ClassVar[BridgeStatsConfigProto.Metric]
        kCloudUptierPostCallLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kCloudUptierPostCallErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kCloudDowntierPutCall: _ClassVar[BridgeStatsConfigProto.Metric]
        kCloudDowntierPutCallLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kCloudDowntierPutCallErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kNumEntriesExecutingExternal: _ClassVar[BridgeStatsConfigProto.Metric]
        kNumEntriesQueuedExternal: _ClassVar[BridgeStatsConfigProto.Metric]
        kNumEntriesExecutingBlobstore: _ClassVar[BridgeStatsConfigProto.Metric]
        kNumEntriesQueuedBlobstore: _ClassVar[BridgeStatsConfigProto.Metric]
        kBlobstoreQueueCapacity: _ClassVar[BridgeStatsConfigProto.Metric]
        kBlobstoreQueueLoad: _ClassVar[BridgeStatsConfigProto.Metric]
        kDowntierBytes: _ClassVar[BridgeStatsConfigProto.Metric]
        kDowntierIos: _ClassVar[BridgeStatsConfigProto.Metric]
        kDowntierErrors: _ClassVar[BridgeStatsConfigProto.Metric]
        kDowntierLatency: _ClassVar[BridgeStatsConfigProto.Metric]
        kBlobDataJournalAdmittedIos: _ClassVar[BridgeStatsConfigProto.Metric]
        kBlobDataJournalBytesFlushed: _ClassVar[BridgeStatsConfigProto.Metric]
        kBlobDataJournalFlushLatencyUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kBlobDataJournalBytesWritten: _ClassVar[BridgeStatsConfigProto.Metric]
        kBlobDataJournalWriteLatencyUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kBlobDataJournalBytesRead: _ClassVar[BridgeStatsConfigProto.Metric]
        kBlobDataJournalReadIos: _ClassVar[BridgeStatsConfigProto.Metric]
        kBlobDataJournalReadLatencyUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kBlobDataJournalBytesOffloaded: _ClassVar[BridgeStatsConfigProto.Metric]
        kBlobDataJournalEpochReplicaOffloadLatencyUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kBlobDataJournalEpochReplicasOffloaded: _ClassVar[BridgeStatsConfigProto.Metric]
        kBlobMetadataJournalAdmittedIos: _ClassVar[BridgeStatsConfigProto.Metric]
        kBlobMetadataJournalBytesFlushed: _ClassVar[BridgeStatsConfigProto.Metric]
        kBlobMetadataJournalFlushLatencyUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kBlobMetadataJournalBytesWritten: _ClassVar[BridgeStatsConfigProto.Metric]
        kBlobMetadataJournalWriteLatencyUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kBlobMetadataJournalBytesRead: _ClassVar[BridgeStatsConfigProto.Metric]
        kBlobMetadataJournalReadIos: _ClassVar[BridgeStatsConfigProto.Metric]
        kBlobMetadataJournalReadLatencyUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kBlobMetadataJournalBytesOffloaded: _ClassVar[BridgeStatsConfigProto.Metric]
        kBlobMetadataJournalEpochReplicaOffloadLatencyUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kBlobMetadataJournalEpochReplicasOffloaded: _ClassVar[BridgeStatsConfigProto.Metric]
        kChunkBytesLogical: _ClassVar[BridgeStatsConfigProto.Metric]
        kChunkBytesMorphed: _ClassVar[BridgeStatsConfigProto.Metric]
        kChunkBytesPhysical: _ClassVar[BridgeStatsConfigProto.Metric]
        kNumFiles: _ClassVar[BridgeStatsConfigProto.Metric]
        kNumDirectories: _ClassVar[BridgeStatsConfigProto.Metric]
        kInodeBytesLogical: _ClassVar[BridgeStatsConfigProto.Metric]
        kUniqueChunkBytesLogical: _ClassVar[BridgeStatsConfigProto.Metric]
        kUniqueChunkBytesPhysical: _ClassVar[BridgeStatsConfigProto.Metric]
        kUniqueChunkBytesPhysicalCloud: _ClassVar[BridgeStatsConfigProto.Metric]
        kUniqueChunkBytesPhysicalLocal: _ClassVar[BridgeStatsConfigProto.Metric]
        kUniqueChunkBytesMorphed: _ClassVar[BridgeStatsConfigProto.Metric]
        kUniqueChunkBytesMorphedCloud: _ClassVar[BridgeStatsConfigProto.Metric]
        kUniqueChunkBytesMorphedLocal: _ClassVar[BridgeStatsConfigProto.Metric]
        kCreateFileLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kCreateFileOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kCreateFileErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kMkDirLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kMkDirOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kMkDirErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kMkNodLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kMkNodOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kMkNodErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kSymLinkLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kSymLinkOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kSymLinkErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kRmDirLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kRmDirOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kRmDirErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kRemoveFileLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kRemoveFileOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kRemoveFileErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kLookupInodeMetaDataLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kLookupInodeMetaDataOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kLookupInodeMetaDataErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kLookupPathLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kLookupPathOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kLookupPathErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kLookupDirectoryEntryLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kLookupDirectoryEntryOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kLookupDirectoryEntryErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kLinkLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kLinkOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kLinkErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kSetattrLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kSetattrOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kSetattrErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kReaddirLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kReaddirOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kReaddirErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kRenameLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kRenameOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kRenameErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kCloneBytesLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kCloneBytesOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kCloneBytesErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kCommitLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kCommitOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kCommitErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kDeleteOrphanLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kDeleteOrphanOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kDeleteOrphanErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kDeleteGarbageLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kDeleteGarbageOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kDeleteGarbageErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kDirQuotaRecursiveWalkLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kDirQuotaRecursiveWalkOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kDirQuotaRecursiveWalkErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kSnapFsFixerLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kSnapFsFixerOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kSnapFsFixerErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kTextFilesCount: _ClassVar[BridgeStatsConfigProto.Metric]
        kTextFilesBytes: _ClassVar[BridgeStatsConfigProto.Metric]
        kVideoFilesCount: _ClassVar[BridgeStatsConfigProto.Metric]
        kVideoFilesBytes: _ClassVar[BridgeStatsConfigProto.Metric]
        kAudioFilesCount: _ClassVar[BridgeStatsConfigProto.Metric]
        kAudioFilesBytes: _ClassVar[BridgeStatsConfigProto.Metric]
        kCompressedFilesCount: _ClassVar[BridgeStatsConfigProto.Metric]
        kCompressedFilesBytes: _ClassVar[BridgeStatsConfigProto.Metric]
        kDatabaseFilesCount: _ClassVar[BridgeStatsConfigProto.Metric]
        kDatabaseFilesBytes: _ClassVar[BridgeStatsConfigProto.Metric]
        kImageFilesCount: _ClassVar[BridgeStatsConfigProto.Metric]
        kImageFilesBytes: _ClassVar[BridgeStatsConfigProto.Metric]
        kExecutableFilesCount: _ClassVar[BridgeStatsConfigProto.Metric]
        kExecutableFilesBytes: _ClassVar[BridgeStatsConfigProto.Metric]
        kLogFilesCount: _ClassVar[BridgeStatsConfigProto.Metric]
        kLogFilesBytes: _ClassVar[BridgeStatsConfigProto.Metric]
        kOtherFilesCount: _ClassVar[BridgeStatsConfigProto.Metric]
        kOtherFilesBytes: _ClassVar[BridgeStatsConfigProto.Metric]
        kStubViewReadBytes: _ClassVar[BridgeStatsConfigProto.Metric]
        kStubViewReadLatencyUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kJournalNumEpochs: _ClassVar[BridgeStatsConfigProto.Metric]
        kAdmctlRequestsCompleted: _ClassVar[BridgeStatsConfigProto.Metric]
        kAdmctlSlotsUsed: _ClassVar[BridgeStatsConfigProto.Metric]
        kAdmctlRequestsQueued: _ClassVar[BridgeStatsConfigProto.Metric]
        kAdmctlThresholdSlots: _ClassVar[BridgeStatsConfigProto.Metric]
        kAdmctlNumPriorityInversions: _ClassVar[BridgeStatsConfigProto.Metric]
        kAdmctlReleaseEvents: _ClassVar[BridgeStatsConfigProto.Metric]
        kAdmctlThrottleEvents: _ClassVar[BridgeStatsConfigProto.Metric]
        kAdmctlDynamicRateLimit: _ClassVar[BridgeStatsConfigProto.Metric]
        kAdmctlPriorityInversionDetails: _ClassVar[BridgeStatsConfigProto.Metric]
        kNumEntriesExecutingDisk: _ClassVar[BridgeStatsConfigProto.Metric]
        kNumEntriesQueuedDisk: _ClassVar[BridgeStatsConfigProto.Metric]
        kDiskBusyPct: _ClassVar[BridgeStatsConfigProto.Metric]
        kCloudDirectDowntierBytes: _ClassVar[BridgeStatsConfigProto.Metric]
        kCloudDirectDowntierIos: _ClassVar[BridgeStatsConfigProto.Metric]
        kCloudDirectDowntierErrors: _ClassVar[BridgeStatsConfigProto.Metric]
        kCloudDirectDowntierLatency: _ClassVar[BridgeStatsConfigProto.Metric]
        kS3ListLatency: _ClassVar[BridgeStatsConfigProto.Metric]
        kS3ListIO: _ClassVar[BridgeStatsConfigProto.Metric]
        kS3ListIOError: _ClassVar[BridgeStatsConfigProto.Metric]
        kS3GetLatency: _ClassVar[BridgeStatsConfigProto.Metric]
        kS3PutLatency: _ClassVar[BridgeStatsConfigProto.Metric]
        kS3GetIO: _ClassVar[BridgeStatsConfigProto.Metric]
        kS3PutIO: _ClassVar[BridgeStatsConfigProto.Metric]
        kS3PutSize: _ClassVar[BridgeStatsConfigProto.Metric]
        kS3GetSize: _ClassVar[BridgeStatsConfigProto.Metric]
        kS3DeleteLatency: _ClassVar[BridgeStatsConfigProto.Metric]
        kS3DeleteIO: _ClassVar[BridgeStatsConfigProto.Metric]
        kS3GetBandwidth: _ClassVar[BridgeStatsConfigProto.Metric]
        kS3PutBandwidth: _ClassVar[BridgeStatsConfigProto.Metric]
        kS3GetIOError: _ClassVar[BridgeStatsConfigProto.Metric]
        kS3PutIOError: _ClassVar[BridgeStatsConfigProto.Metric]
        kS3DeleteIOError: _ClassVar[BridgeStatsConfigProto.Metric]
        kShuffleBytes: _ClassVar[BridgeStatsConfigProto.Metric]
        kShuffleIos: _ClassVar[BridgeStatsConfigProto.Metric]
        kShuffleErrors: _ClassVar[BridgeStatsConfigProto.Metric]
        kShuffleLatency: _ClassVar[BridgeStatsConfigProto.Metric]
        kBlurUpdateLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kBlurUpdateOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kBlurUpdateErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kBlurLookupLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kBlurLookupOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kBlurLookupErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kBlurScanLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kBlurScanOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kBlurScanErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv3Begin: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv3MntLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv3MntOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv3MntErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv3UmntLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv3UmntOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv3UmntErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv3CreateLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv3CreateOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv3CreateErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv3RemoveLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv3RemoveOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv3RemoveErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv3MkdirLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv3MkdirOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv3MkdirErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv3RmdirLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv3RmdirOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv3RmdirErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv3LookupLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv3LookupOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv3LookupErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv3ReaddirLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv3ReaddirOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv3ReaddirErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv3ReaddirplusLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv3ReaddirplusOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv3ReaddirplusErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv3SymlinkLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv3SymlinkOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv3SymlinkErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv3RenameLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv3RenameOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv3RenameErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv3End: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv4Begin: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv4CreateLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv4CreateOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv4CreateErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv4LookupLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv4LookupOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv4LookupErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv4ReaddirLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv4ReaddirOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv4ReaddirErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv4RemoveLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv4RemoveOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv4RemoveErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv4RenameLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv4RenameOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv4RenameErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kNFSv4End: _ClassVar[BridgeStatsConfigProto.Metric]
        kSMBBegin: _ClassVar[BridgeStatsConfigProto.Metric]
        kSMBSessionSetupLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kSMBSessionSetupOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kSMBSessionSetupErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kSMBLogoffLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kSMBLogoffOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kSMBLogoffErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kSMBTreeConnectLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kSMBTreeConnectOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kSMBTreeConnectErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kSMBTreeDisconnectLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kSMBTreeDisconnectOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kSMBTreeDisconnectErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kSMBOpenLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kSMBOpenOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kSMBOpenErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kSMBCloseLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kSMBCloseOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kSMBCloseErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kSMBCreateFileLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kSMBCreateFileOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kSMBCreateFileErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kSMBDeleteFileLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kSMBDeleteFileOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kSMBDeleteFileErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kSMBMkdirLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kSMBMkdirOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kSMBMkdirErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kSMBRmdirLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kSMBRmdirOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kSMBRmdirErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kSMBReaddirLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kSMBReaddirOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kSMBReaddirErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kSMBGetInfoLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kSMBGetInfoOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kSMBGetInfoErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kSMBSetInfoLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kSMBSetInfoOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kSMBSetInfoErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kSMBRenameLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kSMBRenameOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kSMBRenameErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kSMBEnd: _ClassVar[BridgeStatsConfigProto.Metric]
        kSnapTreeLookupLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kSnapTreeLookupOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kSnapTreeLookupErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kSnapTreeLookupCacheHits: _ClassVar[BridgeStatsConfigProto.Metric]
        kSnapTreeUpdateLatUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kSnapTreeUpdateOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kSnapTreeUpdateErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kLdapConnLatencyUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kLdapConnLatencyOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kLdapConnLatencyErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kLdapQueryLatencyUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kLdapQueryLatencyOps: _ClassVar[BridgeStatsConfigProto.Metric]
        kLdapQueryLatencyErr: _ClassVar[BridgeStatsConfigProto.Metric]
        kNumBytesDeleted: _ClassVar[BridgeStatsConfigProto.Metric]
        kDeleteIos: _ClassVar[BridgeStatsConfigProto.Metric]
        kDeleteLatencyUsecs: _ClassVar[BridgeStatsConfigProto.Metric]
        kNumDeleteErrors: _ClassVar[BridgeStatsConfigProto.Metric]
        kNumDaFilesArchived: _ClassVar[BridgeStatsConfigProto.Metric]
    kTotalIos: BridgeStatsConfigProto.Metric
    kReadIos: BridgeStatsConfigProto.Metric
    kWriteIos: BridgeStatsConfigProto.Metric
    kSequentialIos: BridgeStatsConfigProto.Metric
    kRandomIos: BridgeStatsConfigProto.Metric
    kNumBytesRead: BridgeStatsConfigProto.Metric
    kNumBytesWritten: BridgeStatsConfigProto.Metric
    kReadLatencyUsecs: BridgeStatsConfigProto.Metric
    kWriteLatencyUsecs: BridgeStatsConfigProto.Metric
    kNumReadErrors: BridgeStatsConfigProto.Metric
    kNumWriteErrors: BridgeStatsConfigProto.Metric
    kReadSizesP25: BridgeStatsConfigProto.Metric
    kReadSizesP50: BridgeStatsConfigProto.Metric
    kReadSizesP75: BridgeStatsConfigProto.Metric
    kReadSizesP99: BridgeStatsConfigProto.Metric
    kWriteSizesP25: BridgeStatsConfigProto.Metric
    kWriteSizesP50: BridgeStatsConfigProto.Metric
    kWriteSizesP75: BridgeStatsConfigProto.Metric
    kWriteSizesP99: BridgeStatsConfigProto.Metric
    kCapacityBytes: BridgeStatsConfigProto.Metric
    kSystemCapacityBytes: BridgeStatsConfigProto.Metric
    kMorphedUsageBytes: BridgeStatsConfigProto.Metric
    kUnmorphedUsageBytes: BridgeStatsConfigProto.Metric
    kSystemUsageBytes: BridgeStatsConfigProto.Metric
    kMorphedGarbageBytes: BridgeStatsConfigProto.Metric
    kUnmorphedGarbageBytes: BridgeStatsConfigProto.Metric
    kDedupMorphedUsageBytes: BridgeStatsConfigProto.Metric
    kDedupUnmorphedUsageBytes: BridgeStatsConfigProto.Metric
    kNonDedupMorphedUsageBytes: BridgeStatsConfigProto.Metric
    kNonDedupUnmorphedUsageBytes: BridgeStatsConfigProto.Metric
    kGarbageMorphedUsageBytes: BridgeStatsConfigProto.Metric
    kGarbageUnmorphedUsageBytes: BridgeStatsConfigProto.Metric
    kScribeUsageBytes: BridgeStatsConfigProto.Metric
    kBrickUsageBytes: BridgeStatsConfigProto.Metric
    kPreReplicationMorphedUsageBytes: BridgeStatsConfigProto.Metric
    kContainerECEncodeBytes: BridgeStatsConfigProto.Metric
    kContainerECEncodeOps: BridgeStatsConfigProto.Metric
    kContainerECEncodeErrors: BridgeStatsConfigProto.Metric
    kContainerECEncodeLatencyUsecs: BridgeStatsConfigProto.Metric
    kUnmorphedBytesArchived: BridgeStatsConfigProto.Metric
    kMorphedBytesArchived: BridgeStatsConfigProto.Metric
    kUnmorphedBytesRestored: BridgeStatsConfigProto.Metric
    kMorphedBytesRestored: BridgeStatsConfigProto.Metric
    kUnmorphedBytesGCed: BridgeStatsConfigProto.Metric
    kMorphedBytesGCed: BridgeStatsConfigProto.Metric
    kUnmorphedBytesUptiered: BridgeStatsConfigProto.Metric
    kMorphedBytesUptiered: BridgeStatsConfigProto.Metric
    kMorphedBytesDowntiered: BridgeStatsConfigProto.Metric
    kCloudGetCall: BridgeStatsConfigProto.Metric
    kCloudGetCallLatUsecs: BridgeStatsConfigProto.Metric
    kCloudGetCallErr: BridgeStatsConfigProto.Metric
    kCloudPutCall: BridgeStatsConfigProto.Metric
    kCloudPutCallLatUsecs: BridgeStatsConfigProto.Metric
    kCloudPutCallErr: BridgeStatsConfigProto.Metric
    kCloudPostCall: BridgeStatsConfigProto.Metric
    kCloudPostCallLatUsecs: BridgeStatsConfigProto.Metric
    kCloudPostCallErr: BridgeStatsConfigProto.Metric
    kCloudDeleteCall: BridgeStatsConfigProto.Metric
    kCloudDeleteCallLatUsecs: BridgeStatsConfigProto.Metric
    kCloudDeleteCallErr: BridgeStatsConfigProto.Metric
    kCloudHeadCall: BridgeStatsConfigProto.Metric
    kCloudHeadCallLatUsecs: BridgeStatsConfigProto.Metric
    kCloudHeadCallErr: BridgeStatsConfigProto.Metric
    kCloudUptierHeadCall: BridgeStatsConfigProto.Metric
    kCloudUptierHeadCallLatUsecs: BridgeStatsConfigProto.Metric
    kCloudUptierHeadCallErr: BridgeStatsConfigProto.Metric
    kCloudUptierPostCall: BridgeStatsConfigProto.Metric
    kCloudUptierPostCallLatUsecs: BridgeStatsConfigProto.Metric
    kCloudUptierPostCallErr: BridgeStatsConfigProto.Metric
    kCloudDowntierPutCall: BridgeStatsConfigProto.Metric
    kCloudDowntierPutCallLatUsecs: BridgeStatsConfigProto.Metric
    kCloudDowntierPutCallErr: BridgeStatsConfigProto.Metric
    kNumEntriesExecutingExternal: BridgeStatsConfigProto.Metric
    kNumEntriesQueuedExternal: BridgeStatsConfigProto.Metric
    kNumEntriesExecutingBlobstore: BridgeStatsConfigProto.Metric
    kNumEntriesQueuedBlobstore: BridgeStatsConfigProto.Metric
    kBlobstoreQueueCapacity: BridgeStatsConfigProto.Metric
    kBlobstoreQueueLoad: BridgeStatsConfigProto.Metric
    kDowntierBytes: BridgeStatsConfigProto.Metric
    kDowntierIos: BridgeStatsConfigProto.Metric
    kDowntierErrors: BridgeStatsConfigProto.Metric
    kDowntierLatency: BridgeStatsConfigProto.Metric
    kBlobDataJournalAdmittedIos: BridgeStatsConfigProto.Metric
    kBlobDataJournalBytesFlushed: BridgeStatsConfigProto.Metric
    kBlobDataJournalFlushLatencyUsecs: BridgeStatsConfigProto.Metric
    kBlobDataJournalBytesWritten: BridgeStatsConfigProto.Metric
    kBlobDataJournalWriteLatencyUsecs: BridgeStatsConfigProto.Metric
    kBlobDataJournalBytesRead: BridgeStatsConfigProto.Metric
    kBlobDataJournalReadIos: BridgeStatsConfigProto.Metric
    kBlobDataJournalReadLatencyUsecs: BridgeStatsConfigProto.Metric
    kBlobDataJournalBytesOffloaded: BridgeStatsConfigProto.Metric
    kBlobDataJournalEpochReplicaOffloadLatencyUsecs: BridgeStatsConfigProto.Metric
    kBlobDataJournalEpochReplicasOffloaded: BridgeStatsConfigProto.Metric
    kBlobMetadataJournalAdmittedIos: BridgeStatsConfigProto.Metric
    kBlobMetadataJournalBytesFlushed: BridgeStatsConfigProto.Metric
    kBlobMetadataJournalFlushLatencyUsecs: BridgeStatsConfigProto.Metric
    kBlobMetadataJournalBytesWritten: BridgeStatsConfigProto.Metric
    kBlobMetadataJournalWriteLatencyUsecs: BridgeStatsConfigProto.Metric
    kBlobMetadataJournalBytesRead: BridgeStatsConfigProto.Metric
    kBlobMetadataJournalReadIos: BridgeStatsConfigProto.Metric
    kBlobMetadataJournalReadLatencyUsecs: BridgeStatsConfigProto.Metric
    kBlobMetadataJournalBytesOffloaded: BridgeStatsConfigProto.Metric
    kBlobMetadataJournalEpochReplicaOffloadLatencyUsecs: BridgeStatsConfigProto.Metric
    kBlobMetadataJournalEpochReplicasOffloaded: BridgeStatsConfigProto.Metric
    kChunkBytesLogical: BridgeStatsConfigProto.Metric
    kChunkBytesMorphed: BridgeStatsConfigProto.Metric
    kChunkBytesPhysical: BridgeStatsConfigProto.Metric
    kNumFiles: BridgeStatsConfigProto.Metric
    kNumDirectories: BridgeStatsConfigProto.Metric
    kInodeBytesLogical: BridgeStatsConfigProto.Metric
    kUniqueChunkBytesLogical: BridgeStatsConfigProto.Metric
    kUniqueChunkBytesPhysical: BridgeStatsConfigProto.Metric
    kUniqueChunkBytesPhysicalCloud: BridgeStatsConfigProto.Metric
    kUniqueChunkBytesPhysicalLocal: BridgeStatsConfigProto.Metric
    kUniqueChunkBytesMorphed: BridgeStatsConfigProto.Metric
    kUniqueChunkBytesMorphedCloud: BridgeStatsConfigProto.Metric
    kUniqueChunkBytesMorphedLocal: BridgeStatsConfigProto.Metric
    kCreateFileLatUsecs: BridgeStatsConfigProto.Metric
    kCreateFileOps: BridgeStatsConfigProto.Metric
    kCreateFileErr: BridgeStatsConfigProto.Metric
    kMkDirLatUsecs: BridgeStatsConfigProto.Metric
    kMkDirOps: BridgeStatsConfigProto.Metric
    kMkDirErr: BridgeStatsConfigProto.Metric
    kMkNodLatUsecs: BridgeStatsConfigProto.Metric
    kMkNodOps: BridgeStatsConfigProto.Metric
    kMkNodErr: BridgeStatsConfigProto.Metric
    kSymLinkLatUsecs: BridgeStatsConfigProto.Metric
    kSymLinkOps: BridgeStatsConfigProto.Metric
    kSymLinkErr: BridgeStatsConfigProto.Metric
    kRmDirLatUsecs: BridgeStatsConfigProto.Metric
    kRmDirOps: BridgeStatsConfigProto.Metric
    kRmDirErr: BridgeStatsConfigProto.Metric
    kRemoveFileLatUsecs: BridgeStatsConfigProto.Metric
    kRemoveFileOps: BridgeStatsConfigProto.Metric
    kRemoveFileErr: BridgeStatsConfigProto.Metric
    kLookupInodeMetaDataLatUsecs: BridgeStatsConfigProto.Metric
    kLookupInodeMetaDataOps: BridgeStatsConfigProto.Metric
    kLookupInodeMetaDataErr: BridgeStatsConfigProto.Metric
    kLookupPathLatUsecs: BridgeStatsConfigProto.Metric
    kLookupPathOps: BridgeStatsConfigProto.Metric
    kLookupPathErr: BridgeStatsConfigProto.Metric
    kLookupDirectoryEntryLatUsecs: BridgeStatsConfigProto.Metric
    kLookupDirectoryEntryOps: BridgeStatsConfigProto.Metric
    kLookupDirectoryEntryErr: BridgeStatsConfigProto.Metric
    kLinkLatUsecs: BridgeStatsConfigProto.Metric
    kLinkOps: BridgeStatsConfigProto.Metric
    kLinkErr: BridgeStatsConfigProto.Metric
    kSetattrLatUsecs: BridgeStatsConfigProto.Metric
    kSetattrOps: BridgeStatsConfigProto.Metric
    kSetattrErr: BridgeStatsConfigProto.Metric
    kReaddirLatUsecs: BridgeStatsConfigProto.Metric
    kReaddirOps: BridgeStatsConfigProto.Metric
    kReaddirErr: BridgeStatsConfigProto.Metric
    kRenameLatUsecs: BridgeStatsConfigProto.Metric
    kRenameOps: BridgeStatsConfigProto.Metric
    kRenameErr: BridgeStatsConfigProto.Metric
    kCloneBytesLatUsecs: BridgeStatsConfigProto.Metric
    kCloneBytesOps: BridgeStatsConfigProto.Metric
    kCloneBytesErr: BridgeStatsConfigProto.Metric
    kCommitLatUsecs: BridgeStatsConfigProto.Metric
    kCommitOps: BridgeStatsConfigProto.Metric
    kCommitErr: BridgeStatsConfigProto.Metric
    kDeleteOrphanLatUsecs: BridgeStatsConfigProto.Metric
    kDeleteOrphanOps: BridgeStatsConfigProto.Metric
    kDeleteOrphanErr: BridgeStatsConfigProto.Metric
    kDeleteGarbageLatUsecs: BridgeStatsConfigProto.Metric
    kDeleteGarbageOps: BridgeStatsConfigProto.Metric
    kDeleteGarbageErr: BridgeStatsConfigProto.Metric
    kDirQuotaRecursiveWalkLatUsecs: BridgeStatsConfigProto.Metric
    kDirQuotaRecursiveWalkOps: BridgeStatsConfigProto.Metric
    kDirQuotaRecursiveWalkErr: BridgeStatsConfigProto.Metric
    kSnapFsFixerLatUsecs: BridgeStatsConfigProto.Metric
    kSnapFsFixerOps: BridgeStatsConfigProto.Metric
    kSnapFsFixerErr: BridgeStatsConfigProto.Metric
    kTextFilesCount: BridgeStatsConfigProto.Metric
    kTextFilesBytes: BridgeStatsConfigProto.Metric
    kVideoFilesCount: BridgeStatsConfigProto.Metric
    kVideoFilesBytes: BridgeStatsConfigProto.Metric
    kAudioFilesCount: BridgeStatsConfigProto.Metric
    kAudioFilesBytes: BridgeStatsConfigProto.Metric
    kCompressedFilesCount: BridgeStatsConfigProto.Metric
    kCompressedFilesBytes: BridgeStatsConfigProto.Metric
    kDatabaseFilesCount: BridgeStatsConfigProto.Metric
    kDatabaseFilesBytes: BridgeStatsConfigProto.Metric
    kImageFilesCount: BridgeStatsConfigProto.Metric
    kImageFilesBytes: BridgeStatsConfigProto.Metric
    kExecutableFilesCount: BridgeStatsConfigProto.Metric
    kExecutableFilesBytes: BridgeStatsConfigProto.Metric
    kLogFilesCount: BridgeStatsConfigProto.Metric
    kLogFilesBytes: BridgeStatsConfigProto.Metric
    kOtherFilesCount: BridgeStatsConfigProto.Metric
    kOtherFilesBytes: BridgeStatsConfigProto.Metric
    kStubViewReadBytes: BridgeStatsConfigProto.Metric
    kStubViewReadLatencyUsecs: BridgeStatsConfigProto.Metric
    kJournalNumEpochs: BridgeStatsConfigProto.Metric
    kAdmctlRequestsCompleted: BridgeStatsConfigProto.Metric
    kAdmctlSlotsUsed: BridgeStatsConfigProto.Metric
    kAdmctlRequestsQueued: BridgeStatsConfigProto.Metric
    kAdmctlThresholdSlots: BridgeStatsConfigProto.Metric
    kAdmctlNumPriorityInversions: BridgeStatsConfigProto.Metric
    kAdmctlReleaseEvents: BridgeStatsConfigProto.Metric
    kAdmctlThrottleEvents: BridgeStatsConfigProto.Metric
    kAdmctlDynamicRateLimit: BridgeStatsConfigProto.Metric
    kAdmctlPriorityInversionDetails: BridgeStatsConfigProto.Metric
    kNumEntriesExecutingDisk: BridgeStatsConfigProto.Metric
    kNumEntriesQueuedDisk: BridgeStatsConfigProto.Metric
    kDiskBusyPct: BridgeStatsConfigProto.Metric
    kCloudDirectDowntierBytes: BridgeStatsConfigProto.Metric
    kCloudDirectDowntierIos: BridgeStatsConfigProto.Metric
    kCloudDirectDowntierErrors: BridgeStatsConfigProto.Metric
    kCloudDirectDowntierLatency: BridgeStatsConfigProto.Metric
    kS3ListLatency: BridgeStatsConfigProto.Metric
    kS3ListIO: BridgeStatsConfigProto.Metric
    kS3ListIOError: BridgeStatsConfigProto.Metric
    kS3GetLatency: BridgeStatsConfigProto.Metric
    kS3PutLatency: BridgeStatsConfigProto.Metric
    kS3GetIO: BridgeStatsConfigProto.Metric
    kS3PutIO: BridgeStatsConfigProto.Metric
    kS3PutSize: BridgeStatsConfigProto.Metric
    kS3GetSize: BridgeStatsConfigProto.Metric
    kS3DeleteLatency: BridgeStatsConfigProto.Metric
    kS3DeleteIO: BridgeStatsConfigProto.Metric
    kS3GetBandwidth: BridgeStatsConfigProto.Metric
    kS3PutBandwidth: BridgeStatsConfigProto.Metric
    kS3GetIOError: BridgeStatsConfigProto.Metric
    kS3PutIOError: BridgeStatsConfigProto.Metric
    kS3DeleteIOError: BridgeStatsConfigProto.Metric
    kShuffleBytes: BridgeStatsConfigProto.Metric
    kShuffleIos: BridgeStatsConfigProto.Metric
    kShuffleErrors: BridgeStatsConfigProto.Metric
    kShuffleLatency: BridgeStatsConfigProto.Metric
    kBlurUpdateLatUsecs: BridgeStatsConfigProto.Metric
    kBlurUpdateOps: BridgeStatsConfigProto.Metric
    kBlurUpdateErr: BridgeStatsConfigProto.Metric
    kBlurLookupLatUsecs: BridgeStatsConfigProto.Metric
    kBlurLookupOps: BridgeStatsConfigProto.Metric
    kBlurLookupErr: BridgeStatsConfigProto.Metric
    kBlurScanLatUsecs: BridgeStatsConfigProto.Metric
    kBlurScanOps: BridgeStatsConfigProto.Metric
    kBlurScanErr: BridgeStatsConfigProto.Metric
    kNFSv3Begin: BridgeStatsConfigProto.Metric
    kNFSv3MntLatUsecs: BridgeStatsConfigProto.Metric
    kNFSv3MntOps: BridgeStatsConfigProto.Metric
    kNFSv3MntErr: BridgeStatsConfigProto.Metric
    kNFSv3UmntLatUsecs: BridgeStatsConfigProto.Metric
    kNFSv3UmntOps: BridgeStatsConfigProto.Metric
    kNFSv3UmntErr: BridgeStatsConfigProto.Metric
    kNFSv3CreateLatUsecs: BridgeStatsConfigProto.Metric
    kNFSv3CreateOps: BridgeStatsConfigProto.Metric
    kNFSv3CreateErr: BridgeStatsConfigProto.Metric
    kNFSv3RemoveLatUsecs: BridgeStatsConfigProto.Metric
    kNFSv3RemoveOps: BridgeStatsConfigProto.Metric
    kNFSv3RemoveErr: BridgeStatsConfigProto.Metric
    kNFSv3MkdirLatUsecs: BridgeStatsConfigProto.Metric
    kNFSv3MkdirOps: BridgeStatsConfigProto.Metric
    kNFSv3MkdirErr: BridgeStatsConfigProto.Metric
    kNFSv3RmdirLatUsecs: BridgeStatsConfigProto.Metric
    kNFSv3RmdirOps: BridgeStatsConfigProto.Metric
    kNFSv3RmdirErr: BridgeStatsConfigProto.Metric
    kNFSv3LookupLatUsecs: BridgeStatsConfigProto.Metric
    kNFSv3LookupOps: BridgeStatsConfigProto.Metric
    kNFSv3LookupErr: BridgeStatsConfigProto.Metric
    kNFSv3ReaddirLatUsecs: BridgeStatsConfigProto.Metric
    kNFSv3ReaddirOps: BridgeStatsConfigProto.Metric
    kNFSv3ReaddirErr: BridgeStatsConfigProto.Metric
    kNFSv3ReaddirplusLatUsecs: BridgeStatsConfigProto.Metric
    kNFSv3ReaddirplusOps: BridgeStatsConfigProto.Metric
    kNFSv3ReaddirplusErr: BridgeStatsConfigProto.Metric
    kNFSv3SymlinkLatUsecs: BridgeStatsConfigProto.Metric
    kNFSv3SymlinkOps: BridgeStatsConfigProto.Metric
    kNFSv3SymlinkErr: BridgeStatsConfigProto.Metric
    kNFSv3RenameLatUsecs: BridgeStatsConfigProto.Metric
    kNFSv3RenameOps: BridgeStatsConfigProto.Metric
    kNFSv3RenameErr: BridgeStatsConfigProto.Metric
    kNFSv3End: BridgeStatsConfigProto.Metric
    kNFSv4Begin: BridgeStatsConfigProto.Metric
    kNFSv4CreateLatUsecs: BridgeStatsConfigProto.Metric
    kNFSv4CreateOps: BridgeStatsConfigProto.Metric
    kNFSv4CreateErr: BridgeStatsConfigProto.Metric
    kNFSv4LookupLatUsecs: BridgeStatsConfigProto.Metric
    kNFSv4LookupOps: BridgeStatsConfigProto.Metric
    kNFSv4LookupErr: BridgeStatsConfigProto.Metric
    kNFSv4ReaddirLatUsecs: BridgeStatsConfigProto.Metric
    kNFSv4ReaddirOps: BridgeStatsConfigProto.Metric
    kNFSv4ReaddirErr: BridgeStatsConfigProto.Metric
    kNFSv4RemoveLatUsecs: BridgeStatsConfigProto.Metric
    kNFSv4RemoveOps: BridgeStatsConfigProto.Metric
    kNFSv4RemoveErr: BridgeStatsConfigProto.Metric
    kNFSv4RenameLatUsecs: BridgeStatsConfigProto.Metric
    kNFSv4RenameOps: BridgeStatsConfigProto.Metric
    kNFSv4RenameErr: BridgeStatsConfigProto.Metric
    kNFSv4End: BridgeStatsConfigProto.Metric
    kSMBBegin: BridgeStatsConfigProto.Metric
    kSMBSessionSetupLatUsecs: BridgeStatsConfigProto.Metric
    kSMBSessionSetupOps: BridgeStatsConfigProto.Metric
    kSMBSessionSetupErr: BridgeStatsConfigProto.Metric
    kSMBLogoffLatUsecs: BridgeStatsConfigProto.Metric
    kSMBLogoffOps: BridgeStatsConfigProto.Metric
    kSMBLogoffErr: BridgeStatsConfigProto.Metric
    kSMBTreeConnectLatUsecs: BridgeStatsConfigProto.Metric
    kSMBTreeConnectOps: BridgeStatsConfigProto.Metric
    kSMBTreeConnectErr: BridgeStatsConfigProto.Metric
    kSMBTreeDisconnectLatUsecs: BridgeStatsConfigProto.Metric
    kSMBTreeDisconnectOps: BridgeStatsConfigProto.Metric
    kSMBTreeDisconnectErr: BridgeStatsConfigProto.Metric
    kSMBOpenLatUsecs: BridgeStatsConfigProto.Metric
    kSMBOpenOps: BridgeStatsConfigProto.Metric
    kSMBOpenErr: BridgeStatsConfigProto.Metric
    kSMBCloseLatUsecs: BridgeStatsConfigProto.Metric
    kSMBCloseOps: BridgeStatsConfigProto.Metric
    kSMBCloseErr: BridgeStatsConfigProto.Metric
    kSMBCreateFileLatUsecs: BridgeStatsConfigProto.Metric
    kSMBCreateFileOps: BridgeStatsConfigProto.Metric
    kSMBCreateFileErr: BridgeStatsConfigProto.Metric
    kSMBDeleteFileLatUsecs: BridgeStatsConfigProto.Metric
    kSMBDeleteFileOps: BridgeStatsConfigProto.Metric
    kSMBDeleteFileErr: BridgeStatsConfigProto.Metric
    kSMBMkdirLatUsecs: BridgeStatsConfigProto.Metric
    kSMBMkdirOps: BridgeStatsConfigProto.Metric
    kSMBMkdirErr: BridgeStatsConfigProto.Metric
    kSMBRmdirLatUsecs: BridgeStatsConfigProto.Metric
    kSMBRmdirOps: BridgeStatsConfigProto.Metric
    kSMBRmdirErr: BridgeStatsConfigProto.Metric
    kSMBReaddirLatUsecs: BridgeStatsConfigProto.Metric
    kSMBReaddirOps: BridgeStatsConfigProto.Metric
    kSMBReaddirErr: BridgeStatsConfigProto.Metric
    kSMBGetInfoLatUsecs: BridgeStatsConfigProto.Metric
    kSMBGetInfoOps: BridgeStatsConfigProto.Metric
    kSMBGetInfoErr: BridgeStatsConfigProto.Metric
    kSMBSetInfoLatUsecs: BridgeStatsConfigProto.Metric
    kSMBSetInfoOps: BridgeStatsConfigProto.Metric
    kSMBSetInfoErr: BridgeStatsConfigProto.Metric
    kSMBRenameLatUsecs: BridgeStatsConfigProto.Metric
    kSMBRenameOps: BridgeStatsConfigProto.Metric
    kSMBRenameErr: BridgeStatsConfigProto.Metric
    kSMBEnd: BridgeStatsConfigProto.Metric
    kSnapTreeLookupLatUsecs: BridgeStatsConfigProto.Metric
    kSnapTreeLookupOps: BridgeStatsConfigProto.Metric
    kSnapTreeLookupErr: BridgeStatsConfigProto.Metric
    kSnapTreeLookupCacheHits: BridgeStatsConfigProto.Metric
    kSnapTreeUpdateLatUsecs: BridgeStatsConfigProto.Metric
    kSnapTreeUpdateOps: BridgeStatsConfigProto.Metric
    kSnapTreeUpdateErr: BridgeStatsConfigProto.Metric
    kLdapConnLatencyUsecs: BridgeStatsConfigProto.Metric
    kLdapConnLatencyOps: BridgeStatsConfigProto.Metric
    kLdapConnLatencyErr: BridgeStatsConfigProto.Metric
    kLdapQueryLatencyUsecs: BridgeStatsConfigProto.Metric
    kLdapQueryLatencyOps: BridgeStatsConfigProto.Metric
    kLdapQueryLatencyErr: BridgeStatsConfigProto.Metric
    kNumBytesDeleted: BridgeStatsConfigProto.Metric
    kDeleteIos: BridgeStatsConfigProto.Metric
    kDeleteLatencyUsecs: BridgeStatsConfigProto.Metric
    kNumDeleteErrors: BridgeStatsConfigProto.Metric
    kNumDaFilesArchived: BridgeStatsConfigProto.Metric
    TIME_TO_LIVE_SECS_FIELD_NUMBER: _ClassVar[int]
    INTERNAL_STATS_TIME_TO_LIVE_SECS_FIELD_NUMBER: _ClassVar[int]
    DISK_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    DISK_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    NODE_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    NODE_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    VIEWBOX_DISK_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    VIEWBOX_DISK_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    VIEWBOX_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    VIEWBOX_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    VIEWBOX_NODE_LOGICAL_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    VIEWBOX_NODE_LOGICAL_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    VIEWBOX_LOGICAL_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    VIEWBOX_LOGICAL_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_LOGICAL_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_LOGICAL_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    VIEWBOX_NODE_WORKLOAD_LOGICAL_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    VIEWBOX_NODE_WORKLOAD_LOGICAL_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    VIEWBOX_WORKLOAD_LOGICAL_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    VIEWBOX_WORKLOAD_LOGICAL_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_WORKLOAD_LOGICAL_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_WORKLOAD_LOGICAL_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    ICEBOX_VAULT_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    ICEBOX_VAULT_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    VIEWBOX_NODE_SCRIBE_PHYSICAL_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    VIEWBOX_NODE_SCRIBE_PHYSICAL_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    ICEBOX_JOB_VAULT_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    ICEBOX_JOB_VAULT_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_TIER_PHYSICAL_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_TIER_PHYSICAL_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    VIEWBOX_TIER_PHYSICAL_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    VIEWBOX_TIER_PHYSICAL_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    ICEBOX_CLUSTER_VAULT_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    ICEBOX_CLUSTER_VAULT_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    VIEWBOX_NODE_BRICK_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    VIEWBOX_NODE_BRICK_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    VIEW_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    VIEW_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    STATS_CONTAINER_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    STATS_CONTAINER_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    VIEWBOX_NODE_BLOB_DATA_JOURNAL_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    VIEWBOX_NODE_BLOB_DATA_JOURNAL_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    VIEWBOX_BLOB_DATA_JOURNAL_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    VIEWBOX_BLOB_DATA_JOURNAL_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_BLOB_DATA_JOURNAL_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_BLOB_DATA_JOURNAL_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    VIEWBOX_NODE_BLOB_METADATA_JOURNAL_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    VIEWBOX_NODE_BLOB_METADATA_JOURNAL_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    VIEWBOX_BLOB_METADATA_JOURNAL_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    VIEWBOX_BLOB_METADATA_JOURNAL_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_BLOB_METADATA_JOURNAL_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_BLOB_METADATA_JOURNAL_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    VIEW_BLOB_METADATA_JOURNAL_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    VIEW_BLOB_METADATA_JOURNAL_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    VIEW_PERF_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    VIEW_PERF_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    VIEWBOX_NODE_JOURNAL_USAGE_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    VIEWBOX_NODE_JOURNAL_USAGE_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    VIEWBOX_JOURNAL_USAGE_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    VIEWBOX_JOURNAL_USAGE_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    DISK_JOURNAL_USAGE_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    DISK_JOURNAL_USAGE_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    NODE_JOURNAL_USAGE_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    NODE_JOURNAL_USAGE_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_JOURNAL_USAGE_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_JOURNAL_USAGE_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    ADMCTL_COMPONENT_NODE_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    ADMCTL_COMPONENT_NODE_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    ADMCTL_COMPONENT_QUEUE_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    ADMCTL_COMPONENT_QUEUE_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    ADMCTL_COMPONENT_QUEUE_CLUSTER_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    ADMCTL_COMPONENT_QUEUE_CLUSTER_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    ICEBOX_STUB_VIEW_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    ICEBOX_STUB_VIEW_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    OBJECT_PERF_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    OBJECT_PERF_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    ICEBOX_CLOUD_DOMAIN_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    ICEBOX_CLOUD_DOMAIN_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    FILER_PERF_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    FILER_PERF_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    CLIENT_PERF_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    CLIENT_PERF_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    WORKLOAD_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    WORKLOAD_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    WORKLOAD_COMPONENT_LEVEL_PERF_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    WORKLOAD_COMPONENT_LEVEL_PERF_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    WORKLOAD_GRANULAR_LEVEL_PERF_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    WORKLOAD_GRANULAR_LEVEL_PERF_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    LDAP_PERF_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    LDAP_PERF_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    WORKLOAD_PHYSICAL_PERF_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    WORKLOAD_PHYSICAL_PERF_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    DISK_ID_ATTR_FIELD_NUMBER: _ClassVar[int]
    NODE_ID_ATTR_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_ID_ATTR_FIELD_NUMBER: _ClassVar[int]
    VIEWBOX_DISK_ID_ATTR_FIELD_NUMBER: _ClassVar[int]
    VIEWBOX_ID_ATTR_FIELD_NUMBER: _ClassVar[int]
    VIEWBOX_NAME_ATTR_FIELD_NUMBER: _ClassVar[int]
    VIEWBOX_NODE_ID_ATTR_FIELD_NUMBER: _ClassVar[int]
    VIEWBOX_NODE_WORKLOAD_ID_ATTR_FIELD_NUMBER: _ClassVar[int]
    VIEWBOX_WORKLOAD_ID_ATTR_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_WORKLOAD_ID_ATTR_FIELD_NUMBER: _ClassVar[int]
    ICEBOX_VAULT_ID_ATTR_FIELD_NUMBER: _ClassVar[int]
    ICEBOX_JOB_VAULT_ID_ATTR_FIELD_NUMBER: _ClassVar[int]
    ICEBOX_JOB_ID_ATTR_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_TIER_ID_ATTR_FIELD_NUMBER: _ClassVar[int]
    VIEWBOX_TIER_ID_ATTR_FIELD_NUMBER: _ClassVar[int]
    ICEBOX_VAULT_NAME_ATTR_FIELD_NUMBER: _ClassVar[int]
    ICEBOX_VAULT_TYPE_ATTR_FIELD_NUMBER: _ClassVar[int]
    ICEBOX_JOB_NAME_ATTR_FIELD_NUMBER: _ClassVar[int]
    VIEW_ID_ATTR_FIELD_NUMBER: _ClassVar[int]
    STATS_CONTAINER_ID_ATTR_FIELD_NUMBER: _ClassVar[int]
    ICEBOX_JOB_TYPE_ATTR_FIELD_NUMBER: _ClassVar[int]
    ICEBOX_NUM_ENTITIES_ATTR_FIELD_NUMBER: _ClassVar[int]
    COMPONENT_QUEUE_NODE_ID_ATTR_FIELD_NUMBER: _ClassVar[int]
    COMPONENT_QUEUE_ID_ATTR_FIELD_NUMBER: _ClassVar[int]
    COMPONENT_ID_ATTR_FIELD_NUMBER: _ClassVar[int]
    ICEBOX_CLOUD_DOMAIN_ID_ATTR_FIELD_NUMBER: _ClassVar[int]
    ICEBOX_CLOUD_DOMAIN_NAMESPACE_ATTR_FIELD_NUMBER: _ClassVar[int]
    FILER_PERF_STATS_ID_ATTR_FIELD_NUMBER: _ClassVar[int]
    CLIENT_PERF_STATS_ID_ATTR_FIELD_NUMBER: _ClassVar[int]
    PRIORITY_INVERSION_NODE_ID_ATTR_FIELD_NUMBER: _ClassVar[int]
    PRIORITY_INVERSION_COMPONENT_ID_ATTR_FIELD_NUMBER: _ClassVar[int]
    PRIORITY_INVERSION_CLUSTER_ID_ATTR_FIELD_NUMBER: _ClassVar[int]
    VIEWBOX_NODE_METADATA_JOURNAL_USAGE_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    VIEWBOX_NODE_METADATA_JOURNAL_USAGE_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    VIEWBOX_METADATA_JOURNAL_USAGE_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    VIEWBOX_METADATA_JOURNAL_USAGE_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    VIEW_METADATA_JOURNAL_USAGE_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    VIEW_METADATA_JOURNAL_USAGE_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    NODE_METADATA_JOURNAL_USAGE_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    NODE_METADATA_JOURNAL_USAGE_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_METADATA_JOURNAL_USAGE_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    CLUSTER_METADATA_JOURNAL_USAGE_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    DISK_METADATA_JOURNAL_USAGE_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    DISK_METADATA_JOURNAL_USAGE_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    WORKLOAD_STATS_ID_ATTR_FIELD_NUMBER: _ClassVar[int]
    WORKLOAD_COMPONENT_LEVEL_PERF_STATS_ID_ATTR_FIELD_NUMBER: _ClassVar[int]
    WORKLOAD_GRANULAR_LEVEL_PERF_STATS_ID_ATTR_FIELD_NUMBER: _ClassVar[int]
    LDAP_PERF_STATS_ID_ATTR_FIELD_NUMBER: _ClassVar[int]
    ICEBOX_ARCHIVE_FORMAT_ATTR_FIELD_NUMBER: _ClassVar[int]
    WORKLOAD_PHYSICAL_PERF_STATS_ID_ATTR_FIELD_NUMBER: _ClassVar[int]
    PRIORITY_INVERSION_NODE_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    PRIORITY_INVERSION_NODE_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    PRIORITY_INVERSION_COMPONENT_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    PRIORITY_INVERSION_COMPONENT_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    PRIORITY_INVERSION_CLUSTER_STATS_SCHEMA_NAME_FIELD_NUMBER: _ClassVar[int]
    PRIORITY_INVERSION_CLUSTER_STATS_SCHEMA_VERSION_FIELD_NUMBER: _ClassVar[int]
    time_to_live_secs: int
    internal_stats_time_to_live_secs: int
    disk_stats_schema_name: str
    disk_stats_schema_version: int
    node_stats_schema_name: str
    node_stats_schema_version: int
    cluster_stats_schema_name: str
    cluster_stats_schema_version: int
    viewbox_disk_stats_schema_name: str
    viewbox_disk_stats_schema_version: int
    viewbox_stats_schema_name: str
    viewbox_stats_schema_version: int
    viewbox_node_logical_stats_schema_name: str
    viewbox_node_logical_stats_schema_version: int
    viewbox_logical_stats_schema_name: str
    viewbox_logical_stats_schema_version: int
    cluster_logical_stats_schema_name: str
    cluster_logical_stats_schema_version: int
    viewbox_node_workload_logical_stats_schema_name: str
    viewbox_node_workload_logical_stats_schema_version: int
    viewbox_workload_logical_stats_schema_name: str
    viewbox_workload_logical_stats_schema_version: int
    cluster_workload_logical_stats_schema_name: str
    cluster_workload_logical_stats_schema_version: int
    icebox_vault_stats_schema_name: str
    icebox_vault_stats_schema_version: int
    viewbox_node_scribe_physical_stats_schema_name: str
    viewbox_node_scribe_physical_stats_schema_version: int
    icebox_job_vault_stats_schema_name: str
    icebox_job_vault_stats_schema_version: int
    cluster_tier_physical_stats_schema_name: str
    cluster_tier_physical_stats_schema_version: int
    viewbox_tier_physical_stats_schema_name: str
    viewbox_tier_physical_stats_schema_version: int
    icebox_cluster_vault_stats_schema_name: str
    icebox_cluster_vault_stats_schema_version: int
    viewbox_node_brick_stats_schema_name: str
    viewbox_node_brick_stats_schema_version: int
    view_stats_schema_name: str
    view_stats_schema_version: int
    stats_container_stats_schema_name: str
    stats_container_stats_schema_version: int
    viewbox_node_blob_data_journal_schema_name: str
    viewbox_node_blob_data_journal_schema_version: int
    viewbox_blob_data_journal_schema_name: str
    viewbox_blob_data_journal_schema_version: int
    cluster_blob_data_journal_schema_name: str
    cluster_blob_data_journal_schema_version: int
    viewbox_node_blob_metadata_journal_schema_name: str
    viewbox_node_blob_metadata_journal_schema_version: int
    viewbox_blob_metadata_journal_schema_name: str
    viewbox_blob_metadata_journal_schema_version: int
    cluster_blob_metadata_journal_schema_name: str
    cluster_blob_metadata_journal_schema_version: int
    view_blob_metadata_journal_schema_name: str
    view_blob_metadata_journal_schema_version: int
    view_perf_stats_schema_name: str
    view_perf_stats_schema_version: int
    viewbox_node_journal_usage_stats_schema_name: str
    viewbox_node_journal_usage_stats_schema_version: int
    viewbox_journal_usage_stats_schema_name: str
    viewbox_journal_usage_stats_schema_version: int
    disk_journal_usage_stats_schema_name: str
    disk_journal_usage_stats_schema_version: int
    node_journal_usage_stats_schema_name: str
    node_journal_usage_stats_schema_version: int
    cluster_journal_usage_stats_schema_name: str
    cluster_journal_usage_stats_schema_version: int
    admctl_component_node_stats_schema_name: str
    admctl_component_node_stats_schema_version: int
    admctl_component_queue_stats_schema_name: str
    admctl_component_queue_stats_schema_version: int
    admctl_component_queue_cluster_stats_schema_name: str
    admctl_component_queue_cluster_stats_schema_version: int
    icebox_stub_view_stats_schema_name: str
    icebox_stub_view_stats_schema_version: int
    object_perf_stats_schema_name: str
    object_perf_stats_schema_version: int
    icebox_cloud_domain_stats_schema_name: str
    icebox_cloud_domain_stats_schema_version: int
    filer_perf_stats_schema_name: str
    filer_perf_stats_schema_version: int
    client_perf_stats_schema_name: str
    client_perf_stats_schema_version: int
    workload_stats_schema_name: str
    workload_stats_schema_version: int
    workload_component_level_perf_stats_schema_name: str
    workload_component_level_perf_stats_schema_version: int
    workload_granular_level_perf_stats_schema_name: str
    workload_granular_level_perf_stats_schema_version: int
    ldap_perf_stats_schema_name: str
    ldap_perf_stats_schema_version: int
    workload_physical_perf_stats_schema_name: str
    workload_physical_perf_stats_schema_version: int
    disk_id_attr: str
    node_id_attr: str
    cluster_id_attr: str
    viewbox_disk_id_attr: str
    viewbox_id_attr: str
    viewbox_name_attr: str
    viewbox_node_id_attr: str
    viewbox_node_workload_id_attr: str
    viewbox_workload_id_attr: str
    cluster_workload_id_attr: str
    icebox_vault_id_attr: str
    icebox_job_vault_id_attr: str
    icebox_job_id_attr: str
    cluster_tier_id_attr: str
    viewbox_tier_id_attr: str
    icebox_vault_name_attr: str
    icebox_vault_type_attr: str
    icebox_job_name_attr: str
    view_id_attr: str
    stats_container_id_attr: str
    icebox_job_type_attr: str
    icebox_num_entities_attr: str
    component_queue_node_id_attr: str
    component_queue_id_attr: str
    component_id_attr: str
    icebox_cloud_domain_id_attr: str
    icebox_cloud_domain_namespace_attr: str
    filer_perf_stats_id_attr: str
    client_perf_stats_id_attr: str
    priority_inversion_node_id_attr: str
    priority_inversion_component_id_attr: str
    priority_inversion_cluster_id_attr: str
    viewbox_node_metadata_journal_usage_stats_schema_name: str
    viewbox_node_metadata_journal_usage_stats_schema_version: int
    viewbox_metadata_journal_usage_stats_schema_name: str
    viewbox_metadata_journal_usage_stats_schema_version: int
    view_metadata_journal_usage_stats_schema_name: str
    view_metadata_journal_usage_stats_schema_version: int
    node_metadata_journal_usage_stats_schema_name: str
    node_metadata_journal_usage_stats_schema_version: int
    cluster_metadata_journal_usage_stats_schema_name: str
    cluster_metadata_journal_usage_stats_schema_version: int
    disk_metadata_journal_usage_stats_schema_name: str
    disk_metadata_journal_usage_stats_schema_version: int
    workload_stats_id_attr: str
    workload_component_level_perf_stats_id_attr: str
    workload_granular_level_perf_stats_id_attr: str
    ldap_perf_stats_id_attr: str
    icebox_archive_format_attr: str
    workload_physical_perf_stats_id_attr: str
    priority_inversion_node_stats_schema_name: str
    priority_inversion_node_stats_schema_version: int
    priority_inversion_component_stats_schema_name: str
    priority_inversion_component_stats_schema_version: int
    priority_inversion_cluster_stats_schema_name: str
    priority_inversion_cluster_stats_schema_version: int
    def __init__(self, time_to_live_secs: _Optional[int] = ..., internal_stats_time_to_live_secs: _Optional[int] = ..., disk_stats_schema_name: _Optional[str] = ..., disk_stats_schema_version: _Optional[int] = ..., node_stats_schema_name: _Optional[str] = ..., node_stats_schema_version: _Optional[int] = ..., cluster_stats_schema_name: _Optional[str] = ..., cluster_stats_schema_version: _Optional[int] = ..., viewbox_disk_stats_schema_name: _Optional[str] = ..., viewbox_disk_stats_schema_version: _Optional[int] = ..., viewbox_stats_schema_name: _Optional[str] = ..., viewbox_stats_schema_version: _Optional[int] = ..., viewbox_node_logical_stats_schema_name: _Optional[str] = ..., viewbox_node_logical_stats_schema_version: _Optional[int] = ..., viewbox_logical_stats_schema_name: _Optional[str] = ..., viewbox_logical_stats_schema_version: _Optional[int] = ..., cluster_logical_stats_schema_name: _Optional[str] = ..., cluster_logical_stats_schema_version: _Optional[int] = ..., viewbox_node_workload_logical_stats_schema_name: _Optional[str] = ..., viewbox_node_workload_logical_stats_schema_version: _Optional[int] = ..., viewbox_workload_logical_stats_schema_name: _Optional[str] = ..., viewbox_workload_logical_stats_schema_version: _Optional[int] = ..., cluster_workload_logical_stats_schema_name: _Optional[str] = ..., cluster_workload_logical_stats_schema_version: _Optional[int] = ..., icebox_vault_stats_schema_name: _Optional[str] = ..., icebox_vault_stats_schema_version: _Optional[int] = ..., viewbox_node_scribe_physical_stats_schema_name: _Optional[str] = ..., viewbox_node_scribe_physical_stats_schema_version: _Optional[int] = ..., icebox_job_vault_stats_schema_name: _Optional[str] = ..., icebox_job_vault_stats_schema_version: _Optional[int] = ..., cluster_tier_physical_stats_schema_name: _Optional[str] = ..., cluster_tier_physical_stats_schema_version: _Optional[int] = ..., viewbox_tier_physical_stats_schema_name: _Optional[str] = ..., viewbox_tier_physical_stats_schema_version: _Optional[int] = ..., icebox_cluster_vault_stats_schema_name: _Optional[str] = ..., icebox_cluster_vault_stats_schema_version: _Optional[int] = ..., viewbox_node_brick_stats_schema_name: _Optional[str] = ..., viewbox_node_brick_stats_schema_version: _Optional[int] = ..., view_stats_schema_name: _Optional[str] = ..., view_stats_schema_version: _Optional[int] = ..., stats_container_stats_schema_name: _Optional[str] = ..., stats_container_stats_schema_version: _Optional[int] = ..., viewbox_node_blob_data_journal_schema_name: _Optional[str] = ..., viewbox_node_blob_data_journal_schema_version: _Optional[int] = ..., viewbox_blob_data_journal_schema_name: _Optional[str] = ..., viewbox_blob_data_journal_schema_version: _Optional[int] = ..., cluster_blob_data_journal_schema_name: _Optional[str] = ..., cluster_blob_data_journal_schema_version: _Optional[int] = ..., viewbox_node_blob_metadata_journal_schema_name: _Optional[str] = ..., viewbox_node_blob_metadata_journal_schema_version: _Optional[int] = ..., viewbox_blob_metadata_journal_schema_name: _Optional[str] = ..., viewbox_blob_metadata_journal_schema_version: _Optional[int] = ..., cluster_blob_metadata_journal_schema_name: _Optional[str] = ..., cluster_blob_metadata_journal_schema_version: _Optional[int] = ..., view_blob_metadata_journal_schema_name: _Optional[str] = ..., view_blob_metadata_journal_schema_version: _Optional[int] = ..., view_perf_stats_schema_name: _Optional[str] = ..., view_perf_stats_schema_version: _Optional[int] = ..., viewbox_node_journal_usage_stats_schema_name: _Optional[str] = ..., viewbox_node_journal_usage_stats_schema_version: _Optional[int] = ..., viewbox_journal_usage_stats_schema_name: _Optional[str] = ..., viewbox_journal_usage_stats_schema_version: _Optional[int] = ..., disk_journal_usage_stats_schema_name: _Optional[str] = ..., disk_journal_usage_stats_schema_version: _Optional[int] = ..., node_journal_usage_stats_schema_name: _Optional[str] = ..., node_journal_usage_stats_schema_version: _Optional[int] = ..., cluster_journal_usage_stats_schema_name: _Optional[str] = ..., cluster_journal_usage_stats_schema_version: _Optional[int] = ..., admctl_component_node_stats_schema_name: _Optional[str] = ..., admctl_component_node_stats_schema_version: _Optional[int] = ..., admctl_component_queue_stats_schema_name: _Optional[str] = ..., admctl_component_queue_stats_schema_version: _Optional[int] = ..., admctl_component_queue_cluster_stats_schema_name: _Optional[str] = ..., admctl_component_queue_cluster_stats_schema_version: _Optional[int] = ..., icebox_stub_view_stats_schema_name: _Optional[str] = ..., icebox_stub_view_stats_schema_version: _Optional[int] = ..., object_perf_stats_schema_name: _Optional[str] = ..., object_perf_stats_schema_version: _Optional[int] = ..., icebox_cloud_domain_stats_schema_name: _Optional[str] = ..., icebox_cloud_domain_stats_schema_version: _Optional[int] = ..., filer_perf_stats_schema_name: _Optional[str] = ..., filer_perf_stats_schema_version: _Optional[int] = ..., client_perf_stats_schema_name: _Optional[str] = ..., client_perf_stats_schema_version: _Optional[int] = ..., workload_stats_schema_name: _Optional[str] = ..., workload_stats_schema_version: _Optional[int] = ..., workload_component_level_perf_stats_schema_name: _Optional[str] = ..., workload_component_level_perf_stats_schema_version: _Optional[int] = ..., workload_granular_level_perf_stats_schema_name: _Optional[str] = ..., workload_granular_level_perf_stats_schema_version: _Optional[int] = ..., ldap_perf_stats_schema_name: _Optional[str] = ..., ldap_perf_stats_schema_version: _Optional[int] = ..., workload_physical_perf_stats_schema_name: _Optional[str] = ..., workload_physical_perf_stats_schema_version: _Optional[int] = ..., disk_id_attr: _Optional[str] = ..., node_id_attr: _Optional[str] = ..., cluster_id_attr: _Optional[str] = ..., viewbox_disk_id_attr: _Optional[str] = ..., viewbox_id_attr: _Optional[str] = ..., viewbox_name_attr: _Optional[str] = ..., viewbox_node_id_attr: _Optional[str] = ..., viewbox_node_workload_id_attr: _Optional[str] = ..., viewbox_workload_id_attr: _Optional[str] = ..., cluster_workload_id_attr: _Optional[str] = ..., icebox_vault_id_attr: _Optional[str] = ..., icebox_job_vault_id_attr: _Optional[str] = ..., icebox_job_id_attr: _Optional[str] = ..., cluster_tier_id_attr: _Optional[str] = ..., viewbox_tier_id_attr: _Optional[str] = ..., icebox_vault_name_attr: _Optional[str] = ..., icebox_vault_type_attr: _Optional[str] = ..., icebox_job_name_attr: _Optional[str] = ..., view_id_attr: _Optional[str] = ..., stats_container_id_attr: _Optional[str] = ..., icebox_job_type_attr: _Optional[str] = ..., icebox_num_entities_attr: _Optional[str] = ..., component_queue_node_id_attr: _Optional[str] = ..., component_queue_id_attr: _Optional[str] = ..., component_id_attr: _Optional[str] = ..., icebox_cloud_domain_id_attr: _Optional[str] = ..., icebox_cloud_domain_namespace_attr: _Optional[str] = ..., filer_perf_stats_id_attr: _Optional[str] = ..., client_perf_stats_id_attr: _Optional[str] = ..., priority_inversion_node_id_attr: _Optional[str] = ..., priority_inversion_component_id_attr: _Optional[str] = ..., priority_inversion_cluster_id_attr: _Optional[str] = ..., viewbox_node_metadata_journal_usage_stats_schema_name: _Optional[str] = ..., viewbox_node_metadata_journal_usage_stats_schema_version: _Optional[int] = ..., viewbox_metadata_journal_usage_stats_schema_name: _Optional[str] = ..., viewbox_metadata_journal_usage_stats_schema_version: _Optional[int] = ..., view_metadata_journal_usage_stats_schema_name: _Optional[str] = ..., view_metadata_journal_usage_stats_schema_version: _Optional[int] = ..., node_metadata_journal_usage_stats_schema_name: _Optional[str] = ..., node_metadata_journal_usage_stats_schema_version: _Optional[int] = ..., cluster_metadata_journal_usage_stats_schema_name: _Optional[str] = ..., cluster_metadata_journal_usage_stats_schema_version: _Optional[int] = ..., disk_metadata_journal_usage_stats_schema_name: _Optional[str] = ..., disk_metadata_journal_usage_stats_schema_version: _Optional[int] = ..., workload_stats_id_attr: _Optional[str] = ..., workload_component_level_perf_stats_id_attr: _Optional[str] = ..., workload_granular_level_perf_stats_id_attr: _Optional[str] = ..., ldap_perf_stats_id_attr: _Optional[str] = ..., icebox_archive_format_attr: _Optional[str] = ..., workload_physical_perf_stats_id_attr: _Optional[str] = ..., priority_inversion_node_stats_schema_name: _Optional[str] = ..., priority_inversion_node_stats_schema_version: _Optional[int] = ..., priority_inversion_component_stats_schema_name: _Optional[str] = ..., priority_inversion_component_stats_schema_version: _Optional[int] = ..., priority_inversion_cluster_stats_schema_name: _Optional[str] = ..., priority_inversion_cluster_stats_schema_version: _Optional[int] = ...) -> None: ...
