# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: experimental/jayaram/rpc/file_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from open_util.net import protorpc_pb2 as open__util_dot_net_dot_protorpc__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+experimental/jayaram/rpc/file_service.proto\x12!cohesity.experimental.jayaram.rpc\x1a\x1copen_util/net/protorpc.proto\"#\n\x0cHelloRequest\x12\x13\n\x04name\x18\x01 \x01(\t:\x05World\"\x1f\n\x0bHelloResult\x12\x10\n\x08greeting\x18\x01 \x01(\t\"%\n\x11\x43reateFileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x02(\t\"$\n\x12\x43reateFileResponse\x12\x0e\n\x06status\x18\x01 \x02(\t\"G\n\x15WriteFileRangeRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0e\n\x06offset\x18\x02 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\"N\n\x16WriteFileRangeResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x10\n\x08response\x18\x02 \x01(\t\x12\x12\n\nbytes_read\x18\x03 \x01(\x05\"H\n\x14ReadFileRangeRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0e\n\x06offset\x18\x02 \x01(\x05\x12\x0e\n\x06length\x18\x03 \x01(\x05\"9\n\x15ReadFileRangeResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x10\n\x08response\x18\x02 \x01(\t2\x96\x04\n\x0b\x46ileService\x12j\n\x05Greet\x12/.cohesity.experimental.jayaram.rpc.HelloRequest\x1a..cohesity.experimental.jayaram.rpc.HelloResult\"\x00\x12{\n\nCreateFile\x12\x34.cohesity.experimental.jayaram.rpc.CreateFileRequest\x1a\x35.cohesity.experimental.jayaram.rpc.CreateFileResponse\"\x00\x12\x87\x01\n\x0eWriteFileRange\x12\x38.cohesity.experimental.jayaram.rpc.WriteFileRangeRequest\x1a\x39.cohesity.experimental.jayaram.rpc.WriteFileRangeResponse\"\x00\x12\x84\x01\n\rReadFileRange\x12\x37.cohesity.experimental.jayaram.rpc.ReadFileRangeRequest\x1a\x38.cohesity.experimental.jayaram.rpc.ReadFileRangeResponse\"\x00\x1a\r\x80\xf1\x04\xd0\x0f\x88\xf1\x04\x01\x90\xf1\x04\x02\x42\x03\x80\x01\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'experimental.jayaram.rpc.file_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\200\001\001'
  _globals['_FILESERVICE']._loaded_options = None
  _globals['_FILESERVICE']._serialized_options = b'\200\361\004\320\017\210\361\004\001\220\361\004\002'
  _globals['_HELLOREQUEST']._serialized_start=112
  _globals['_HELLOREQUEST']._serialized_end=147
  _globals['_HELLORESULT']._serialized_start=149
  _globals['_HELLORESULT']._serialized_end=180
  _globals['_CREATEFILEREQUEST']._serialized_start=182
  _globals['_CREATEFILEREQUEST']._serialized_end=219
  _globals['_CREATEFILERESPONSE']._serialized_start=221
  _globals['_CREATEFILERESPONSE']._serialized_end=257
  _globals['_WRITEFILERANGEREQUEST']._serialized_start=259
  _globals['_WRITEFILERANGEREQUEST']._serialized_end=330
  _globals['_WRITEFILERANGERESPONSE']._serialized_start=332
  _globals['_WRITEFILERANGERESPONSE']._serialized_end=410
  _globals['_READFILERANGEREQUEST']._serialized_start=412
  _globals['_READFILERANGEREQUEST']._serialized_end=484
  _globals['_READFILERANGERESPONSE']._serialized_start=486
  _globals['_READFILERANGERESPONSE']._serialized_end=543
  _globals['_FILESERVICE']._serialized_start=546
  _globals['_FILESERVICE']._serialized_end=1080
# @@protoc_insertion_point(module_scope)
