# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bridge/filer_event_log/filer_event_log.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bridge.audit_log import audit_log_pb2 as bridge_dot_audit__log_dot_audit__log__pb2
from bridge.smb_portal import smb_portal_metadata_pb2 as bridge_dot_smb__portal_dot_smb__portal__metadata__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,bridge/filer_event_log/filer_event_log.proto\x12\x1f\x63ohesity.bridge.filer_event_log\x1a bridge/audit_log/audit_log.proto\x1a+bridge/smb_portal/smb_portal_metadata.proto\"\xa0\x01\n\x10\x46ilerEventRecord\x12<\n\x0c\x61udit_record\x18\x01 \x01(\x0b\x32&.cohesity.bridge.audit_log.AuditRecord\x12N\n\x19smb_entity_metadata_proto\x18\x02 \x01(\x0b\x32+.cohesity.bridge.smb.SmbEntityMetadataProto')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bridge.filer_event_log.filer_event_log_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILEREVENTRECORD']._serialized_start=161
  _globals['_FILEREVENTRECORD']._serialized_end=321
# @@protoc_insertion_point(module_scope)
