# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bridge/vault/qa/on_disk_object_metadata.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-bridge/vault/qa/on_disk_object_metadata.proto\x12\x18\x63ohesity.bridge.vault.qa\"\x95\x02\n\x19OnDiskObjectMetadataProto\x12\x13\n\x0bobject_name\x18\x01 \x02(\t\x12\x1e\n\x16object_part_size_bytes\x18\x02 \x01(\x03\x12\x19\n\x11object_size_bytes\x18\x03 \x01(\x03\x12\x18\n\x10num_object_parts\x18\x04 \x01(\x05\x12\x14\n\x0cis_finalized\x18\x05 \x01(\x08\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\x12!\n\x19restore_status_call_count\x18\x07 \x01(\x05\x12\x15\n\rstorage_class\x18\x08 \x01(\t\x12\x1b\n\x13\x63reation_time_usecs\x18\t \x01(\x03\x12\x0c\n\x04\x63tag\x18\n \x01(\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bridge.vault.qa.on_disk_object_metadata_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ONDISKOBJECTMETADATAPROTO']._serialized_start=76
  _globals['_ONDISKOBJECTMETADATAPROTO']._serialized_end=353
# @@protoc_insertion_point(module_scope)
