# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: experimental/sisir/rpc/fs_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from open_util.net import protorpc_pb2 as open__util_dot_net_dot_protorpc__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'experimental/sisir/rpc/fs_service.proto\x12\x1f\x63ohesity.experimental.sisir.rpc\x1a\x1copen_util/net/protorpc.proto\"%\n\x11\x43reateFileRequest\x12\x10\n\x08pathname\x18\x01 \x01(\t\"6\n\x12\x43reateFileResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x12\x10\n\x08\x65rr_code\x18\x02 \x01(\x05\"G\n\x14ReadFileRangeRequest\x12\x10\n\x08pathname\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x12\x0e\n\x06offset\x18\x03 \x01(\x03\"9\n\x15ReadFileRangeResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x12\x10\n\x08\x65rr_code\x18\x02 \x01(\x05\"H\n\x15WriteFileRangeRequest\x12\x10\n\x08pathname\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x12\x0e\n\x06offset\x18\x03 \x01(\x03\":\n\x16WriteFileRangeResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x12\x10\n\x08\x65rr_code\x18\x02 \x01(\x05\x32\x9c\x03\n\tFsService\x12w\n\nCreateFile\x12\x32.cohesity.experimental.sisir.rpc.CreateFileRequest\x1a\x33.cohesity.experimental.sisir.rpc.CreateFileResponse\"\x00\x12\x80\x01\n\rReadFileRange\x12\x35.cohesity.experimental.sisir.rpc.ReadFileRangeRequest\x1a\x36.cohesity.experimental.sisir.rpc.ReadFileRangeResponse\"\x00\x12\x83\x01\n\x0eWriteFileRange\x12\x36.cohesity.experimental.sisir.rpc.WriteFileRangeRequest\x1a\x37.cohesity.experimental.sisir.rpc.WriteFileRangeResponse\"\x00\x1a\r\x80\xf1\x04\xe8\x07\x88\xf1\x04\x01\x90\xf1\x04\x02\x42\x03\x80\x01\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'experimental.sisir.rpc.fs_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\200\001\001'
  _globals['_FSSERVICE']._loaded_options = None
  _globals['_FSSERVICE']._serialized_options = b'\200\361\004\350\007\210\361\004\001\220\361\004\002'
  _globals['_CREATEFILEREQUEST']._serialized_start=106
  _globals['_CREATEFILEREQUEST']._serialized_end=143
  _globals['_CREATEFILERESPONSE']._serialized_start=145
  _globals['_CREATEFILERESPONSE']._serialized_end=199
  _globals['_READFILERANGEREQUEST']._serialized_start=201
  _globals['_READFILERANGEREQUEST']._serialized_end=272
  _globals['_READFILERANGERESPONSE']._serialized_start=274
  _globals['_READFILERANGERESPONSE']._serialized_end=331
  _globals['_WRITEFILERANGEREQUEST']._serialized_start=333
  _globals['_WRITEFILERANGEREQUEST']._serialized_end=405
  _globals['_WRITEFILERANGERESPONSE']._serialized_start=407
  _globals['_WRITEFILERANGERESPONSE']._serialized_end=465
  _globals['_FSSERVICE']._serialized_start=468
  _globals['_FSSERVICE']._serialized_end=880
# @@protoc_insertion_point(module_scope)
