# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: magneto/connectors/gpfs/gpfs_param.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from magneto.base.entities import gpfs_pb2 as magneto_dot_base_dot_entities_dot_gpfs__pb2
from magneto.base import magneto_pb2 as magneto_dot_base_dot_magneto__pb2
try:
  magneto_dot_base_dot_env__params__pb2 = magneto_dot_base_dot_magneto__pb2.magneto_dot_base_dot_env__params__pb2
except AttributeError:
  magneto_dot_base_dot_env__params__pb2 = magneto_dot_base_dot_magneto__pb2.magneto.base.env_params_pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(magneto/connectors/gpfs/gpfs_param.proto\x12\x15\x63ohesity.magneto.gpfs\x1a magneto/base/entities/gpfs.proto\x1a\x1amagneto/base/magneto.proto\"O\n\x11\x43reateSnapshotArg\x12\x12\n\nfilesystem\x18\x01 \x01(\t\x12\x0f\n\x07\x66ileset\x18\x02 \x01(\t\x12\x15\n\rsnapshot_name\x18\x03 \x01(\t\"a\n\x14\x43reateSnapshotResult\x12I\n\x15\x66ileset_snapshot_info\x18\x01 \x01(\x0b\x32*.cohesity.magneto.gpfs.FilesetSnapshotInfo\"I\n\x0bSnapshotArg\x12\x12\n\nfilesystem\x18\x01 \x01(\t\x12\x0f\n\x07\x66ileset\x18\x02 \x01(\t\x12\x15\n\rsnapshot_name\x18\x03 \x01(\t\"\x16\n\x14\x44\x65leteSnapshotResult\"\x19\n\x17QueryEntityHierarchyArg\"^\n\x1aQueryEntityHierarchyResult\x12@\n\x10\x65ntity_hierarchy\x18\x01 \x01(\x0b\x32&.cohesity.magneto.EntityHierarchyProto\"\x15\n\x13\x46\x65tchIpAddressesArg\"*\n\x16\x46\x65tchIpAddressesResult\x12\x10\n\x08ip_addrs\x18\x01 \x03(\t\"5\n\x0cNfsExportArg\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x17\n\x0fnfs_clients_str\x18\x02 \x01(\t\"6\n\x0fNfsExportResult\x12\x0e\n\x06job_id\x18\x01 \x01(\x04\x12\x13\n\x0bnfs_clients\x18\x02 \x03(\t\"X\n\x12UpdateNfsExportArg\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0e\n\x06nfsadd\x18\x02 \x01(\t\x12\x11\n\tnfsremove\x18\x03 \x01(\t\x12\x11\n\tnfschange\x18\x04 \x01(\t\"\x1f\n\rGetJobInfoArg\x12\x0e\n\x06job_id\x18\x01 \x01(\x04\"\x12\n\x10GetJobInfoResult')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'magneto.connectors.gpfs.gpfs_param_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATESNAPSHOTARG']._serialized_start=129
  _globals['_CREATESNAPSHOTARG']._serialized_end=208
  _globals['_CREATESNAPSHOTRESULT']._serialized_start=210
  _globals['_CREATESNAPSHOTRESULT']._serialized_end=307
  _globals['_SNAPSHOTARG']._serialized_start=309
  _globals['_SNAPSHOTARG']._serialized_end=382
  _globals['_DELETESNAPSHOTRESULT']._serialized_start=384
  _globals['_DELETESNAPSHOTRESULT']._serialized_end=406
  _globals['_QUERYENTITYHIERARCHYARG']._serialized_start=408
  _globals['_QUERYENTITYHIERARCHYARG']._serialized_end=433
  _globals['_QUERYENTITYHIERARCHYRESULT']._serialized_start=435
  _globals['_QUERYENTITYHIERARCHYRESULT']._serialized_end=529
  _globals['_FETCHIPADDRESSESARG']._serialized_start=531
  _globals['_FETCHIPADDRESSESARG']._serialized_end=552
  _globals['_FETCHIPADDRESSESRESULT']._serialized_start=554
  _globals['_FETCHIPADDRESSESRESULT']._serialized_end=596
  _globals['_NFSEXPORTARG']._serialized_start=598
  _globals['_NFSEXPORTARG']._serialized_end=651
  _globals['_NFSEXPORTRESULT']._serialized_start=653
  _globals['_NFSEXPORTRESULT']._serialized_end=707
  _globals['_UPDATENFSEXPORTARG']._serialized_start=709
  _globals['_UPDATENFSEXPORTARG']._serialized_end=797
  _globals['_GETJOBINFOARG']._serialized_start=799
  _globals['_GETJOBINFOARG']._serialized_end=830
  _globals['_GETJOBINFORESULT']._serialized_start=832
  _globals['_GETJOBINFORESULT']._serialized_end=850
# @@protoc_insertion_point(module_scope)
