# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nexus/go/pki/ca/grpc/api/error.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$nexus/go/pki/ca/grpc/api/error.proto\x12\x0f\x63ohesity.ca.api\"\xae\x01\n\nErrorProto\x12\x38\n\x04type\x18\x01 \x01(\x0e\x32 .cohesity.ca.api.ErrorProto.Type:\x08kNoError\x12\x11\n\terror_msg\x18\x02 \x01(\t\"S\n\x04Type\x12\x0c\n\x08kNoError\x10\x00\x12\x0e\n\nkCertError\x10\x01\x12\n\n\x06kRetry\x10\x02\x12\x0c\n\x08kTimeout\x10\x03\x12\x13\n\x0fkTransportError\x10\x04\x42\x16Z\x14\x63ohesity/ca/grpc/api')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nexus.go.pki.ca.grpc.api.error_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\024cohesity/ca/grpc/api'
  _globals['_ERRORPROTO']._serialized_start=58
  _globals['_ERRORPROTO']._serialized_end=232
  _globals['_ERRORPROTO_TYPE']._serialized_start=149
  _globals['_ERRORPROTO_TYPE']._serialized_end=232
# @@protoc_insertion_point(module_scope)
