# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: experimental/harish/exp/file_io_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from open_util.net import protorpc_pb2 as open__util_dot_net_dot_protorpc__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-experimental/harish/exp/file_io_service.proto\x12 cohesity.experimental.harish.exp\x1a\x1copen_util/net/protorpc.proto\"!\n\rCreateRequest\x12\x10\n\x08pathname\x18\x01 \x01(\t\"2\n\x0e\x43reateResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x12\x10\n\x08\x65rr_code\x18\x02 \x01(\x05\"A\n\x0bReadRequest\x12\x10\n\x08pathname\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x12\x11\n\x06offset\x18\x03 \x01(\x03:\x01\x30\">\n\x0cReadResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x12\x10\n\x08\x65rr_code\x18\x02 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\"P\n\x0cWriteRequest\x12\x10\n\x08pathname\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x12\x11\n\x06offset\x18\x03 \x01(\x03:\x01\x30\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\"1\n\rWriteResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x12\x10\n\x08\x65rr_code\x18\x02 \x01(\x05\x32\xdf\x02\n\nFIOService\x12m\n\x06\x43reate\x12/.cohesity.experimental.harish.exp.CreateRequest\x1a\x30.cohesity.experimental.harish.exp.CreateResponse\"\x00\x12g\n\x04Read\x12-.cohesity.experimental.harish.exp.ReadRequest\x1a..cohesity.experimental.harish.exp.ReadResponse\"\x00\x12j\n\x05Write\x12..cohesity.experimental.harish.exp.WriteRequest\x1a/.cohesity.experimental.harish.exp.WriteResponse\"\x00\x1a\r\x80\xf1\x04\xe8\x07\x88\xf1\x04\x01\x90\xf1\x04\x02\x42\x03\x80\x01\x01')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'experimental.harish.exp.file_io_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\200\001\001'
  _globals['_FIOSERVICE']._loaded_options = None
  _globals['_FIOSERVICE']._serialized_options = b'\200\361\004\350\007\210\361\004\001\220\361\004\002'
  _globals['_CREATEREQUEST']._serialized_start=113
  _globals['_CREATEREQUEST']._serialized_end=146
  _globals['_CREATERESPONSE']._serialized_start=148
  _globals['_CREATERESPONSE']._serialized_end=198
  _globals['_READREQUEST']._serialized_start=200
  _globals['_READREQUEST']._serialized_end=265
  _globals['_READRESPONSE']._serialized_start=267
  _globals['_READRESPONSE']._serialized_end=329
  _globals['_WRITEREQUEST']._serialized_start=331
  _globals['_WRITEREQUEST']._serialized_end=411
  _globals['_WRITERESPONSE']._serialized_start=413
  _globals['_WRITERESPONSE']._serialized_end=462
  _globals['_FIOSERVICE']._serialized_start=465
  _globals['_FIOSERVICE']._serialized_end=816
# @@protoc_insertion_point(module_scope)
