name: Ansible Lint
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # this Action should follow steps to set up Python build environment
    - name: Install dependencies
      run: |
        sudo python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then sudo pip install -r requirements.txt; fi
    - name: Perform sanity testing with ansible-test
      uses: ansible-community/ansible-test-gh-action@release/v1
      with:
        ansible-core-version: stable-2.15
        testing-type: sanity
