from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class ErrorProto(_message.Message):
    __slots__ = ()
    class Type(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
        __slots__ = ()
        kNoError: _ClassVar[ErrorProto.Type]
        kInvalidRequest: _ClassVar[ErrorProto.Type]
        kNotCluster: _ClassVar[ErrorProto.Type]
        kGandalfNonExistentKey: _ClassVar[ErrorProto.Type]
        kStale: _ClassVar[ErrorProto.Type]
        kRetry: _ClassVar[ErrorProto.Type]
        kTimeout: _ClassVar[ErrorProto.Type]
        kProtoParseError: _ClassVar[ErrorProto.Type]
        kConfigWatchCancel: _ClassVar[ErrorProto.Type]
        kNonExistentView: _ClassVar[ErrorProto.Type]
        kViewAlreadyExists: _ClassVar[ErrorProto.Type]
        kBridgeError: _ClassVar[ErrorProto.Type]
        kClusterAuditError: _ClassVar[ErrorProto.Type]
        kScribeTimeout: _ClassVar[ErrorProto.Type]
        kScribeTableNonExistent: _ClassVar[ErrorProto.Type]
        kScribeInvalidSequencer: _ClassVar[ErrorProto.Type]
        kScribeCASFailure: _ClassVar[ErrorProto.Type]
        kUnknownScribeError: _ClassVar[ErrorProto.Type]
        kScribeNonExistentKey: _ClassVar[ErrorProto.Type]
        kLibrarianError: _ClassVar[ErrorProto.Type]
        kLibrarianNonExistentIndex: _ClassVar[ErrorProto.Type]
        kLuceneMaxClauseCount: _ClassVar[ErrorProto.Type]
        kServiceDown: _ClassVar[ErrorProto.Type]
        kAntivirusProviderUnavailable: _ClassVar[ErrorProto.Type]
        kQuotaExceeded: _ClassVar[ErrorProto.Type]
        kDomainControllerNotReachable: _ClassVar[ErrorProto.Type]
        kDomainControllerIncompatible: _ClassVar[ErrorProto.Type]
        kNisConfigClientError: _ClassVar[ErrorProto.Type]
        kBifrostError: _ClassVar[ErrorProto.Type]
        kKeystoneNotReachable: _ClassVar[ErrorProto.Type]
        kKeystoneValidationError: _ClassVar[ErrorProto.Type]
        kAdNotReachable: _ClassVar[ErrorProto.Type]
        kAdNeedFixing: _ClassVar[ErrorProto.Type]
        kAdIncorrectPassword: _ClassVar[ErrorProto.Type]
        kAdUnknownUser: _ClassVar[ErrorProto.Type]
        kAdPermissionDenied: _ClassVar[ErrorProto.Type]
        kAdAlreadyExists: _ClassVar[ErrorProto.Type]
        kNoAdServices: _ClassVar[ErrorProto.Type]
        kAdInvalidUsernameOrPassword: _ClassVar[ErrorProto.Type]
        kNonExistentLdap: _ClassVar[ErrorProto.Type]
        kLdapClientError: _ClassVar[ErrorProto.Type]
        kAdKerberosInternalError: _ClassVar[ErrorProto.Type]
        kAdLdapInternalError: _ClassVar[ErrorProto.Type]
        kAdClientError: _ClassVar[ErrorProto.Type]
        kPasswordExpired: _ClassVar[ErrorProto.Type]
        kMachineAccountNeedFixing: _ClassVar[ErrorProto.Type]
        kNotFound: _ClassVar[ErrorProto.Type]
        kNotIndexed: _ClassVar[ErrorProto.Type]
        kSnapshotExpired: _ClassVar[ErrorProto.Type]
        kBaseSnapshotExpired: _ClassVar[ErrorProto.Type]
        kBaseSnapshotNotFound: _ClassVar[ErrorProto.Type]
        kInvalid: _ClassVar[ErrorProto.Type]
        kNoCrackedFileIndex: _ClassVar[ErrorProto.Type]
        kOutOfSpace: _ClassVar[ErrorProto.Type]
        kLibrarianStaleCookie: _ClassVar[ErrorProto.Type]
        kRigelMode: _ClassVar[ErrorProto.Type]
        kBifrostAlreadyExists: _ClassVar[ErrorProto.Type]
        kPathNonExistent: _ClassVar[ErrorProto.Type]
        kKerberosClientError: _ClassVar[ErrorProto.Type]
        kKerbAlreadyExists: _ClassVar[ErrorProto.Type]
        kKerbIncorrectPassword: _ClassVar[ErrorProto.Type]
        kKerbInvalidUsernameOrPassword: _ClassVar[ErrorProto.Type]
        kKerbNeedFixing: _ClassVar[ErrorProto.Type]
        kKerbPermissionDenied: _ClassVar[ErrorProto.Type]
        kKerbUnknownUser: _ClassVar[ErrorProto.Type]
        kUDAConfigError: _ClassVar[ErrorProto.Type]
        kS3AbacAlreadyExists: _ClassVar[ErrorProto.Type]
        kS3AbacConfigClientError: _ClassVar[ErrorProto.Type]
        kTMActionAlreadyExists: _ClassVar[ErrorProto.Type]
        kTenantMigrationActionError: _ClassVar[ErrorProto.Type]
        kNonExistent: _ClassVar[ErrorProto.Type]
        kAlreadyExists: _ClassVar[ErrorProto.Type]
        kNotSupported: _ClassVar[ErrorProto.Type]
        kViewNotEmpty: _ClassVar[ErrorProto.Type]
        kCloneDataJournalFailed: _ClassVar[ErrorProto.Type]
        kNeedExclusivePin: _ClassVar[ErrorProto.Type]
        kNotDirectory: _ClassVar[ErrorProto.Type]
        kNotSynchronized: _ClassVar[ErrorProto.Type]
        kBridgeBadCookie: _ClassVar[ErrorProto.Type]
        kCASError: _ClassVar[ErrorProto.Type]
    kNoError: ErrorProto.Type
    kInvalidRequest: ErrorProto.Type
    kNotCluster: ErrorProto.Type
    kGandalfNonExistentKey: ErrorProto.Type
    kStale: ErrorProto.Type
    kRetry: ErrorProto.Type
    kTimeout: ErrorProto.Type
    kProtoParseError: ErrorProto.Type
    kConfigWatchCancel: ErrorProto.Type
    kNonExistentView: ErrorProto.Type
    kViewAlreadyExists: ErrorProto.Type
    kBridgeError: ErrorProto.Type
    kClusterAuditError: ErrorProto.Type
    kScribeTimeout: ErrorProto.Type
    kScribeTableNonExistent: ErrorProto.Type
    kScribeInvalidSequencer: ErrorProto.Type
    kScribeCASFailure: ErrorProto.Type
    kUnknownScribeError: ErrorProto.Type
    kScribeNonExistentKey: ErrorProto.Type
    kLibrarianError: ErrorProto.Type
    kLibrarianNonExistentIndex: ErrorProto.Type
    kLuceneMaxClauseCount: ErrorProto.Type
    kServiceDown: ErrorProto.Type
    kAntivirusProviderUnavailable: ErrorProto.Type
    kQuotaExceeded: ErrorProto.Type
    kDomainControllerNotReachable: ErrorProto.Type
    kDomainControllerIncompatible: ErrorProto.Type
    kNisConfigClientError: ErrorProto.Type
    kBifrostError: ErrorProto.Type
    kKeystoneNotReachable: ErrorProto.Type
    kKeystoneValidationError: ErrorProto.Type
    kAdNotReachable: ErrorProto.Type
    kAdNeedFixing: ErrorProto.Type
    kAdIncorrectPassword: ErrorProto.Type
    kAdUnknownUser: ErrorProto.Type
    kAdPermissionDenied: ErrorProto.Type
    kAdAlreadyExists: ErrorProto.Type
    kNoAdServices: ErrorProto.Type
    kAdInvalidUsernameOrPassword: ErrorProto.Type
    kNonExistentLdap: ErrorProto.Type
    kLdapClientError: ErrorProto.Type
    kAdKerberosInternalError: ErrorProto.Type
    kAdLdapInternalError: ErrorProto.Type
    kAdClientError: ErrorProto.Type
    kPasswordExpired: ErrorProto.Type
    kMachineAccountNeedFixing: ErrorProto.Type
    kNotFound: ErrorProto.Type
    kNotIndexed: ErrorProto.Type
    kSnapshotExpired: ErrorProto.Type
    kBaseSnapshotExpired: ErrorProto.Type
    kBaseSnapshotNotFound: ErrorProto.Type
    kInvalid: ErrorProto.Type
    kNoCrackedFileIndex: ErrorProto.Type
    kOutOfSpace: ErrorProto.Type
    kLibrarianStaleCookie: ErrorProto.Type
    kRigelMode: ErrorProto.Type
    kBifrostAlreadyExists: ErrorProto.Type
    kPathNonExistent: ErrorProto.Type
    kKerberosClientError: ErrorProto.Type
    kKerbAlreadyExists: ErrorProto.Type
    kKerbIncorrectPassword: ErrorProto.Type
    kKerbInvalidUsernameOrPassword: ErrorProto.Type
    kKerbNeedFixing: ErrorProto.Type
    kKerbPermissionDenied: ErrorProto.Type
    kKerbUnknownUser: ErrorProto.Type
    kUDAConfigError: ErrorProto.Type
    kS3AbacAlreadyExists: ErrorProto.Type
    kS3AbacConfigClientError: ErrorProto.Type
    kTMActionAlreadyExists: ErrorProto.Type
    kTenantMigrationActionError: ErrorProto.Type
    kNonExistent: ErrorProto.Type
    kAlreadyExists: ErrorProto.Type
    kNotSupported: ErrorProto.Type
    kViewNotEmpty: ErrorProto.Type
    kCloneDataJournalFailed: ErrorProto.Type
    kNeedExclusivePin: ErrorProto.Type
    kNotDirectory: ErrorProto.Type
    kNotSynchronized: ErrorProto.Type
    kBridgeBadCookie: ErrorProto.Type
    kCASError: ErrorProto.Type
    def __init__(self) -> None: ...
