from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from typing import ClassVar as _ClassVar, Optional as _Optional

DESCRIPTOR: _descriptor.FileDescriptor

class RestEndpointsProto(_message.Message):
    __slots__ = ("proxy_base_url", "lookup_key_endpoint", "update_key_endpoint", "delete_key_endpoint", "watch_cluster_config_endpoint", "alloc_ids_endpoint", "create_view_endpoint", "clone_view_endpoint", "delete_view_endpoint", "get_views_endpoint", "edit_view_endpoint", "rename_view_endpoint", "set_smb_permissions_view_endpoint", "create_active_directory_entry_endpoint", "delete_active_directory_entry_endpoint", "get_nfs_connections_endpoint", "get_smb_connections_endpoint", "write_cluster_audit_log_record_endpoint", "get_active_smb_file_opens_endpoint", "close_active_smb_file_open_endpoint", "create_view_alias_endpoint", "delete_view_alias_endpoint", "search_active_directory_endpoint", "get_iris_master_endpoint", "overwrite_view_endpoint", "write_column_to_scribe_endpoint", "read_column_from_scribe_endpoint", "clone_view_directory_endpoint", "centrify_zones_endpoint", "get_users_quota_and_usage_for_view_endpoint", "update_user_quota_overrides_in_view_endpoint", "get_quota_and_usage_for_user_in_all_views_endpoint", "get_user_quota_summary_for_view_endpoint", "get_user_quota_summary_for_user_endpoint", "edit_active_directory_entry_endpoint", "search_librarian_endpoint", "update_file_lock_endpoint", "get_file_lock_endpoint", "restore_view_aliases_endpoint", "create_ldap_provider_endpoint", "edit_ldap_provider_endpoint", "delete_ldap_provider_endpoint", "get_ldap_provider_status_endpoint", "get_trusted_domains_endpoint", "get_ad_info_from_sids_endpoint", "authenticate_user_endpoint", "get_bifrost_server_info_for_tenant", "list_infected_files_endpoint", "modify_infected_file_endpoint", "delete_infected_file_endpoint", "get_metadata_capacity_endpoint", "get_ad_user_group_sids_endpoint", "get_icap_connection_status_endpoint", "list_nlm_locks_endpoint", "clear_nlm_locks_endpoint", "get_prepare_cracked_file_index", "get_get_cracked_file_index", "get_release_cracked_file_index", "update_dir_quota", "get_view_dir_quota_info", "modify_view_alias_endpoint", "get_domain_controller_status_endpoint", "create_or_update_keystone_endpoint", "create_or_update_swift_endpoint", "create_nis_provider_entry_endpoint", "delete_nis_provider_entry_endpoint", "edit_nis_provider_entry_endpoint", "clear_bridge_cache_endpoint", "update_bifrost_reverse_tunnel_endpoint", "create_view_template_endpoint", "read_view_template_by_id_endpoint", "delete_view_template_endpoint", "modify_view_template_endpoint", "read_view_templates_endpoint", "register_swift_endpoint", "unregister_swift_endpoint", "get_bifrost_tenants_capabilities_endpoint", "lookup_path_endpoint", "create_file_endpoint", "create_entity_endpoint", "write_entity_endpoint", "read_file_endpoint", "remove_entity_endpoint", "create_network_realm_endpoint", "update_network_realm_endpoint", "get_network_realms_endpoint", "delete_network_realm_endpoint", "create_connector_endpoint", "update_connector_endpoint", "get_connectors_endpoint", "delete_connector_endpoint", "get_domain_controllers_endpoint", "create_kerberos_provider_entry_endpoint", "delete_kerberos_provider_entry_endpoint", "edit_kerberos_provider_entry_endpoint", "get_connections_summary_endpoint", "update_ldap_bind_credentials_endpoint", "edit_preferred_dcs_endpoint", "create_uda_connector_config_endpoint", "update_uda_connector_config_endpoint", "delete_uda_connector_config_endpoint", "clone_secure_view_endpoint", "clone_secure_view_directory_endpoint", "modify_ca_paths_endpoint", "trigger_trusted_domains_discovery_endpoint", "get_trusted_domains_discovery_status_endpoint", "create_or_update_s3_abac_server_endpoint", "delete_s3_abac_server_endpoint")
    PROXY_BASE_URL_FIELD_NUMBER: _ClassVar[int]
    LOOKUP_KEY_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    UPDATE_KEY_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    DELETE_KEY_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    WATCH_CLUSTER_CONFIG_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    ALLOC_IDS_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    CREATE_VIEW_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    CLONE_VIEW_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    DELETE_VIEW_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    GET_VIEWS_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    EDIT_VIEW_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    RENAME_VIEW_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    SET_SMB_PERMISSIONS_VIEW_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    CREATE_ACTIVE_DIRECTORY_ENTRY_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    DELETE_ACTIVE_DIRECTORY_ENTRY_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    GET_NFS_CONNECTIONS_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    GET_SMB_CONNECTIONS_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    WRITE_CLUSTER_AUDIT_LOG_RECORD_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    GET_ACTIVE_SMB_FILE_OPENS_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    CLOSE_ACTIVE_SMB_FILE_OPEN_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    CREATE_VIEW_ALIAS_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    DELETE_VIEW_ALIAS_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    SEARCH_ACTIVE_DIRECTORY_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    GET_IRIS_MASTER_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    OVERWRITE_VIEW_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    WRITE_COLUMN_TO_SCRIBE_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    READ_COLUMN_FROM_SCRIBE_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    CLONE_VIEW_DIRECTORY_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    CENTRIFY_ZONES_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    GET_USERS_QUOTA_AND_USAGE_FOR_VIEW_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    UPDATE_USER_QUOTA_OVERRIDES_IN_VIEW_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    GET_QUOTA_AND_USAGE_FOR_USER_IN_ALL_VIEWS_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    GET_USER_QUOTA_SUMMARY_FOR_VIEW_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    GET_USER_QUOTA_SUMMARY_FOR_USER_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    EDIT_ACTIVE_DIRECTORY_ENTRY_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    SEARCH_LIBRARIAN_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    UPDATE_FILE_LOCK_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    GET_FILE_LOCK_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    RESTORE_VIEW_ALIASES_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    CREATE_LDAP_PROVIDER_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    EDIT_LDAP_PROVIDER_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    DELETE_LDAP_PROVIDER_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    GET_LDAP_PROVIDER_STATUS_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    GET_TRUSTED_DOMAINS_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    GET_AD_INFO_FROM_SIDS_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    AUTHENTICATE_USER_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    GET_BIFROST_SERVER_INFO_FOR_TENANT_FIELD_NUMBER: _ClassVar[int]
    LIST_INFECTED_FILES_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    MODIFY_INFECTED_FILE_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    DELETE_INFECTED_FILE_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    GET_METADATA_CAPACITY_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    GET_AD_USER_GROUP_SIDS_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    GET_ICAP_CONNECTION_STATUS_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    LIST_NLM_LOCKS_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    CLEAR_NLM_LOCKS_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    GET_PREPARE_CRACKED_FILE_INDEX_FIELD_NUMBER: _ClassVar[int]
    GET_GET_CRACKED_FILE_INDEX_FIELD_NUMBER: _ClassVar[int]
    GET_RELEASE_CRACKED_FILE_INDEX_FIELD_NUMBER: _ClassVar[int]
    UPDATE_DIR_QUOTA_FIELD_NUMBER: _ClassVar[int]
    GET_VIEW_DIR_QUOTA_INFO_FIELD_NUMBER: _ClassVar[int]
    MODIFY_VIEW_ALIAS_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    GET_DOMAIN_CONTROLLER_STATUS_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    CREATE_OR_UPDATE_KEYSTONE_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    CREATE_OR_UPDATE_SWIFT_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    CREATE_NIS_PROVIDER_ENTRY_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    DELETE_NIS_PROVIDER_ENTRY_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    EDIT_NIS_PROVIDER_ENTRY_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    CLEAR_BRIDGE_CACHE_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    UPDATE_BIFROST_REVERSE_TUNNEL_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    CREATE_VIEW_TEMPLATE_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    READ_VIEW_TEMPLATE_BY_ID_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    DELETE_VIEW_TEMPLATE_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    MODIFY_VIEW_TEMPLATE_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    READ_VIEW_TEMPLATES_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    REGISTER_SWIFT_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    UNREGISTER_SWIFT_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    GET_BIFROST_TENANTS_CAPABILITIES_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    LOOKUP_PATH_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    CREATE_FILE_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    CREATE_ENTITY_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    WRITE_ENTITY_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    READ_FILE_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    REMOVE_ENTITY_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    CREATE_NETWORK_REALM_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    UPDATE_NETWORK_REALM_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    GET_NETWORK_REALMS_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    DELETE_NETWORK_REALM_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    CREATE_CONNECTOR_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    UPDATE_CONNECTOR_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    GET_CONNECTORS_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    DELETE_CONNECTOR_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    GET_DOMAIN_CONTROLLERS_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    CREATE_KERBEROS_PROVIDER_ENTRY_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    DELETE_KERBEROS_PROVIDER_ENTRY_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    EDIT_KERBEROS_PROVIDER_ENTRY_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    GET_CONNECTIONS_SUMMARY_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    UPDATE_LDAP_BIND_CREDENTIALS_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    EDIT_PREFERRED_DCS_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    CREATE_UDA_CONNECTOR_CONFIG_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    UPDATE_UDA_CONNECTOR_CONFIG_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    DELETE_UDA_CONNECTOR_CONFIG_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    CLONE_SECURE_VIEW_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    CLONE_SECURE_VIEW_DIRECTORY_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    MODIFY_CA_PATHS_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    TRIGGER_TRUSTED_DOMAINS_DISCOVERY_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    GET_TRUSTED_DOMAINS_DISCOVERY_STATUS_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    CREATE_OR_UPDATE_S3_ABAC_SERVER_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    DELETE_S3_ABAC_SERVER_ENDPOINT_FIELD_NUMBER: _ClassVar[int]
    proxy_base_url: str
    lookup_key_endpoint: str
    update_key_endpoint: str
    delete_key_endpoint: str
    watch_cluster_config_endpoint: str
    alloc_ids_endpoint: str
    create_view_endpoint: str
    clone_view_endpoint: str
    delete_view_endpoint: str
    get_views_endpoint: str
    edit_view_endpoint: str
    rename_view_endpoint: str
    set_smb_permissions_view_endpoint: str
    create_active_directory_entry_endpoint: str
    delete_active_directory_entry_endpoint: str
    get_nfs_connections_endpoint: str
    get_smb_connections_endpoint: str
    write_cluster_audit_log_record_endpoint: str
    get_active_smb_file_opens_endpoint: str
    close_active_smb_file_open_endpoint: str
    create_view_alias_endpoint: str
    delete_view_alias_endpoint: str
    search_active_directory_endpoint: str
    get_iris_master_endpoint: str
    overwrite_view_endpoint: str
    write_column_to_scribe_endpoint: str
    read_column_from_scribe_endpoint: str
    clone_view_directory_endpoint: str
    centrify_zones_endpoint: str
    get_users_quota_and_usage_for_view_endpoint: str
    update_user_quota_overrides_in_view_endpoint: str
    get_quota_and_usage_for_user_in_all_views_endpoint: str
    get_user_quota_summary_for_view_endpoint: str
    get_user_quota_summary_for_user_endpoint: str
    edit_active_directory_entry_endpoint: str
    search_librarian_endpoint: str
    update_file_lock_endpoint: str
    get_file_lock_endpoint: str
    restore_view_aliases_endpoint: str
    create_ldap_provider_endpoint: str
    edit_ldap_provider_endpoint: str
    delete_ldap_provider_endpoint: str
    get_ldap_provider_status_endpoint: str
    get_trusted_domains_endpoint: str
    get_ad_info_from_sids_endpoint: str
    authenticate_user_endpoint: str
    get_bifrost_server_info_for_tenant: str
    list_infected_files_endpoint: str
    modify_infected_file_endpoint: str
    delete_infected_file_endpoint: str
    get_metadata_capacity_endpoint: str
    get_ad_user_group_sids_endpoint: str
    get_icap_connection_status_endpoint: str
    list_nlm_locks_endpoint: str
    clear_nlm_locks_endpoint: str
    get_prepare_cracked_file_index: str
    get_get_cracked_file_index: str
    get_release_cracked_file_index: str
    update_dir_quota: str
    get_view_dir_quota_info: str
    modify_view_alias_endpoint: str
    get_domain_controller_status_endpoint: str
    create_or_update_keystone_endpoint: str
    create_or_update_swift_endpoint: str
    create_nis_provider_entry_endpoint: str
    delete_nis_provider_entry_endpoint: str
    edit_nis_provider_entry_endpoint: str
    clear_bridge_cache_endpoint: str
    update_bifrost_reverse_tunnel_endpoint: str
    create_view_template_endpoint: str
    read_view_template_by_id_endpoint: str
    delete_view_template_endpoint: str
    modify_view_template_endpoint: str
    read_view_templates_endpoint: str
    register_swift_endpoint: str
    unregister_swift_endpoint: str
    get_bifrost_tenants_capabilities_endpoint: str
    lookup_path_endpoint: str
    create_file_endpoint: str
    create_entity_endpoint: str
    write_entity_endpoint: str
    read_file_endpoint: str
    remove_entity_endpoint: str
    create_network_realm_endpoint: str
    update_network_realm_endpoint: str
    get_network_realms_endpoint: str
    delete_network_realm_endpoint: str
    create_connector_endpoint: str
    update_connector_endpoint: str
    get_connectors_endpoint: str
    delete_connector_endpoint: str
    get_domain_controllers_endpoint: str
    create_kerberos_provider_entry_endpoint: str
    delete_kerberos_provider_entry_endpoint: str
    edit_kerberos_provider_entry_endpoint: str
    get_connections_summary_endpoint: str
    update_ldap_bind_credentials_endpoint: str
    edit_preferred_dcs_endpoint: str
    create_uda_connector_config_endpoint: str
    update_uda_connector_config_endpoint: str
    delete_uda_connector_config_endpoint: str
    clone_secure_view_endpoint: str
    clone_secure_view_directory_endpoint: str
    modify_ca_paths_endpoint: str
    trigger_trusted_domains_discovery_endpoint: str
    get_trusted_domains_discovery_status_endpoint: str
    create_or_update_s3_abac_server_endpoint: str
    delete_s3_abac_server_endpoint: str
    def __init__(self, proxy_base_url: _Optional[str] = ..., lookup_key_endpoint: _Optional[str] = ..., update_key_endpoint: _Optional[str] = ..., delete_key_endpoint: _Optional[str] = ..., watch_cluster_config_endpoint: _Optional[str] = ..., alloc_ids_endpoint: _Optional[str] = ..., create_view_endpoint: _Optional[str] = ..., clone_view_endpoint: _Optional[str] = ..., delete_view_endpoint: _Optional[str] = ..., get_views_endpoint: _Optional[str] = ..., edit_view_endpoint: _Optional[str] = ..., rename_view_endpoint: _Optional[str] = ..., set_smb_permissions_view_endpoint: _Optional[str] = ..., create_active_directory_entry_endpoint: _Optional[str] = ..., delete_active_directory_entry_endpoint: _Optional[str] = ..., get_nfs_connections_endpoint: _Optional[str] = ..., get_smb_connections_endpoint: _Optional[str] = ..., write_cluster_audit_log_record_endpoint: _Optional[str] = ..., get_active_smb_file_opens_endpoint: _Optional[str] = ..., close_active_smb_file_open_endpoint: _Optional[str] = ..., create_view_alias_endpoint: _Optional[str] = ..., delete_view_alias_endpoint: _Optional[str] = ..., search_active_directory_endpoint: _Optional[str] = ..., get_iris_master_endpoint: _Optional[str] = ..., overwrite_view_endpoint: _Optional[str] = ..., write_column_to_scribe_endpoint: _Optional[str] = ..., read_column_from_scribe_endpoint: _Optional[str] = ..., clone_view_directory_endpoint: _Optional[str] = ..., centrify_zones_endpoint: _Optional[str] = ..., get_users_quota_and_usage_for_view_endpoint: _Optional[str] = ..., update_user_quota_overrides_in_view_endpoint: _Optional[str] = ..., get_quota_and_usage_for_user_in_all_views_endpoint: _Optional[str] = ..., get_user_quota_summary_for_view_endpoint: _Optional[str] = ..., get_user_quota_summary_for_user_endpoint: _Optional[str] = ..., edit_active_directory_entry_endpoint: _Optional[str] = ..., search_librarian_endpoint: _Optional[str] = ..., update_file_lock_endpoint: _Optional[str] = ..., get_file_lock_endpoint: _Optional[str] = ..., restore_view_aliases_endpoint: _Optional[str] = ..., create_ldap_provider_endpoint: _Optional[str] = ..., edit_ldap_provider_endpoint: _Optional[str] = ..., delete_ldap_provider_endpoint: _Optional[str] = ..., get_ldap_provider_status_endpoint: _Optional[str] = ..., get_trusted_domains_endpoint: _Optional[str] = ..., get_ad_info_from_sids_endpoint: _Optional[str] = ..., authenticate_user_endpoint: _Optional[str] = ..., get_bifrost_server_info_for_tenant: _Optional[str] = ..., list_infected_files_endpoint: _Optional[str] = ..., modify_infected_file_endpoint: _Optional[str] = ..., delete_infected_file_endpoint: _Optional[str] = ..., get_metadata_capacity_endpoint: _Optional[str] = ..., get_ad_user_group_sids_endpoint: _Optional[str] = ..., get_icap_connection_status_endpoint: _Optional[str] = ..., list_nlm_locks_endpoint: _Optional[str] = ..., clear_nlm_locks_endpoint: _Optional[str] = ..., get_prepare_cracked_file_index: _Optional[str] = ..., get_get_cracked_file_index: _Optional[str] = ..., get_release_cracked_file_index: _Optional[str] = ..., update_dir_quota: _Optional[str] = ..., get_view_dir_quota_info: _Optional[str] = ..., modify_view_alias_endpoint: _Optional[str] = ..., get_domain_controller_status_endpoint: _Optional[str] = ..., create_or_update_keystone_endpoint: _Optional[str] = ..., create_or_update_swift_endpoint: _Optional[str] = ..., create_nis_provider_entry_endpoint: _Optional[str] = ..., delete_nis_provider_entry_endpoint: _Optional[str] = ..., edit_nis_provider_entry_endpoint: _Optional[str] = ..., clear_bridge_cache_endpoint: _Optional[str] = ..., update_bifrost_reverse_tunnel_endpoint: _Optional[str] = ..., create_view_template_endpoint: _Optional[str] = ..., read_view_template_by_id_endpoint: _Optional[str] = ..., delete_view_template_endpoint: _Optional[str] = ..., modify_view_template_endpoint: _Optional[str] = ..., read_view_templates_endpoint: _Optional[str] = ..., register_swift_endpoint: _Optional[str] = ..., unregister_swift_endpoint: _Optional[str] = ..., get_bifrost_tenants_capabilities_endpoint: _Optional[str] = ..., lookup_path_endpoint: _Optional[str] = ..., create_file_endpoint: _Optional[str] = ..., create_entity_endpoint: _Optional[str] = ..., write_entity_endpoint: _Optional[str] = ..., read_file_endpoint: _Optional[str] = ..., remove_entity_endpoint: _Optional[str] = ..., create_network_realm_endpoint: _Optional[str] = ..., update_network_realm_endpoint: _Optional[str] = ..., get_network_realms_endpoint: _Optional[str] = ..., delete_network_realm_endpoint: _Optional[str] = ..., create_connector_endpoint: _Optional[str] = ..., update_connector_endpoint: _Optional[str] = ..., get_connectors_endpoint: _Optional[str] = ..., delete_connector_endpoint: _Optional[str] = ..., get_domain_controllers_endpoint: _Optional[str] = ..., create_kerberos_provider_entry_endpoint: _Optional[str] = ..., delete_kerberos_provider_entry_endpoint: _Optional[str] = ..., edit_kerberos_provider_entry_endpoint: _Optional[str] = ..., get_connections_summary_endpoint: _Optional[str] = ..., update_ldap_bind_credentials_endpoint: _Optional[str] = ..., edit_preferred_dcs_endpoint: _Optional[str] = ..., create_uda_connector_config_endpoint: _Optional[str] = ..., update_uda_connector_config_endpoint: _Optional[str] = ..., delete_uda_connector_config_endpoint: _Optional[str] = ..., clone_secure_view_endpoint: _Optional[str] = ..., clone_secure_view_directory_endpoint: _Optional[str] = ..., modify_ca_paths_endpoint: _Optional[str] = ..., trigger_trusted_domains_discovery_endpoint: _Optional[str] = ..., get_trusted_domains_discovery_status_endpoint: _Optional[str] = ..., create_or_update_s3_abac_server_endpoint: _Optional[str] = ..., delete_s3_abac_server_endpoint: _Optional[str] = ...) -> None: ...
