# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from magneto.connectors.imanis import imanis_grpc_service_pb2 as magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in magneto/connectors/imanis/imanis_grpc_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class ImanisGRpcServiceStub(object):
    """-----------------------------------------------------------------------------

    Service discriptor containing all the gRPC services exposed by the Imanis
    API Server.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetConnectorInfo = channel.unary_unary(
                '/cohesity.magneto.imanis.ImanisGRpcService/GetConnectorInfo',
                request_serializer=magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.GetConnectorInfoArg.SerializeToString,
                response_deserializer=magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.GetConnectorInfoResult.FromString,
                _registered_method=True)
        self.GetImanisVersion = channel.unary_unary(
                '/cohesity.magneto.imanis.ImanisGRpcService/GetImanisVersion',
                request_serializer=magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.GetImanisVersionArg.SerializeToString,
                response_deserializer=magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.GetImanisVersionResult.FromString,
                _registered_method=True)
        self.DiscoverSource = channel.unary_unary(
                '/cohesity.magneto.imanis.ImanisGRpcService/DiscoverSource',
                request_serializer=magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.DiscoverSourceArg.SerializeToString,
                response_deserializer=magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.DiscoverSourceResult.FromString,
                _registered_method=True)
        self.VerifySource = channel.unary_unary(
                '/cohesity.magneto.imanis.ImanisGRpcService/VerifySource',
                request_serializer=magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.VerifySourceArg.SerializeToString,
                response_deserializer=magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.VerifySourceResult.FromString,
                _registered_method=True)
        self.GetEntities = channel.unary_unary(
                '/cohesity.magneto.imanis.ImanisGRpcService/GetEntities',
                request_serializer=magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.GetEntitiesArg.SerializeToString,
                response_deserializer=magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.GetEntitiesResult.FromString,
                _registered_method=True)
        self.RunJob = channel.unary_unary(
                '/cohesity.magneto.imanis.ImanisGRpcService/RunJob',
                request_serializer=magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.RunJobArg.SerializeToString,
                response_deserializer=magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.RunJobResult.FromString,
                _registered_method=True)
        self.CancelJob = channel.unary_unary(
                '/cohesity.magneto.imanis.ImanisGRpcService/CancelJob',
                request_serializer=magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.CancelJobArg.SerializeToString,
                response_deserializer=magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.CancelJobResult.FromString,
                _registered_method=True)
        self.GetJobStatus = channel.unary_unary(
                '/cohesity.magneto.imanis.ImanisGRpcService/GetJobStatus',
                request_serializer=magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.GetJobStatusArg.SerializeToString,
                response_deserializer=magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.GetJobStatusResult.FromString,
                _registered_method=True)
        self.GetEntitySize = channel.unary_unary(
                '/cohesity.magneto.imanis.ImanisGRpcService/GetEntitySize',
                request_serializer=magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.GetEntitySizeArg.SerializeToString,
                response_deserializer=magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.GetEntitySizeResult.FromString,
                _registered_method=True)
        self.GetCompletedJobDetails = channel.unary_unary(
                '/cohesity.magneto.imanis.ImanisGRpcService/GetCompletedJobDetails',
                request_serializer=magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.GetCompletedJobDetailsArg.SerializeToString,
                response_deserializer=magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.GetCompletedJobDetailsResult.FromString,
                _registered_method=True)
        self.SendEntities = channel.unary_unary(
                '/cohesity.magneto.imanis.ImanisGRpcService/SendEntities',
                request_serializer=magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.SendEntitiesArg.SerializeToString,
                response_deserializer=magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.SendEntitiesResult.FromString,
                _registered_method=True)


class ImanisGRpcServiceServicer(object):
    """-----------------------------------------------------------------------------

    Service discriptor containing all the gRPC services exposed by the Imanis
    API Server.
    """

    def GetConnectorInfo(self, request, context):
        """Check connectivity with Imanis API Server.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetImanisVersion(self, request, context):
        """Fetch Imanis version.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DiscoverSource(self, request, context):
        """Discover more properties of the Source.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifySource(self, request, context):
        """Verify the source configuration and connection.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEntities(self, request, context):
        """Fetch entities for the source. If a parent entity is specified then
        it's children are returned, else the root level entities are returned.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunJob(self, request, context):
        """Run a job, with arguments provided.
        The job could be a backup, recovery, compaction or GC.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelJob(self, request, context):
        """Cancel a running job.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobStatus(self, request, context):
        """Get status of a job, also report its progress.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEntitySize(self, request, context):
        """Get size of an entity.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCompletedJobDetails(self, request, context):
        """Get task details. This api is invoked when TaskStatus is reported as
        kCompleted.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendEntities(self, request, context):
        """Send Entities. This api is invoked before RunJobArg for kBackup,
        kRecovery and before calling UpdateCdpService API.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImanisGRpcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetConnectorInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConnectorInfo,
                    request_deserializer=magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.GetConnectorInfoArg.FromString,
                    response_serializer=magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.GetConnectorInfoResult.SerializeToString,
            ),
            'GetImanisVersion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetImanisVersion,
                    request_deserializer=magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.GetImanisVersionArg.FromString,
                    response_serializer=magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.GetImanisVersionResult.SerializeToString,
            ),
            'DiscoverSource': grpc.unary_unary_rpc_method_handler(
                    servicer.DiscoverSource,
                    request_deserializer=magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.DiscoverSourceArg.FromString,
                    response_serializer=magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.DiscoverSourceResult.SerializeToString,
            ),
            'VerifySource': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifySource,
                    request_deserializer=magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.VerifySourceArg.FromString,
                    response_serializer=magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.VerifySourceResult.SerializeToString,
            ),
            'GetEntities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEntities,
                    request_deserializer=magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.GetEntitiesArg.FromString,
                    response_serializer=magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.GetEntitiesResult.SerializeToString,
            ),
            'RunJob': grpc.unary_unary_rpc_method_handler(
                    servicer.RunJob,
                    request_deserializer=magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.RunJobArg.FromString,
                    response_serializer=magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.RunJobResult.SerializeToString,
            ),
            'CancelJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelJob,
                    request_deserializer=magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.CancelJobArg.FromString,
                    response_serializer=magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.CancelJobResult.SerializeToString,
            ),
            'GetJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobStatus,
                    request_deserializer=magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.GetJobStatusArg.FromString,
                    response_serializer=magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.GetJobStatusResult.SerializeToString,
            ),
            'GetEntitySize': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEntitySize,
                    request_deserializer=magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.GetEntitySizeArg.FromString,
                    response_serializer=magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.GetEntitySizeResult.SerializeToString,
            ),
            'GetCompletedJobDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCompletedJobDetails,
                    request_deserializer=magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.GetCompletedJobDetailsArg.FromString,
                    response_serializer=magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.GetCompletedJobDetailsResult.SerializeToString,
            ),
            'SendEntities': grpc.unary_unary_rpc_method_handler(
                    servicer.SendEntities,
                    request_deserializer=magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.SendEntitiesArg.FromString,
                    response_serializer=magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.SendEntitiesResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cohesity.magneto.imanis.ImanisGRpcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cohesity.magneto.imanis.ImanisGRpcService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ImanisGRpcService(object):
    """-----------------------------------------------------------------------------

    Service discriptor containing all the gRPC services exposed by the Imanis
    API Server.
    """

    @staticmethod
    def GetConnectorInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohesity.magneto.imanis.ImanisGRpcService/GetConnectorInfo',
            magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.GetConnectorInfoArg.SerializeToString,
            magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.GetConnectorInfoResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetImanisVersion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohesity.magneto.imanis.ImanisGRpcService/GetImanisVersion',
            magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.GetImanisVersionArg.SerializeToString,
            magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.GetImanisVersionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DiscoverSource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohesity.magneto.imanis.ImanisGRpcService/DiscoverSource',
            magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.DiscoverSourceArg.SerializeToString,
            magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.DiscoverSourceResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifySource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohesity.magneto.imanis.ImanisGRpcService/VerifySource',
            magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.VerifySourceArg.SerializeToString,
            magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.VerifySourceResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEntities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohesity.magneto.imanis.ImanisGRpcService/GetEntities',
            magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.GetEntitiesArg.SerializeToString,
            magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.GetEntitiesResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohesity.magneto.imanis.ImanisGRpcService/RunJob',
            magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.RunJobArg.SerializeToString,
            magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.RunJobResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohesity.magneto.imanis.ImanisGRpcService/CancelJob',
            magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.CancelJobArg.SerializeToString,
            magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.CancelJobResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohesity.magneto.imanis.ImanisGRpcService/GetJobStatus',
            magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.GetJobStatusArg.SerializeToString,
            magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.GetJobStatusResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEntitySize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohesity.magneto.imanis.ImanisGRpcService/GetEntitySize',
            magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.GetEntitySizeArg.SerializeToString,
            magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.GetEntitySizeResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCompletedJobDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohesity.magneto.imanis.ImanisGRpcService/GetCompletedJobDetails',
            magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.GetCompletedJobDetailsArg.SerializeToString,
            magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.GetCompletedJobDetailsResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendEntities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cohesity.magneto.imanis.ImanisGRpcService/SendEntities',
            magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.SendEntitiesArg.SerializeToString,
            magneto_dot_connectors_dot_imanis_dot_imanis__grpc__service__pb2.SendEntitiesResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
